/* eslint-disable @next/next/no-html-link-for-pages -- The clear control intentionally performs a clean document navigation. */
import { redirect } from "next/navigation";
import { ManufacturerHeader } from "@/components/manufacturer-shell";
import { getActiveBrand } from "@/lib/branding";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { createUserInvitation } from "./actions";
import InvitationControls from "./invitation-controls";
import MemberControls from "./member-controls";

type Person={user_id:string;email:string;role:string;status:string;company_id?:string;company_name?:string};
type Invite={id:string;email:string;invitation_type:string;role:string;status:string;company_name:string|null;expires_at:string;email_status?:string;email_attempts?:number;last_email_at?:string|null;email_error?:string|null};
type Delivery={id:string;email_status:string;email_attempts:number;last_email_at:string|null;email_error:string|null};
type Dashboard={manufacturer_members:Person[];retailer_members:Person[];retailers:{id:string;name:string}[];invitations:Invite[]};

const roleDescription:Record<string,string>={owner:"Full academy control, including branding, users, content, reporting, and owner access.",admin:"Manages the academy, users, content, assignments, and reporting.",content_manager:"Builds and manages products, quizzes, courses, assignments, and offers.",viewer:"Views the academy and permitted reports without changing content or access.",manager:"Manages learners and training activity for their retailer.",learner:"Completes assigned training and accesses eligible academy resources."};
const invitationClosed=(status:string)=>["accepted","cancelled","revoked"].includes(status);
const matches=(value:string|null|undefined,query:string)=>!query||String(value??"").toLowerCase().includes(query);

export default async function UsersPage({searchParams}:{searchParams:Promise<{error?:string;invited?:string;updated?:string;email?:string;q?:string;directory?:string;role?:string}>}){
 const params=await searchParams;const supabase=await createSupabaseServerClient();const [{data:auth},brand]=await Promise.all([supabase.auth.getUser(),getActiveBrand()]);
 if(!auth.user)redirect("/login");if(!brand?.can_manage_brand)redirect("/app");
 const [{data},{data:deliveryRows}]=await Promise.all([supabase.rpc("manufacturer_people_dashboard"),supabase.rpc("invitation_delivery_directory")]);const dashboard=(data??{manufacturer_members:[],retailer_members:[],retailers:[],invitations:[]}) as Dashboard;const deliveries=new Map(((deliveryRows??[]) as Delivery[]).map(item=>[item.id,item]));dashboard.invitations=dashboard.invitations.map(invite=>({...invite,...deliveries.get(invite.id)}));
 const query=String(params.q??"").trim().toLowerCase(),directory=String(params.directory??"all"),role=String(params.role??"all");
 const personMatches=(person:Person)=>matches(person.email,query)||matches(person.company_name,query);
 const roleMatches=(value:string)=>role==="all"||value===role;
 const manufacturerMembers=directory!=="retailer"&&directory!=="invitations"?dashboard.manufacturer_members.filter(person=>personMatches(person)&&roleMatches(person.role)):[];
 const retailerMembers=directory!=="manufacturer"&&directory!=="invitations"?dashboard.retailer_members.filter(person=>personMatches(person)&&roleMatches(person.role)):[];
 const invitationMatches=(invite:Invite)=>(matches(invite.email,query)||matches(invite.company_name,query))&&roleMatches(invite.role);
 const openInvitations=directory!=="manufacturer"&&directory!=="retailer"?dashboard.invitations.filter(i=>!invitationClosed(i.status)&&invitationMatches(i)):[];
 const invitationHistory=directory!=="manufacturer"&&directory!=="retailer"?dashboard.invitations.filter(i=>invitationClosed(i.status)&&invitationMatches(i)):[];
 return <div className="min-h-screen bg-[#f4f4f2] text-black"><ManufacturerHeader brand={brand} email={auth.user.email}/><main className="mx-auto max-w-7xl px-5 py-10 lg:px-8 lg:py-14">
  <p className="text-sm font-extrabold uppercase italic tracking-[0.2em]" style={{color:brand.primary_color}}>Access management</p><h1 className="mt-2 text-4xl font-extrabold uppercase tracking-tight sm:text-5xl">Users & invitations</h1><p className="mt-3 max-w-2xl text-black/60">Invite users, update their roles, or remove access to this brand without deleting their account or training history.</p>
  {params.error&&<div className="mt-6 border-l-4 bg-red-50 p-4 font-semibold text-red-900" style={{borderColor:brand.primary_color}}>{params.error}</div>}{params.invited&&params.email==="sent"&&<div className="mt-6 border-l-4 border-green-600 bg-green-50 p-4 font-semibold text-green-900">Invitation email sent successfully.</div>}{params.invited&&params.email==="waiting"&&<div className="mt-6 border-l-4 border-amber-500 bg-amber-50 p-4 font-semibold text-amber-900">Invitation created. Email delivery is waiting for the Resend connection; the invitation link remains available below.</div>}{params.invited&&params.email==="failed"&&<div className="mt-6 border-l-4 border-red-700 bg-red-50 p-4 font-semibold text-red-900">Invitation created, but the email could not be delivered. Copy the link below or try sending it again.</div>}{params.updated&&<div className="mt-6 border-l-4 border-green-600 bg-green-50 p-4 font-semibold text-green-900">User access updated.</div>}
  <details className="mt-8 overflow-hidden rounded-lg border border-black/10 bg-white shadow-sm"><summary className="flex min-h-14 cursor-pointer list-none items-center justify-between px-5 font-extrabold uppercase marker:content-none [&::-webkit-details-marker]:hidden">Understand academy roles <span className="text-xs text-black/40">View guide +</span></summary><div className="grid border-t border-black/10 md:grid-cols-3">{Object.entries(roleDescription).map(([name,description])=><div key={name} className="border-b border-black/10 p-5 last:border-0 md:border-b-0 md:border-r md:last:border-r-0"><b className="text-sm uppercase">{name.replaceAll("_"," ")}</b><p className="mt-2 text-sm leading-6 text-black/50">{description}</p></div>)}</div></details>
  <form action={createUserInvitation} className="mt-8 grid gap-5 border border-black/10 bg-white p-6 shadow-sm md:grid-cols-2 lg:grid-cols-4"><label className="grid grid-rows-[auto_2rem_3rem] gap-2 font-bold"><span>Email address</span><span className="text-xs font-normal leading-4 text-black/45">User&apos;s account email</span><input name="email" type="email" required placeholder="name@retailer.com" className="h-12 border border-black/20 px-4 font-normal"/></label><label className="grid grid-rows-[auto_2rem_3rem] gap-2 font-bold"><span>Invite as</span><span className="text-xs font-normal leading-4 text-black/45">Choose the type of access</span><select name="kind" className="h-12 border border-black/20 bg-white px-4 font-normal"><option value="retailer_learner">Retailer learner</option><option value="retailer_manager">Retailer manager</option><option value="manufacturer_member">Manufacturer team</option></select></label><label className="grid grid-rows-[auto_2rem_3rem] gap-2 font-bold"><span>Retailer</span><span className="text-xs font-normal leading-4 text-black/45">Required for retailer users</span><select name="companyId" className="h-12 border border-black/20 bg-white px-4 font-normal"><option value="">Select retailer</option>{dashboard.retailers.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className="grid grid-rows-[auto_2rem_3rem] gap-2 font-bold"><span>Team role</span><span className="text-xs font-normal leading-4 text-black/45">Used for manufacturer team</span><select name="role" className="h-12 border border-black/20 bg-white px-4 font-normal"><option value="admin">Admin</option><option value="content_manager">Content manager</option><option value="viewer">Viewer</option></select></label><button className="min-h-12 font-extrabold uppercase text-white md:col-span-2 lg:col-span-4" style={{backgroundColor:brand.primary_color}}>Create invitation</button></form>
  <form method="get" className="mt-10 grid gap-4 rounded-lg border border-black/10 bg-white p-5 shadow-sm md:grid-cols-[minmax(260px,1fr)_220px_200px_auto] md:items-end"><label className="grid gap-2 text-sm font-bold">Search directory<input name="q" defaultValue={params.q??""} placeholder="Email, retailer, or organization" className="h-12 rounded-md border border-black/20 px-4 font-normal"/></label><label className="grid gap-2 text-sm font-bold">Directory<select name="directory" defaultValue={directory} className="h-12 rounded-md border border-black/20 bg-white px-4 font-normal"><option value="all">Everyone</option><option value="manufacturer">Manufacturer team</option><option value="retailer">Retailer users</option><option value="invitations">Invitations</option></select></label><label className="grid gap-2 text-sm font-bold">Role<select name="role" defaultValue={role} className="h-12 rounded-md border border-black/20 bg-white px-4 font-normal"><option value="all">All roles</option>{Object.keys(roleDescription).map(item=><option key={item} value={item}>{item.replaceAll("_"," ")}</option>)}</select></label><div className="flex gap-2"><button className="academy-filter-button min-h-12 flex-1 px-5 text-xs font-extrabold uppercase">Apply</button><a href="/app/users" className="grid min-h-12 place-items-center rounded-md border border-black/20 px-4 text-xs font-extrabold uppercase">Clear</a></div></form>
  <section className="mt-10"><div><h2 className="text-2xl font-extrabold uppercase">Open invitations</h2><p className="mt-2 text-sm text-black/50">Track delivery, resend an email, renew an expired link, or revoke access before it is accepted.</p></div><div className="mt-4 overflow-x-auto rounded-lg border border-black/10 bg-white shadow-sm"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-black/[.03] text-xs uppercase text-black/45"><tr><th className="p-4">Email</th><th className="p-4">Access</th><th className="p-4">Organization</th><th className="p-4">Delivery</th><th className="p-4">Expires</th><th className="p-4">Actions</th></tr></thead><tbody>{openInvitations.map(i=>{const expired=new Date(i.expires_at)<=new Date();return <tr key={i.id} className="border-t border-black/10"><td className="p-4 font-semibold">{i.email}</td><td className="p-4"><span className="capitalize">{i.role.replaceAll("_"," ")}</span><p className="mt-1 max-w-48 text-xs leading-5 text-black/40">{roleDescription[i.role]}</p></td><td className="p-4">{i.company_name||brand.name}</td><td className="p-4"><span className={`inline-flex px-2 py-1 text-[10px] font-extrabold uppercase ${i.email_status==="sent"?"bg-green-50 text-green-800":i.email_status==="failed"?"bg-red-50 text-red-800":"bg-amber-50 text-amber-800"}`}>{i.email_status==="sent"?"Sent":i.email_status==="failed"?"Failed":"Not sent"}</span><p className="mt-1 text-xs text-black/40">{i.email_attempts??0} attempt{(i.email_attempts??0)===1?"":"s"}{i.last_email_at?` · ${new Date(i.last_email_at).toLocaleDateString()}`:""}</p>{i.email_error&&<p className="mt-1 max-w-56 truncate text-xs text-red-700" title={i.email_error}>{i.email_error}</p>}</td><td className={`p-4 ${expired?"font-bold text-red-700":""}`}>{expired?"Expired ":""}{new Date(i.expires_at).toLocaleDateString()}</td><td className="p-4"><InvitationControls invitationId={i.id} email={i.email} expired={expired}/></td></tr>})}{!openInvitations.length&&<tr><td colSpan={6} className="p-10 text-center"><b className="block uppercase">No matching open invitations</b><span className="mt-2 block text-black/45">New invitations and pending email deliveries will appear here.</span></td></tr>}</tbody></table></div></section>
  <details className="mt-8 overflow-hidden rounded-lg border border-black/10 bg-white shadow-sm"><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between px-5 marker:content-none [&::-webkit-details-marker]:hidden"><span><b className="block uppercase">Invitation history</b><span className="mt-1 block text-sm text-black/45">Accepted and revoked invitations remain available for reference.</span></span><span className="rounded-full bg-black/[.05] px-3 py-1 text-xs font-extrabold">{invitationHistory.length}</span></summary><div className="overflow-x-auto border-t border-black/10"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-black/[.03] text-xs uppercase text-black/45"><tr><th className="p-4">Email</th><th className="p-4">Access</th><th className="p-4">Organization</th><th className="p-4">Final status</th><th className="p-4">Last delivery</th></tr></thead><tbody>{invitationHistory.map(i=><tr key={i.id} className="border-t border-black/10"><td className="p-4 font-semibold">{i.email}</td><td className="p-4 capitalize">{i.role.replaceAll("_"," ")}</td><td className="p-4">{i.company_name||brand.name}</td><td className="p-4"><span className="inline-flex bg-black/[.05] px-2 py-1 text-[10px] font-extrabold uppercase">{i.status}</span></td><td className="p-4 text-black/50">{i.last_email_at?new Date(i.last_email_at).toLocaleString():"No email recorded"}</td></tr>)}{!invitationHistory.length&&<tr><td colSpan={5} className="p-8 text-center text-black/45">No matching invitation history.</td></tr>}</tbody></table></div></details>
  <section className="mt-10"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[.18em]" style={{color:brand.primary_color}}>Brand access</p><h2 className="mt-2 text-2xl font-extrabold uppercase">Manufacturer team</h2></div><p className="max-w-lg text-sm text-black/50">Removing access affects only {brand.name}. The user keeps their JobberTrain account, history, and other academy access.</p></div><div className="mt-5 max-h-[36rem] overflow-y-auto rounded-lg border border-black/10 bg-white shadow-sm"><div className="sticky top-0 z-10 hidden grid-cols-[minmax(0,1.5fr)_minmax(230px,.8fr)_minmax(110px,.4fr)_auto] gap-5 border-b border-black/10 bg-[#f7f7f5] px-5 py-4 text-xs font-extrabold uppercase tracking-wide text-black/45 md:grid"><span>User</span><span>Role & permissions</span><span>Status</span><span className="justify-self-end">Actions</span></div>{manufacturerMembers.map(p=><div key={p.user_id} className="grid min-h-20 gap-4 border-b border-black/10 bg-white px-5 py-5 last:border-0 md:grid-cols-[minmax(0,1.5fr)_minmax(230px,.8fr)_minmax(110px,.4fr)_auto] md:items-center md:gap-5"><div className="min-w-0"><b className="block truncate">{p.email}</b>{p.user_id===auth.user.id&&<span className="mt-1 inline-block text-[10px] font-extrabold uppercase text-black/35">You</span>}</div><div><span className="mr-2 text-[10px] font-extrabold uppercase text-black/35 md:hidden">Role</span><span className="text-sm font-semibold capitalize">{p.role.replaceAll("_"," ")}</span><p className="mt-1 text-xs leading-5 text-black/40">{roleDescription[p.role]}</p></div><div><span className="mr-2 text-[10px] font-extrabold uppercase text-black/35 md:hidden">Status</span><span className="inline-flex bg-green-50 px-2 py-1 text-[10px] font-extrabold uppercase text-green-800">{p.status}</span></div><MemberControls userId={p.user_id} email={p.email} scope="manufacturer" role={p.role} currentUserId={auth.user.id}/></div>)}{!manufacturerMembers.length&&<p className="bg-white p-10 text-center text-black/45">No manufacturer team members match the current filters.</p>}</div></section>
  <section className="mt-10"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[.18em]" style={{color:brand.primary_color}}>Retail network</p><h2 className="mt-2 text-2xl font-extrabold uppercase">Retailer users</h2></div><p className="max-w-lg text-sm text-black/50">Each row controls access only within that connected retailer.</p></div><div className="mt-5 max-h-[36rem] overflow-y-auto rounded-lg border border-black/10 bg-white shadow-sm"><div className="sticky top-0 z-10 hidden grid-cols-[minmax(0,1.2fr)_minmax(170px,.7fr)_minmax(230px,.8fr)_auto] gap-5 border-b border-black/10 bg-[#f7f7f5] px-5 py-4 text-xs font-extrabold uppercase tracking-wide text-black/45 md:grid"><span>User</span><span>Retailer</span><span>Role & permissions</span><span className="justify-self-end">Actions</span></div>{retailerMembers.map(p=><div key={`${p.user_id}-${p.company_id}`} className="grid min-h-20 gap-4 border-b border-black/10 bg-white px-5 py-5 last:border-0 md:grid-cols-[minmax(0,1.2fr)_minmax(170px,.7fr)_minmax(230px,.8fr)_auto] md:items-center md:gap-5"><div className="min-w-0"><b className="block truncate">{p.email}</b>{p.user_id===auth.user.id&&<span className="mt-1 inline-block text-[10px] font-extrabold uppercase text-black/35">You</span>}</div><div><span className="mr-2 text-[10px] font-extrabold uppercase text-black/35 md:hidden">Retailer</span><span className="text-sm">{p.company_name}</span></div><div><span className="mr-2 text-[10px] font-extrabold uppercase text-black/35 md:hidden">Role</span><span className="text-sm font-semibold capitalize">{p.role.replaceAll("_"," ")}</span><p className="mt-1 text-xs leading-5 text-black/40">{roleDescription[p.role]}</p></div><MemberControls userId={p.user_id} email={p.email} scope="retailer" companyId={p.company_id} role={p.role} currentUserId={auth.user.id}/></div>)}{!retailerMembers.length&&<p className="bg-white p-10 text-center text-black/45">No retailer users match the current filters.</p>}</div></section>
 </main></div>;
}
