import { redirect } from "next/navigation";
import { ManufacturerHeader } from "@/components/manufacturer-shell";
import { getActiveBrand } from "@/lib/branding";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { createUserInvitation, manageInvitation } from "./actions";
import CopyLink from "./copy-link";
import MemberControls from "./member-controls";

type Person={user_id:string;email:string;role:string;status:string;company_id?:string;company_name?:string};
type Invite={id:string;email:string;invitation_type:string;role:string;status:string;company_name:string|null;expires_at:string};
type Dashboard={manufacturer_members:Person[];retailer_members:Person[];retailers:{id:string;name:string}[];invitations:Invite[]};

export default async function UsersPage({searchParams}:{searchParams:Promise<{error?:string;invited?:string;updated?:string}>}){
 const params=await searchParams;const supabase=await createSupabaseServerClient();const [{data:auth},brand]=await Promise.all([supabase.auth.getUser(),getActiveBrand()]);
 if(!auth.user)redirect("/login");if(!brand?.can_manage_brand)redirect("/app");
 const {data}=await supabase.rpc("manufacturer_people_dashboard");const dashboard=(data??{manufacturer_members:[],retailer_members:[],retailers:[],invitations:[]}) as Dashboard;
 return <div className="min-h-screen bg-[#f4f4f2] text-black"><ManufacturerHeader brand={brand} email={auth.user.email}/><main className="mx-auto max-w-7xl px-5 py-10 lg:px-8 lg:py-14">
  <p className="text-sm font-extrabold uppercase italic tracking-[0.2em]" style={{color:brand.primary_color}}>Access management</p><h1 className="mt-2 text-4xl font-extrabold uppercase tracking-tight sm:text-5xl">Users & invitations</h1><p className="mt-3 max-w-2xl text-black/60">Invite users, update their roles, or remove access to this brand without deleting their account or training history.</p>
  {params.error&&<div className="mt-6 border-l-4 bg-red-50 p-4 font-semibold text-red-900" style={{borderColor:brand.primary_color}}>{params.error}</div>}{params.invited&&<div className="mt-6 border-l-4 border-green-600 bg-green-50 p-4 font-semibold text-green-900">Invitation created. Copy its link below and send it to the user.</div>}{params.updated&&<div className="mt-6 border-l-4 border-green-600 bg-green-50 p-4 font-semibold text-green-900">User access updated.</div>}
  <form action={createUserInvitation} className="mt-8 grid gap-5 border border-black/10 bg-white p-6 shadow-sm md:grid-cols-2 lg:grid-cols-4"><label className="grid grid-rows-[auto_2rem_3rem] gap-2 font-bold"><span>Email address</span><span className="text-xs font-normal leading-4 text-black/45">User&apos;s account email</span><input name="email" type="email" required placeholder="name@retailer.com" className="h-12 border border-black/20 px-4 font-normal"/></label><label className="grid grid-rows-[auto_2rem_3rem] gap-2 font-bold"><span>Invite as</span><span className="text-xs font-normal leading-4 text-black/45">Choose the type of access</span><select name="kind" className="h-12 border border-black/20 bg-white px-4 font-normal"><option value="retailer_learner">Retailer learner</option><option value="retailer_manager">Retailer manager</option><option value="manufacturer_member">Manufacturer team</option></select></label><label className="grid grid-rows-[auto_2rem_3rem] gap-2 font-bold"><span>Retailer</span><span className="text-xs font-normal leading-4 text-black/45">Required for retailer users</span><select name="companyId" className="h-12 border border-black/20 bg-white px-4 font-normal"><option value="">Select retailer</option>{dashboard.retailers.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className="grid grid-rows-[auto_2rem_3rem] gap-2 font-bold"><span>Team role</span><span className="text-xs font-normal leading-4 text-black/45">Used for manufacturer team</span><select name="role" className="h-12 border border-black/20 bg-white px-4 font-normal"><option value="admin">Admin</option><option value="content_manager">Content manager</option><option value="viewer">Viewer</option></select></label><button className="min-h-12 font-extrabold uppercase text-white md:col-span-2 lg:col-span-4" style={{backgroundColor:brand.primary_color}}>Create invitation</button></form>
  <section className="mt-10"><h2 className="text-2xl font-extrabold uppercase">Pending invitations</h2><div className="mt-4 overflow-x-auto border border-black/10 bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-black/[.03] text-xs uppercase text-black/45"><tr><th className="p-4">Email</th><th className="p-4">Access</th><th className="p-4">Organization</th><th className="p-4">Expires</th><th className="p-4">Actions</th></tr></thead><tbody>{dashboard.invitations.filter(i=>i.status==="pending").map(i=><tr key={i.id} className="border-t border-black/10"><td className="p-4 font-semibold">{i.email}</td><td className="p-4 capitalize">{i.role.replaceAll("_"," ")}</td><td className="p-4">{i.company_name||brand.name}</td><td className="p-4">{new Date(i.expires_at).toLocaleDateString()}</td><td className="p-4"><div className="flex gap-4"><CopyLink token={i.id}/><form action={manageInvitation}><input type="hidden" name="invitationId" value={i.id}/><button name="action" value="renew" className="font-bold hover:underline">Renew</button></form><form action={manageInvitation}><input type="hidden" name="invitationId" value={i.id}/><button name="action" value="cancel" className="font-bold text-red-700 hover:underline">Revoke</button></form></div></td></tr>)}{!dashboard.invitations.some(i=>i.status==="pending")&&<tr><td colSpan={5} className="p-8 text-center text-black/45">No pending invitations.</td></tr>}</tbody></table></div></section>
  <section className="mt-10"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[.18em]" style={{color:brand.primary_color}}>Brand access</p><h2 className="mt-2 text-2xl font-extrabold uppercase">Manufacturer team</h2></div><p className="max-w-lg text-sm text-black/50">Removing access affects only {brand.name}. The user keeps their JobberTrain account, history, and other academy access.</p></div><div className="mt-5 border border-black/10 bg-white shadow-sm"><div className="hidden grid-cols-[minmax(0,1.5fr)_minmax(150px,.65fr)_minmax(110px,.45fr)_auto] gap-5 border-b border-black/10 bg-black/[.03] px-5 py-4 text-xs font-extrabold uppercase tracking-wide text-black/45 md:grid"><span>User</span><span>Role</span><span>Status</span><span className="justify-self-end">Actions</span></div>{dashboard.manufacturer_members.map(p=><div key={p.user_id} className="grid min-h-20 gap-4 border-b border-black/10 px-5 py-5 last:border-0 md:grid-cols-[minmax(0,1.5fr)_minmax(150px,.65fr)_minmax(110px,.45fr)_auto] md:items-center md:gap-5"><div className="min-w-0"><b className="block truncate">{p.email}</b>{p.user_id===auth.user.id&&<span className="mt-1 inline-block text-[10px] font-extrabold uppercase text-black/35">You</span>}</div><div><span className="mr-2 text-[10px] font-extrabold uppercase text-black/35 md:hidden">Role</span><span className="text-sm font-semibold capitalize">{p.role.replaceAll("_"," ")}</span></div><div><span className="mr-2 text-[10px] font-extrabold uppercase text-black/35 md:hidden">Status</span><span className="inline-flex bg-green-50 px-2 py-1 text-[10px] font-extrabold uppercase text-green-800">{p.status}</span></div><MemberControls userId={p.user_id} email={p.email} scope="manufacturer" role={p.role} currentUserId={auth.user.id}/></div>)}{!dashboard.manufacturer_members.length&&<p className="p-8 text-center text-black/45">No manufacturer team members.</p>}</div></section>
  <section className="mt-10"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[.18em]" style={{color:brand.primary_color}}>Retail network</p><h2 className="mt-2 text-2xl font-extrabold uppercase">Retailer users</h2></div><p className="max-w-lg text-sm text-black/50">Each row controls access only within that connected retailer.</p></div><div className="mt-5 border border-black/10 bg-white shadow-sm"><div className="hidden grid-cols-[minmax(0,1.25fr)_minmax(170px,.8fr)_minmax(130px,.55fr)_auto] gap-5 border-b border-black/10 bg-black/[.03] px-5 py-4 text-xs font-extrabold uppercase tracking-wide text-black/45 md:grid"><span>User</span><span>Retailer</span><span>Role</span><span className="justify-self-end">Actions</span></div>{dashboard.retailer_members.map(p=><div key={`${p.user_id}-${p.company_id}`} className="grid min-h-20 gap-4 border-b border-black/10 px-5 py-5 last:border-0 md:grid-cols-[minmax(0,1.25fr)_minmax(170px,.8fr)_minmax(130px,.55fr)_auto] md:items-center md:gap-5"><div className="min-w-0"><b className="block truncate">{p.email}</b>{p.user_id===auth.user.id&&<span className="mt-1 inline-block text-[10px] font-extrabold uppercase text-black/35">You</span>}</div><div><span className="mr-2 text-[10px] font-extrabold uppercase text-black/35 md:hidden">Retailer</span><span className="text-sm">{p.company_name}</span></div><div><span className="mr-2 text-[10px] font-extrabold uppercase text-black/35 md:hidden">Role</span><span className="text-sm font-semibold capitalize">{p.role.replaceAll("_"," ")}</span></div><MemberControls userId={p.user_id} email={p.email} scope="retailer" companyId={p.company_id} role={p.role} currentUserId={auth.user.id}/></div>)}{!dashboard.retailer_members.length&&<p className="p-8 text-center text-black/45">No retailer users.</p>}</div></section>
 </main></div>;
}
