import { redirect } from "next/navigation";
import { ManufacturerHeader } from "@/components/manufacturer-shell";
import { getActiveBrand } from "@/lib/branding";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { createUserInvitation, manageInvitation } from "./actions";
import CopyLink from "./copy-link";

type Person = { user_id: string; email: string; role: string; status: string; company_name?: string };
type Invite = { id: string; email: string; invitation_type: string; role: string; status: string; company_name: string | null; expires_at: string };
type Dashboard = { manufacturer_members: Person[]; retailer_members: Person[]; retailers: { id: string; name: string }[]; invitations: Invite[] };
export default async function UsersPage({ searchParams }: { searchParams: Promise<{ error?: string; invited?: string }> }) {
  const params=await searchParams; const supabase=await createSupabaseServerClient(); const [{data:auth},brand]=await Promise.all([supabase.auth.getUser(),getActiveBrand()]);
  if(!auth.user) redirect("/login"); if(!brand?.can_manage_brand) redirect("/app");
  const {data}=await supabase.rpc("manufacturer_people_dashboard"); const dashboard=(data ?? {manufacturer_members:[],retailer_members:[],retailers:[],invitations:[]}) as Dashboard;
  return <div className="min-h-screen bg-[#f4f4f2] text-black"><ManufacturerHeader brand={brand} email={auth.user.email}/><main className="mx-auto max-w-7xl px-5 py-10 lg:px-8 lg:py-14"><p className="text-sm font-extrabold uppercase italic tracking-[0.2em]" style={{color:brand.primary_color}}>Access management</p><h1 className="mt-2 text-4xl font-extrabold uppercase tracking-tight sm:text-5xl">Users & invitations</h1><p className="mt-3 max-w-2xl text-black/60">Invite your team or retailer learners with a secure seven-day onboarding link.</p>
    {params.error&&<div className="mt-6 border-l-4 bg-red-50 p-4 font-semibold text-red-900" style={{borderColor:brand.primary_color}}>{params.error}</div>}{params.invited&&<div className="mt-6 border-l-4 border-green-600 bg-green-50 p-4 font-semibold text-green-900">Invitation created. Copy its link below and send it to the user.</div>}
    <form action={createUserInvitation} className="mt-8 grid gap-5 border border-black/10 bg-white p-6 shadow-sm md:grid-cols-2 lg:grid-cols-4"><label className="grid gap-2 font-bold">Email address<input name="email" type="email" required placeholder="name@retailer.com" className="min-h-12 border border-black/20 px-4 font-normal"/></label><label className="grid gap-2 font-bold">Invite as<select name="kind" className="min-h-12 border border-black/20 bg-white px-4 font-normal"><option value="retailer_learner">Retailer learner</option><option value="retailer_manager">Retailer manager</option><option value="manufacturer_member">Manufacturer team</option></select></label><label className="grid gap-2 font-bold">Retailer <span className="text-xs font-normal text-black/45">For retailer users</span><select name="companyId" className="min-h-12 border border-black/20 bg-white px-4 font-normal"><option value="">Select retailer</option>{dashboard.retailers.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className="grid gap-2 font-bold">Team role <span className="text-xs font-normal text-black/45">For manufacturer team</span><select name="role" className="min-h-12 border border-black/20 bg-white px-4 font-normal"><option value="admin">Admin</option><option value="content_manager">Content manager</option><option value="viewer">Viewer</option></select></label><button className="min-h-12 font-extrabold uppercase text-white md:col-span-2 lg:col-span-4" style={{backgroundColor:brand.primary_color}}>Create invitation</button></form>
    <section className="mt-10"><h2 className="text-2xl font-extrabold uppercase">Pending invitations</h2><div className="mt-4 overflow-x-auto border border-black/10 bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-black/[.03] text-xs uppercase text-black/45"><tr><th className="p-4">Email</th><th className="p-4">Access</th><th className="p-4">Organization</th><th className="p-4">Expires</th><th className="p-4">Actions</th></tr></thead><tbody>{dashboard.invitations.filter(i=>i.status==="pending").map(i=><tr key={i.id} className="border-t border-black/10"><td className="p-4 font-semibold">{i.email}</td><td className="p-4 capitalize">{i.role.replaceAll("_"," ")}</td><td className="p-4">{i.company_name||brand.name}</td><td className="p-4">{new Date(i.expires_at).toLocaleDateString()}</td><td className="p-4"><div className="flex gap-4"><CopyLink token={i.id}/><form action={manageInvitation}><input type="hidden" name="invitationId" value={i.id}/><button name="action" value="renew" className="font-bold hover:underline">Renew</button></form><form action={manageInvitation}><input type="hidden" name="invitationId" value={i.id}/><button name="action" value="cancel" className="font-bold text-red-700 hover:underline">Cancel</button></form></div></td></tr>)}{!dashboard.invitations.some(i=>i.status==="pending")&&<tr><td colSpan={5} className="p-8 text-center text-black/45">No pending invitations.</td></tr>}</tbody></table></div></section>
    <section className="mt-10 grid gap-7 xl:grid-cols-2"><div><h2 className="text-2xl font-extrabold uppercase">Manufacturer team</h2><div className="mt-4 border border-black/10 bg-white">{dashboard.manufacturer_members.map(p=><div key={p.user_id} className="flex justify-between gap-4 border-b border-black/10 p-4 last:border-0"><div><b>{p.email}</b><p className="text-xs capitalize text-black/45">{p.role.replaceAll("_"," ")}</p></div><span className="text-xs font-bold uppercase text-green-700">{p.status}</span></div>)}</div></div><div><h2 className="text-2xl font-extrabold uppercase">Retailer users</h2><div className="mt-4 border border-black/10 bg-white">{dashboard.retailer_members.map(p=><div key={`${p.user_id}-${p.company_name}`} className="flex justify-between gap-4 border-b border-black/10 p-4 last:border-0"><div><b>{p.email}</b><p className="text-xs capitalize text-black/45">{p.company_name} · {p.role}</p></div><span className="text-xs font-bold uppercase text-green-700">{p.status}</span></div>)}</div></div></section>
  </main></div>;
}
