import type { SupabaseClient } from "@supabase/supabase-js";

type Payload={manufacturer_name:string;manufacturer_slug:string;logo_url:string|null;primary_color:string;content_type:"quiz"|"course";content_title:string;recipients:string[]};
const escape=(value:string)=>value.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]!);
const site=()=>`${(process.env.NEXT_PUBLIC_SITE_URL?.trim()||"http://localhost:3000").replace(/\/$/,"")}`;

export async function sendAssignmentEmails(supabase:SupabaseClient,args:{contentType:string;contentId:string;companyIds:string[];manufacturerTeam:boolean;required:boolean;dueAt:string|null}){
  const {data:enabled}=await supabase.rpc("assignment_notifications_enabled");
  if(!enabled)return{sent:0,failed:0,configured:true,disabled:true};
  if(!process.env.RESEND_API_KEY?.trim())return{sent:0,failed:0,configured:false};
  const {data,error}=await supabase.rpc("assignment_email_recipients",{target_content_type:args.contentType,target_content_id:args.contentId,target_company_ids:args.companyIds,include_manufacturer_team:args.manufacturerTeam});
  if(error||!data)return{sent:0,failed:0,configured:true};
  const p=data as Payload;const url=`${site()}/m/${p.manufacturer_slug}/app/my-training`;const accent=/^#[0-9a-f]{6}$/i.test(p.primary_color)?p.primary_color:"#ff4f1f";
  const due=args.dueAt?new Intl.DateTimeFormat("en-US",{dateStyle:"long"}).format(new Date(args.dueAt)):null;
  const html=`<!doctype html><html><body style="margin:0;background:#f3f3f1;font-family:Arial,sans-serif;color:#171717"><table role="presentation" width="100%"><tr><td style="padding:32px 16px"><table role="presentation" width="100%" style="max-width:620px;margin:auto;background:#fff;border:1px solid #ddd"><tr><td style="height:8px;background:${accent}"></td></tr><tr><td style="padding:42px">${p.logo_url?`<img src="${escape(p.logo_url)}" alt="${escape(p.manufacturer_name)}" style="display:block;max-width:190px;max-height:58px;margin-bottom:28px">`:""}<div style="font-size:12px;font-weight:800;letter-spacing:2px;text-transform:uppercase;color:${accent}">New ${escape(p.content_type)} assignment</div><h1 style="font-size:30px;line-height:1.15;margin:14px 0;text-transform:uppercase">${escape(p.content_title)}</h1><p style="font-size:16px;line-height:1.6;color:#555">${escape(p.manufacturer_name)} assigned new product training to you.${args.required?" This training is required.":""}${due?` Please complete it by ${escape(due)}.`:""}</p><a href="${escape(url)}" style="display:inline-block;margin-top:16px;background:${accent};color:#fff;text-decoration:none;font-size:14px;font-weight:800;text-transform:uppercase;padding:16px 24px">Open My Training</a></td></tr><tr><td style="padding:22px 42px;background:#171717;color:#aaa;font-size:12px">${escape(p.manufacturer_name)} Academy &nbsp;·&nbsp; Powered by JobberTrain</td></tr></table></td></tr></table></body></html>`;
  const results=await Promise.allSettled(p.recipients.map(email=>fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY!.trim()}`,"Content-Type":"application/json"},body:JSON.stringify({from:process.env.RESEND_FROM_EMAIL?.trim()||"JobberTrain <invites@auth.jobbertrain.com>",to:[email],reply_to:process.env.RESEND_REPLY_TO?.trim()||undefined,subject:`New ${p.manufacturer_name} training: ${p.content_title}`,html}),cache:"no-store"}).then(r=>{if(!r.ok)throw new Error("Email delivery failed");})));
  return{sent:results.filter(r=>r.status==="fulfilled").length,failed:results.filter(r=>r.status==="rejected").length,configured:true};
}
