import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { createInvitedAccount } from "./actions";

type Invite={email:string;status:string;role:string;manufacturer_name:string;manufacturer_slug:string;company_name:string|null;logo_url:string|null;primary_color:string;secondary_color:string};
export default async function InvitePage({params,searchParams}:{params:Promise<{token:string}>;searchParams:Promise<{error?:string;checkEmail?:string}>}){
 const {token}=await params;const query=await searchParams;const supabase=await createSupabaseServerClient();const {data}=await supabase.rpc("get_invitation_details",{invitation_token:token});if(!data)notFound();const invite=data as Invite;const available=invite.status==="pending";
 return <main className="grid min-h-screen lg:grid-cols-2"><section className="hidden p-12 text-white lg:flex lg:flex-col lg:justify-between" style={{backgroundColor:invite.secondary_color}}>{invite.logo_url?<Image src={invite.logo_url} alt={`${invite.manufacturer_name} logo`} width={200} height={50} className="max-h-12 w-auto object-contain brightness-0 invert" unoptimized/>:<b className="text-2xl uppercase">{invite.manufacturer_name}</b>}<div><p className="text-sm font-extrabold uppercase tracking-[.2em]" style={{color:invite.primary_color}}>You&apos;re invited</p><h1 className="mt-4 text-5xl font-extrabold uppercase leading-none">Learn the product.<br/>Sell with confidence.</h1><p className="mt-5 text-white/60">Join {invite.company_name||invite.manufacturer_name} in the {invite.manufacturer_name} training center.</p></div><p className="text-sm text-white/40">Private training portal</p></section><section className="flex items-center justify-center px-5 py-12"><div className="w-full max-w-md"><p className="text-sm font-extrabold uppercase italic tracking-[.2em]" style={{color:invite.primary_color}}>Account setup</p><h2 className="mt-2 text-4xl font-extrabold uppercase">Accept invitation</h2><p className="mt-3 text-black/60">Create your password for <b>{invite.email}</b>.</p>{query.error&&<div className="mt-6 border-l-4 bg-red-50 p-4 text-red-900" style={{borderColor:invite.primary_color}}>{query.error}</div>}{query.checkEmail&&<div className="mt-6 border-l-4 border-green-600 bg-green-50 p-4 text-green-900"><b>Check your email.</b><br/>Confirm your account, then you’ll be connected automatically.</div>}{!available&&<div className="mt-6 bg-amber-50 p-4 text-amber-900">This invitation is {invite.status}. Ask your administrator for a new link.</div>}{available&&!query.checkEmail&&<form action={createInvitedAccount} className="mt-8 grid gap-5"><input type="hidden" name="token" value={token}/><label className="grid gap-2 font-bold">Create password<input name="password" type="password" minLength={8} required autoComplete="new-password" className="min-h-13 border border-black/20 px-4 font-normal"/></label><button className="min-h-13 font-extrabold uppercase text-white" style={{backgroundColor:invite.primary_color}}>Create account</button></form>}<Link href={`/login?next=${encodeURIComponent(`/invite/${token}/accept`)}&brand=${invite.manufacturer_slug}`} className="mt-7 inline-block text-sm font-bold hover:underline">Already have an account? Sign in →</Link></div></section></main>;
}
