import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {ManufacturerHeader} from "@/components/manufacturer-shell";
import {getActiveBrand} from "@/lib/branding";
import {createSupabaseServerClient} from "@/lib/supabase/server";
import {useContentTemplate} from "../actions";

type Detail={template_id:string;content_type:"product"|"quiz"|"course";template_name:string;template_description:string|null;is_platform_template:boolean;snapshot:Record<string,unknown>;updated_at:string};
const array=(value:unknown)=>Array.isArray(value)?value:[];
const text=(value:unknown)=>typeof value==="string"?value:"";

export default async function TemplatePreviewPage({params}:{params:Promise<{templateId:string}>}){
 const[{templateId},brand,s]=await Promise.all([params,getActiveBrand(),createSupabaseServerClient()]);const{data:auth}=await s.auth.getUser();if(!auth.user)redirect("/login");if(!brand?.can_manage_training)redirect("/app");const{data,error}=await s.rpc("content_template_detail",{target_template_id:templateId});if(error||!data)notFound();const item=data as Detail,snapshot=item.snapshot;
 const title=text(snapshot.name)||text(snapshot.title)||item.template_name;
 return <div className="min-h-screen bg-[#f4f4f2]"><ManufacturerHeader brand={brand} email={auth.user.email}/><main className="mx-auto max-w-5xl px-5 py-10 lg:px-8 lg:py-14"><Link href={`/m/${brand.slug}/app/templates`} className="text-sm font-extrabold uppercase text-black/50 hover:text-black">← Template library</Link><div className="mt-8 flex flex-col justify-between gap-6 border-b border-black/10 pb-8 sm:flex-row sm:items-end"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-black px-3 py-1 text-[10px] font-extrabold uppercase text-white">{item.content_type}</span>{item.is_platform_template&&<span className="rounded-full bg-blue-50 px-3 py-1 text-[10px] font-extrabold uppercase text-blue-800">JobberTrain starter</span>}</div><h1 className="mt-4 text-4xl font-extrabold uppercase tracking-tight sm:text-5xl">{item.template_name}</h1><p className="mt-3 max-w-2xl text-black/55">{item.template_description??`A reusable ${item.content_type} structure.`}</p></div><form action={useContentTemplate}><input type="hidden" name="templateId" value={item.template_id}/><input type="hidden" name="contentType" value={item.content_type}/><button className="min-h-12 rounded-md px-6 text-sm font-extrabold uppercase text-white" style={{backgroundColor:brand.primary_color}}>Use this template</button></form></div>
 <section className="mt-8 overflow-hidden rounded-lg border border-black/10 bg-white shadow-sm"><div className="border-b border-black/10 bg-black/[.025] p-6"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-black/35">Template preview</p><h2 className="mt-2 text-2xl font-extrabold uppercase">{title}</h2><p className="mt-2 max-w-3xl text-black/55">{text(snapshot.tagline)||text(snapshot.description)||"No description provided."}</p></div>
 {item.content_type==="product"&&<div className="grid gap-6 p-6 md:grid-cols-2"><PreviewList title="Features" items={array(snapshot.features).map(x=>typeof x==="string"?x:JSON.stringify(x))}/><PreviewList title="Specifications" items={array(snapshot.specs).map(x=>typeof x==="string"?x:JSON.stringify(x))}/><Stat label="Images" value={array(snapshot.images).length}/><Stat label="Variations" value={array(snapshot.variations).length}/></div>}
 {item.content_type==="quiz"&&<div className="p-6"><div className="mb-5 grid gap-3 sm:grid-cols-2"><Stat label="Questions" value={array(snapshot.questions).length}/><Stat label="Passing score" value={`${Number(snapshot.passing_score??80)}%`}/></div><div className="divide-y divide-black/10 rounded-md border border-black/10">{array(snapshot.questions).map((raw,index)=>{const q=raw as Record<string,unknown>;return <div key={index} className="p-4"><b>{index+1}. {text(q.prompt)}</b><p className="mt-2 text-sm text-black/45">{array(q.choices).length} answer choices</p></div>})}</div></div>}
 {item.content_type==="course"&&<div className="p-6"><div className="divide-y divide-black/10 rounded-md border border-black/10">{array(snapshot.modules).map((raw,index)=>{const courseModule=raw as Record<string,unknown>;return <div key={index} className="p-5"><div className="flex items-center justify-between gap-4"><b className="uppercase">{index+1}. {text(courseModule.title)||`Module ${index+1}`}</b><span className="text-xs font-semibold text-black/40">{array(courseModule.blocks).length} blocks</span></div><div className="mt-3 flex flex-wrap gap-2">{array(courseModule.blocks).map((blockRaw,blockIndex)=>{const block=blockRaw as Record<string,unknown>;return <span key={blockIndex} className="rounded-full bg-black/5 px-3 py-1 text-[10px] font-extrabold uppercase">{text(block.block_type)||"content"}</span>})}</div></div>})}</div></div>}
 </section><div className="mt-5 rounded-md border-l-4 border-blue-600 bg-blue-50 p-4 text-sm text-blue-950"><b>Safe to reuse:</b> using this template creates a brand-new draft. Assignments, learner attempts, completion history, and reports are never copied.</div></main></div>;
}

function Stat({label,value}:{label:string;value:string|number}){return <div className="rounded-md bg-black/[.035] p-4"><p className="text-xs font-extrabold uppercase text-black/40">{label}</p><b className="mt-1 block text-2xl">{value}</b></div>}
function PreviewList({title,items}:{title:string;items:string[]}){return <div><h3 className="font-extrabold uppercase">{title}</h3><div className="mt-3 divide-y divide-black/10 rounded-md border border-black/10">{items.slice(0,8).map((item,index)=><p key={index} className="p-3 text-sm text-black/65">{item}</p>)}{!items.length&&<p className="p-3 text-sm text-black/40">None included</p>}</div></div>}
