import Link from "next/link";
import {redirect} from "next/navigation";
import {ManufacturerHeader} from "@/components/manufacturer-shell";
import {getActiveBrand} from "@/lib/branding";
import {createSupabaseServerClient} from "@/lib/supabase/server";

type Retailer = {company_id:string;company_name:string;member_count:number;assignment_count:number;address_line_1:string|null;address_line_2:string|null;city:string|null;state_region:string|null;postal_code:string|null;phone:string|null;website:string|null;contact_name:string|null;contact_email:string|null};

export default async function RetailersPage({searchParams}:{searchParams:Promise<{q?:string;saved?:string;imported?:string;updated?:string}>}) {
  const query = await searchParams;
  const supabase = await createSupabaseServerClient();
  const [{data:auth}, brand, {data:dashboardRows}, {data:profileRows}] = await Promise.all([supabase.auth.getUser(), getActiveBrand(), supabase.rpc("manufacturer_retailer_dashboard"), supabase.rpc("manufacturer_retailer_profiles")]);
  if (!auth.user) redirect("/login");
  if (!brand?.can_manage_training) redirect("/app");
  const profiles = new Map(((profileRows ?? []) as Omit<Retailer,"company_name"|"member_count"|"assignment_count">[]).map(profile => [profile.company_id, profile]));
  const allRetailers = ((dashboardRows ?? []) as Pick<Retailer,"company_id"|"company_name"|"member_count"|"assignment_count">[]).map(row => ({...row,...profiles.get(row.company_id)})) as Retailer[];
  const search = (query.q ?? "").trim().toLowerCase();
  const retailers = search ? allRetailers.filter(retailer => [retailer.company_name,retailer.address_line_1,retailer.address_line_2,retailer.city,retailer.state_region,retailer.postal_code,retailer.phone,retailer.website,retailer.contact_name,retailer.contact_email].some(value => value?.toLowerCase().includes(search))) : allRetailers;
  return <div className="min-h-screen bg-[#f4f4f2] text-black"><ManufacturerHeader brand={brand} email={auth.user.email}/><main className="mx-auto max-w-7xl px-5 py-10 lg:px-8 lg:py-14"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-extrabold uppercase italic tracking-[0.2em]" style={{color:brand.primary_color}}>Dealer network</p><h1 className="mt-2 text-4xl font-extrabold uppercase tracking-tight sm:text-5xl">Retailers</h1><p className="mt-3 max-w-2xl text-black/60">Manage retailer locations, contacts, and training activity across the {brand.name} network.</p></div><div className="flex flex-wrap gap-3"><Link href={`/m/${brand.slug}/app/retailers/import`} className="inline-flex min-h-12 items-center justify-center border-2 border-black px-6 font-extrabold uppercase tracking-wide hover:bg-black hover:text-white">Import CSV</Link><Link href="/app/assignments" className="inline-flex min-h-12 items-center justify-center px-6 font-extrabold uppercase tracking-wide text-white" style={{backgroundColor:brand.primary_color}}>Assign training</Link></div></div>
    {query.saved&&<div className="mt-6 border-l-4 border-green-600 bg-green-50 p-4 font-semibold text-green-900">Retailer information updated.</div>}{(query.imported!==undefined||query.updated!==undefined)&&<div className="mt-6 border-l-4 border-green-600 bg-green-50 p-4 font-semibold text-green-900">Retailer import complete: {Number(query.imported||0)} created and {Number(query.updated||0)} updated.</div>}
    <form className="mt-8 flex gap-3 border border-black/10 bg-white p-4 shadow-sm"><label className="grid flex-1 gap-1 text-xs font-extrabold uppercase tracking-wide text-black/45">Search retailer data<input name="q" defaultValue={query.q} placeholder="Name, city, state, phone, contact..." className="min-h-11 border border-black/20 px-3 text-sm font-normal normal-case tracking-normal text-black outline-none focus:border-black"/></label><div className="flex items-end gap-2"><button className="min-h-11 bg-black px-5 text-sm font-extrabold uppercase text-white">Filter</button>{search&&<Link href={`/m/${brand.slug}/app/retailers`} className="grid min-h-11 place-items-center border border-black/20 px-4 text-sm font-bold uppercase">Clear</Link>}</div></form>
    <p className="mt-4 text-sm text-black/45">Showing <b className="text-black">{retailers.length}</b> of {allRetailers.length} retailers</p>
    <section className="mt-5 overflow-x-auto border border-black/10 bg-white shadow-sm"><div className="min-w-[960px]"><div className="grid grid-cols-[minmax(220px,1.25fr)_minmax(210px,1fr)_minmax(210px,1fr)_140px_110px] items-center gap-5 border-b border-black/10 bg-black/[.03] px-5 py-4 text-xs font-extrabold uppercase tracking-wide text-black/45"><span>Retailer</span><span>Location</span><span>Contact</span><span>Training</span><span className="justify-self-end">Actions</span></div>{retailers.map(retailer => <div key={retailer.company_id} className="grid min-h-24 grid-cols-[minmax(220px,1.25fr)_minmax(210px,1fr)_minmax(210px,1fr)_140px_110px] items-center gap-5 border-b border-black/10 px-5 py-5 last:border-0"><div className="min-w-0"><b className="block truncate uppercase">{retailer.company_name}</b><span className="mt-1 block text-xs text-black/45">{retailer.website ? retailer.website.replace(/^https?:\/\//,"") : "Website not added"}</span></div><div className="text-sm"><p>{retailer.address_line_1 || "Address not added"}</p><p className="text-black/50">{[retailer.city,retailer.state_region,retailer.postal_code].filter(Boolean).join(", ") || "City and state not added"}</p></div><div className="text-sm"><p>{retailer.contact_name || "Contact not added"}</p><p className="text-black/50">{retailer.phone || retailer.contact_email || "Phone or email not added"}</p></div><div className="text-sm"><p><b>{retailer.member_count}</b> members</p><p className="text-black/50"><b>{retailer.assignment_count}</b> assignments</p></div><details className="group relative justify-self-end"><summary className="flex min-h-10 cursor-pointer list-none items-center gap-3 border-2 border-black px-4 text-xs font-extrabold uppercase marker:content-none hover:bg-black hover:text-white [&::-webkit-details-marker]:hidden">Manage <span className="text-[9px] transition group-open:rotate-180">▼</span></summary><div className="absolute right-0 z-40 mt-2 w-56 border border-black/15 bg-white py-2 shadow-2xl"><Link href={`/m/${brand.slug}/app/retailers/${retailer.company_id}/edit`} className="block px-4 py-3 text-xs font-extrabold uppercase text-black/60 hover:bg-black/5 hover:text-black">Edit Retailer</Link><Link href={`/m/${brand.slug}/app/users`} className="block px-4 py-3 text-xs font-extrabold uppercase text-black/60 hover:bg-black/5 hover:text-black">Manage Users</Link><Link href={`/m/${brand.slug}/app/assignments?retailer=${encodeURIComponent(retailer.company_name)}`} className="block px-4 py-3 text-xs font-extrabold uppercase text-black/60 hover:bg-black/5 hover:text-black">Manage Assignments</Link></div></details></div>)}{!retailers.length&&<p className="p-10 text-center text-black/55">No retailers match this filter.</p>}</div></section>
  </main></div>;
}
