import Link from "next/link";
import {redirect} from "next/navigation";
import {ManufacturerHeader} from "@/components/manufacturer-shell";
import {getActiveBrand} from "@/lib/branding";
import {createSupabaseServerClient} from "@/lib/supabase/server";

type Step={number:string;title:string;description:string;complete:boolean;href:string;action:string;help:string[]};
export default async function GettingStartedPage(){
 const s=await createSupabaseServerClient();const[{data:auth},brand]=await Promise.all([s.auth.getUser(),getActiveBrand()]);if(!auth.user)redirect("/login");if(!brand?.can_manage_training)redirect("/app");
 const[{data:products},{data:quizzes},{data:courses},{data:retailers},{data:assignments}]=await Promise.all([s.rpc("manufacturer_products_v2"),s.from("quizzes").select("id,status"),s.rpc("manufacturer_courses"),s.rpc("manufacturer_retailer_dashboard"),s.rpc("manufacturer_assignment_directory")]);
 const productRows=(products??[])as{parent_product_id:string|null;status:string}[],quizRows=(quizzes??[])as{id:string;status:string}[],courseRows=(courses??[])as{course_id:string;status:string}[];
 const branded=Boolean(brand.logo_url&&brand.primary_color),hasProducts=productRows.some(x=>!x.parent_product_id),hasQuiz=quizRows.length>0,hasCourse=courseRows.length>0,hasRetailers=Boolean(retailers?.length),hasAssignment=Boolean(assignments?.length);
 const steps:Step[]=[
  {number:"01",title:"Make the academy yours",description:"Add the manufacturer logo, colors, sign-in experience, and branded landing-page sections.",complete:branded,href:`/m/${brand.slug}/app/settings/branding`,action:"Open Brand Studio",help:["Upload a readable header logo","Set accessible primary and secondary colors","Preview desktop and mobile before publishing"]},
  {number:"02",title:"Build the product source of truth",description:"Create the products learners need to understand, including families, variations, specs, imagery, and selling points.",complete:hasProducts,href:`/m/${brand.slug}/app/products`,action:"Open Products",help:["Start with the products most often recommended at the counter","Use CSV import for an existing catalog","Keep unfinished products in draft"]},
  {number:"03",title:"Create a knowledge check",description:"Build a focused quiz around applications, comparisons, benefits, and common customer questions.",complete:hasQuiz,href:`/m/${brand.slug}/app/quizzes/new`,action:"Create Quiz",help:["Use 5–15 questions for focused learning","Add product imagery where identification matters","Submit for review before publishing"]},
  {number:"04",title:"Assemble the learning path",description:"Combine product cards, explanations, media, and quizzes into a practical course.",complete:hasCourse,href:`/m/${brand.slug}/app/courses/new`,action:"Create Course",help:["Lead with what the learner should be able to recommend","Use short modules with one clear purpose","Preview the learner experience before publishing"]},
  {number:"05",title:"Add the pilot audience",description:"Create or import retailer locations, then invite the people who will manage and complete training.",complete:hasRetailers,href:`/m/${brand.slug}/app/retailers`,action:"Manage Retailers",help:["Use one record per physical location","Include a primary retailer contact","Invite a small pilot group before a network-wide launch"]},
  {number:"06",title:"Launch the first assignment",description:"Choose published training, select the audience, set a due date, and monitor delivery.",complete:hasAssignment,href:`/m/${brand.slug}/app/assignments`,action:"Assign Training",help:["Start with a clear pilot deadline","Use notifications intentionally","Review reporting after the first completions arrive"]},
 ];
 const complete=steps.filter(x=>x.complete).length;
 return <div className="min-h-screen bg-[#f4f4f2]"><ManufacturerHeader brand={brand} email={auth.user.email}/><main className="mx-auto max-w-6xl px-5 py-10 lg:px-8 lg:py-14"><div className="grid gap-8 lg:grid-cols-[1fr_300px] lg:items-end"><div><p className="text-sm font-extrabold uppercase italic tracking-[.2em]" style={{color:brand.primary_color}}>Pilot launch guide</p><h1 className="mt-2 text-4xl font-extrabold uppercase tracking-tight sm:text-5xl">Launch your academy with confidence</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-black/55">Follow the complete path from brand setup to measurable retailer training. Progress is calculated from the work already completed in this academy.</p></div><div className="rounded-lg bg-black p-6 text-white"><span className="text-xs font-extrabold uppercase tracking-[.16em] text-white/50">Launch readiness</span><div className="mt-3 flex items-end gap-2"><b className="text-5xl">{complete}</b><span className="pb-1 text-white/50">of {steps.length} complete</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full" style={{width:`${complete/steps.length*100}%`,backgroundColor:brand.primary_color}}/></div></div></div>
 <section className="mt-10 grid gap-5">{steps.map(step=><article key={step.number} className="overflow-hidden rounded-lg border border-black/10 bg-white shadow-sm"><div className="grid gap-5 p-6 md:grid-cols-[70px_1fr_auto] md:items-center"><span className={`grid h-12 w-12 place-items-center rounded-md text-sm font-extrabold ${step.complete?"bg-green-100 text-green-800":"bg-black text-white"}`}>{step.complete?"✓":step.number}</span><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-extrabold uppercase">{step.title}</h2><span className={`rounded-full px-3 py-1 text-[10px] font-extrabold uppercase ${step.complete?"bg-green-100 text-green-800":"bg-amber-100 text-amber-800"}`}>{step.complete?"Complete":"Next step"}</span></div><p className="mt-2 max-w-3xl text-sm leading-6 text-black/55">{step.description}</p></div><Link href={step.href} className="inline-flex min-h-11 items-center justify-center rounded-md px-5 text-xs font-extrabold uppercase text-white" style={{backgroundColor:step.complete?"#111":brand.primary_color}}>{step.complete?"Review":"Start"} {step.action}</Link></div><details className="group border-t border-black/10 bg-black/[.02]"><summary className="flex cursor-pointer list-none items-center justify-between px-6 py-4 text-xs font-extrabold uppercase text-black/50 [&::-webkit-details-marker]:hidden">Practical guidance <span className="group-open:rotate-180">▼</span></summary><ul className="grid gap-3 border-t border-black/10 px-6 py-5 text-sm text-black/60 sm:grid-cols-3">{step.help.map(item=><li key={item} className="flex gap-2"><span style={{color:brand.primary_color}}>✓</span><span>{item}</span></li>)}</ul></details></article>)}</section>
 <section className="mt-8 grid gap-5 md:grid-cols-3"><Resource title="Use a starter template" text="Begin with a proven structure, then adapt the content and brand voice." href={`/m/${brand.slug}/app/templates`} action="Browse templates"/><Resource title="Import existing content" text="Use guided CSV templates for products, quizzes, courses, and retailers." href={`/m/${brand.slug}/app/products/import`} action="Start an import"/><Resource title="Validate the pilot" text="Check completion, scores, overdue work, and dealer readiness from one report." href={`/m/${brand.slug}/app/reports`} action="Open reports"/></section>
 </main></div>;
}
function Resource({title,text,href,action}:{title:string;text:string;href:string;action:string}){return <article className="rounded-lg border border-black/10 bg-white p-5 shadow-sm"><h3 className="font-extrabold uppercase">{title}</h3><p className="mt-2 min-h-16 text-sm leading-6 text-black/50">{text}</p><Link href={href} className="mt-4 inline-flex text-xs font-extrabold uppercase hover:underline">{action} →</Link></article>}
