import Link from "next/link";
import type {Metadata} from "next";
import AcademyAuthLayout from "@/components/academy-auth-layout";
import {getPublicBrand,getPublicLandingExperience} from "@/lib/branding";
import {login} from "./actions";

export async function generateMetadata({searchParams}:{searchParams:Promise<{brand?:string;next?:string}>}):Promise<Metadata>{const p=await searchParams;const brand=await getPublicBrand(p.brand);return{title:brand?`Sign in | ${brand.name} Academy`:"Sign in | JobberTrain"}}

export default async function LoginPage({searchParams}:{searchParams:Promise<{next?:string;error?:string;brand?:string;force?:string;reset?:string}>}){
 const params=await searchParams;const next=params.next??"/app";const inferredBrand=params.brand??next.match(/^\/m\/([^/]+)\/app/)?.[1];const platformLogin=next.startsWith("/platform");
 const[brand,experience]=await Promise.all([getPublicBrand(inferredBrand),getPublicLandingExperience(inferredBrand)]);const primary=brand?.primary_color??"#ff4f1f";const loginExperience=experience?.settings.login;
 return <AcademyAuthLayout brand={brand} platform={platformLogin&&!brand} backgroundImage={loginExperience?.image_url} eyebrow={brand?`${brand.name} learning center`:platformLogin?"Manufacturer training platform":"Universal training access"} headline={loginExperience?.headline||brand?.landing_headline||(platformLogin?<>Product knowledge.<br/><span className="italic" style={{color:primary}}>Delivered at scale.</span></>:<>Know the product.<br/><span className="italic" style={{color:primary}}>Sell with confidence.</span></>)} description={loginExperience?.description||brand?.landing_description||(platformLogin?"Build branded training, equip retailer teams, and measure product knowledge across your dealer network.":"Access every academy, assignment, and training result with one JobberTrain account.")}>
  <p className="text-sm font-extrabold uppercase italic tracking-[.2em]" style={{color:primary}}>{platformLogin&&!brand?"Platform access":"Welcome back"}</p><h2 className="mt-2 text-4xl font-extrabold uppercase tracking-tight">Sign in</h2><p className="mt-3 text-black/60">Enter your account details to continue.</p>
  {params.error&&<div role="alert" className="mt-6 border-l-4 bg-red-50 p-4 text-sm text-red-900" style={{borderColor:primary}}><b>We couldn&apos;t sign you in.</b><br/>{params.error}</div>}{params.reset&&<div role="status" className="mt-6 border-l-4 border-green-600 bg-green-50 p-4 text-sm text-green-900"><b>Password updated.</b><br/>Sign in with your new password.</div>}
  <form action={login} className="mt-8 grid gap-5"><input type="hidden" name="next" value={next}/>{params.force==="1"&&<input type="hidden" name="force" value="1"/>}{brand&&<input type="hidden" name="brand" value={brand.slug}/>}<label className="grid gap-2 font-bold">Email address<input name="email" type="email" required autoComplete="email" placeholder="you@company.com" className="min-h-13 border border-black/20 px-4 font-normal outline-none focus:border-black"/></label><label className="grid gap-2 font-bold">Password<input name="password" type="password" required autoComplete="current-password" className="min-h-13 border border-black/20 px-4 font-normal outline-none focus:border-black"/></label><button className="mt-1 min-h-13 px-6 font-extrabold uppercase text-white transition hover:brightness-90" style={{backgroundColor:primary}}>Sign in</button></form>
  <div className="mt-6 flex items-center justify-between gap-4 text-sm font-bold"><Link href={`/forgot-password${brand?`?brand=${brand.slug}`:""}`} className="hover:underline">Forgot password?</Link><Link href={brand?`/m/${brand.slug}`:"/"} className="text-black/45 hover:text-black">Return home →</Link></div>
 </AcademyAuthLayout>;
}
