import Link from "next/link";

const capabilities = [
  ["White-label academies", "Give every manufacturer a branded training destination without maintaining separate software."],
  ["Retailer enablement", "Connect product makers to dealer locations, managers, and frontline sales teams."],
  ["Measurable knowledge", "Track assignments, completions, quiz scores, and product-training performance."],
];

export default function Home() {
  return <main className="min-h-screen bg-[#f4f1eb] text-[#101010]">
    <header className="border-b border-black/10"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><Link href="/" className="text-2xl font-black uppercase tracking-[-0.05em]">Jobber<span className="text-[#ff4f1f]">Train</span></Link><div className="flex items-center gap-5"><a href="#platform" className="hidden text-sm font-bold uppercase tracking-wide sm:block">Platform</a><Link href="/login?next=/platform" className="bg-black px-5 py-3 text-sm font-extrabold uppercase tracking-wide text-white hover:bg-[#ff4f1f]">Platform sign in</Link></div></div></header>
    <section className="relative isolate overflow-hidden bg-[#101010] px-5 py-24 text-white lg:px-8 lg:py-32"><div className="absolute -right-28 -top-44 -z-10 h-[34rem] w-[34rem] rounded-full border-[92px] border-[#ff4f1f] opacity-90" /><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><p className="text-sm font-extrabold uppercase tracking-[0.24em] text-[#ff7048]">Manufacturer-to-retailer training</p><h1 className="mt-6 max-w-4xl text-5xl font-black uppercase leading-[0.92] tracking-[-0.05em] sm:text-6xl lg:text-7xl">Turn product knowledge into <span className="text-[#ff4f1f]">sales confidence.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/65">JobberTrain powers private-label product academies that help manufacturers educate retailer teams, measure knowledge, and improve the customer conversation.</p><a href="#platform" className="mt-9 inline-flex min-h-14 items-center bg-[#ff4f1f] px-7 font-extrabold uppercase tracking-wide text-white hover:bg-[#e43f13]">Explore the platform</a></div><div className="border border-white/15 bg-white/5 p-5 backdrop-blur"><div className="bg-[#f4f1eb] p-7 text-black"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#ff4f1f]">Network performance</p><h2 className="mt-2 text-2xl font-black uppercase">One platform. Every brand.</h2><div className="mt-7 grid grid-cols-3 gap-3">{[["24","Brands"],["480","Retailers"],["91%","Avg. score"]].map(([value,label]) => <div key={label} className="border border-black/10 bg-white p-4 text-center"><b className="block text-2xl">{value}</b><span className="text-xs text-black/45">{label}</span></div>)}</div><div className="mt-6 space-y-3">{["Branded manufacturer academy","Retailer team assignments","Progress and quiz reporting"].map((item,index) => <div key={item} className="flex items-center gap-3 border border-black/10 bg-white p-4"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#ff4f1f] text-xs font-black text-white">{index+1}</span><b className="text-sm">{item}</b></div>)}</div></div></div></div></section>
    <section id="platform" className="px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-[#ff4f1f]">Built for the jobber channel</p><h2 className="mt-4 max-w-4xl text-4xl font-black uppercase leading-tight tracking-[-0.035em] sm:text-5xl">A shared training engine behind every manufacturer brand.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{capabilities.map(([title,copy],index) => <article key={title} className="border border-black/10 bg-white p-7 shadow-sm"><span className="text-sm font-black text-[#ff4f1f]">0{index+1}</span><h3 className="mt-5 text-xl font-black uppercase">{title}</h3><p className="mt-3 leading-7 text-black/60">{copy}</p></article>)}</div></div></section>
    <footer className="border-t border-black/10 px-5 py-8 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 text-sm text-black/50 sm:flex-row"><b className="uppercase text-black">JobberTrain</b><span>Industry product training infrastructure</span></div></footer>
  </main>;
}
