import Link from "next/link";

const capabilities = [
  { number: "01", title: "Build once", copy: "Turn product knowledge into reusable product cards, video lessons, courses, and quizzes." },
  { number: "02", title: "Deliver by brand", copy: "Give each manufacturer a private, fully branded academy for its dealer and internal teams." },
  { number: "03", title: "Prove the impact", copy: "Track assignments, completions, attempts, scores, and knowledge across the network." },
];

const features = [
  ["Product library", "Create a dependable source of truth for features, specifications, images, and selling points."],
  ["Course builder", "Combine product cards, text, media, and quizzes into structured learning paths."],
  ["Quiz engine", "Build, preview, duplicate, import, publish, and assign product-knowledge assessments."],
  ["Team assignments", "Train manufacturer employees internally or distribute learning to retailer locations."],
  ["Retailer network", "Organize jobbers, managers, and frontline learners without mixing manufacturer data."],
  ["Performance reporting", "See who has completed training, how they scored, and where knowledge gaps remain."],
];

const outcomes = [
  "Faster onboarding for new counter and sales staff",
  "More consistent product stories across every location",
  "Greater confidence recommending the right product",
  "Clear visibility into retailer training participation",
];

const brandStages = [
  ["New brands", "Earn trust faster", "Give unfamiliar products a clear, repeatable story so retail teams understand what makes them worth recommending."],
  ["Growing brands", "Scale knowledge with distribution", "Keep product education consistent as new dealers, locations, representatives, and SKUs enter the network."],
  ["Legacy brands", "Stay relevant at the counter", "Refresh long-standing product knowledge, introduce innovation clearly, and remain top of mind with changing retail teams."],
];

export default function Home() {
  return <main className="min-h-screen overflow-hidden bg-[#f4f1eb] text-[#101010]">
    <header className="sticky top-0 z-40 border-b border-black/10 bg-[#f4f1eb]/95 backdrop-blur">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8">
        <Link href="/" className="text-2xl font-black uppercase tracking-[-0.05em]">Jobber<span className="text-[#ff4f1f]">Train</span></Link>
        <nav className="hidden items-center gap-7 lg:flex" aria-label="Main navigation">
          <a href="#how-it-works" className="text-xs font-extrabold uppercase tracking-[.12em] hover:text-[#ff4f1f]">How it works</a>
          <a href="#features" className="text-xs font-extrabold uppercase tracking-[.12em] hover:text-[#ff4f1f]">Features</a>
          <a href="#for-industry" className="text-xs font-extrabold uppercase tracking-[.12em] hover:text-[#ff4f1f]">Who it’s for</a>
        </nav>
        <div className="flex items-center gap-3"><Link href="/login" className="hidden px-3 py-3 text-xs font-extrabold uppercase tracking-wide sm:block">Sign in</Link><a href="#pilot" className="bg-black px-4 py-3 text-xs font-extrabold uppercase tracking-wide text-white transition hover:bg-[#ff4f1f] sm:px-5">Explore a pilot</a></div>
      </div>
    </header>

    <section className="relative isolate overflow-hidden bg-[#101010] px-5 py-20 text-white lg:px-8 lg:py-28">
      <div className="absolute inset-0 -z-20 bg-[linear-gradient(to_right,rgba(255,255,255,.045)_1px,transparent_1px),linear-gradient(to_bottom,rgba(255,255,255,.045)_1px,transparent_1px)] bg-[size:48px_48px]" />
      <div className="absolute -right-32 -top-32 -z-10 h-96 w-96 rotate-12 border-[72px] border-[#343434] sm:h-[34rem] sm:w-[34rem]" />
      <div className="absolute bottom-0 right-0 -z-10 h-40 w-2/3 bg-gradient-to-t from-black/70 to-transparent" />
      <div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[1.15fr_.85fr] lg:items-center">
        <div><p className="text-sm font-extrabold uppercase tracking-[0.24em] text-[#ff7048]">Product knowledge for the last mile of the sale</p><h1 className="mt-6 max-w-4xl text-5xl font-black uppercase leading-[0.9] tracking-[-0.055em] sm:text-6xl lg:text-[5.2rem]">Your product cannot sell itself at the counter.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/70">Manufacturers invest in engineering, inventory, distribution, and demand. But the final recommendation often belongs to a salesperson who may not know the product yet. JobberTrain closes that gap with branded, measurable training built for the people who influence the purchase.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#pilot" className="inline-flex min-h-14 items-center bg-[#ff4f1f] px-7 font-extrabold uppercase tracking-wide text-white transition hover:bg-[#e43f13]">See it in action</a><a href="#why-training" className="inline-flex min-h-14 items-center border border-white/30 px-7 font-extrabold uppercase tracking-wide transition hover:border-white hover:bg-white hover:text-black">Why training matters</a></div></div>
        <div className="relative border border-white/15 bg-white/5 p-4 shadow-2xl backdrop-blur"><div className="bg-[#f4f1eb] text-black"><div className="flex items-center justify-between border-b border-black/10 px-5 py-4"><div className="h-5 w-28 rounded bg-black" /><span className="text-[10px] font-black uppercase tracking-[.18em] text-black/40">Training center</span></div><div className="p-6"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#ff4f1f]">Assigned learning</p><h2 className="mt-2 text-2xl font-black uppercase">Product specialist path</h2><div className="mt-6 space-y-3">{[["Product fundamentals","Complete"],["Choosing the right fit","In progress"],["Confidence check","Up next"]].map(([title,status],index) => <div key={title} className="flex items-center gap-4 border border-black/10 bg-white p-4"><span className={`grid h-9 w-9 shrink-0 place-items-center text-xs font-black ${index === 0 ? "bg-green-100 text-green-800" : index === 1 ? "bg-[#ff4f1f] text-white" : "bg-black/5 text-black/40"}`}>{index === 0 ? "✓" : index + 1}</span><div className="min-w-0 flex-1"><b className="block truncate text-sm uppercase">{title}</b><span className="text-xs text-black/45">{status}</span></div></div>)}</div><div className="mt-5 grid grid-cols-2 gap-3"><div className="bg-black p-4 text-white"><b className="block text-2xl">3</b><span className="text-xs text-white/55">Learning blocks</span></div><div className="bg-[#ff4f1f] p-4 text-white"><b className="block text-2xl">80%</b><span className="text-xs text-white/70">Passing score</span></div></div></div></div></div>
      </div>
    </section>

    <section id="why-training" className="border-b border-black/10 bg-[#dededb] px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="text-sm font-extrabold uppercase tracking-[.2em] text-[#d93a10]">The sales stop-gap</p><h2 className="mt-4 text-4xl font-black uppercase leading-[.95] tracking-[-.04em] sm:text-5xl">The product journey ends with a human conversation.</h2></div><div><p className="text-xl font-bold leading-9 text-black/75">A product can be engineered perfectly, marketed clearly, stocked nationally, and still lose at the point of sale if the person helping the customer cannot explain why it is different.</p><p className="mt-6 text-lg leading-8 text-black/55">Retail staff manage thousands of products and constant turnover. They do not need another document library. They need focused learning that makes the right features, applications, comparisons, and customer benefits easy to remember—and easy to use in a real sales conversation.</p><div className="mt-8 grid gap-px bg-black/15 sm:grid-cols-3">{[["Know","What the product does"],["Understand","Who it is right for"],["Recommend","Why it earns the sale"]].map(([title,copy])=><div key={title} className="bg-[#f4f4f2] p-5"><b className="text-sm uppercase text-[#d93a10]">{title}</b><p className="mt-2 text-sm font-bold text-black/60">{copy}</p></div>)}</div></div></div></section>

    <section className="border-b border-black/10 bg-white px-5 py-7 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 md:flex-row md:items-center md:justify-between"><p className="max-w-md text-sm font-black uppercase tracking-[.15em]">Built for the people who move products through the channel</p><div className="flex flex-wrap gap-x-5 gap-y-2 text-xs font-extrabold uppercase tracking-[.12em] text-black/45"><span>Manufacturers</span><span className="text-[#ff4f1f]">•</span><span>Distributors</span><span className="text-[#ff4f1f]">•</span><span>Jobbers</span><span className="text-[#ff4f1f]">•</span><span>Sales teams</span></div></div></section>

    <section id="how-it-works" className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr] lg:items-end"><div><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-[#ff4f1f]">From expertise to execution</p><h2 className="mt-4 text-4xl font-black uppercase leading-[.95] tracking-[-0.04em] sm:text-5xl">One simple training loop.</h2></div><p className="max-w-2xl text-lg leading-8 text-black/55 lg:justify-self-end">Your team already knows what makes the product valuable. JobberTrain makes that knowledge easy to build, distribute, and measure at scale.</p></div><div className="mt-12 grid gap-px overflow-hidden border border-black/10 bg-black/10 md:grid-cols-3">{capabilities.map((item) => <article key={item.number} className="bg-white p-7 lg:p-9"><span className="text-sm font-black text-[#ff4f1f]">{item.number}</span><h3 className="mt-12 text-2xl font-black uppercase">{item.title}</h3><p className="mt-4 leading-7 text-black/55">{item.copy}</p></article>)}</div></div></section>

    <section id="features" className="bg-[#171717] px-5 py-20 text-white lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-[#ff7048]">The complete enablement system</p><h2 className="mt-4 text-4xl font-black uppercase leading-tight tracking-[-0.04em] sm:text-5xl">Everything needed to build product confidence.</h2></div><div className="mt-12 grid gap-px border border-white/10 bg-white/10 md:grid-cols-2 lg:grid-cols-3">{features.map(([title,copy],index) => <article key={title} className="group bg-[#171717] p-7 transition hover:bg-[#202020] lg:p-8"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center border border-white/15 text-sm font-black text-[#ff7048]">{String(index+1).padStart(2,"0")}</span><span className="text-xl text-white/20 transition group-hover:text-[#ff4f1f]">↗</span></div><h3 className="mt-7 text-xl font-black uppercase">{title}</h3><p className="mt-3 leading-7 text-white/50">{copy}</p></article>)}</div></div></section>

    <section className="bg-white px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-4xl"><p className="text-sm font-extrabold uppercase tracking-[.2em] text-[#d93a10]">Built for every stage</p><h2 className="mt-4 text-4xl font-black uppercase leading-[.95] tracking-[-.04em] sm:text-5xl">Relevance is never automatic.</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-black/55">Whether a brand is earning its first dealer relationships or protecting decades of market leadership, retailer knowledge must be continuously built and renewed.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{brandStages.map(([stage,title,copy],index)=><article key={stage} className="border border-black/15 bg-[#f4f4f2] p-7 lg:p-8"><span className="text-xs font-black uppercase tracking-[.18em] text-black/35">0{index+1} · {stage}</span><h3 className="mt-8 text-2xl font-black uppercase">{title}</h3><p className="mt-4 leading-7 text-black/55">{copy}</p></article>)}</div></div></section>

    <section id="for-industry" className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center"><div className="relative min-h-[32rem] overflow-hidden bg-[#ff4f1f] p-8 text-white sm:p-12"><div className="absolute -bottom-28 -right-28 h-80 w-80 rounded-full border-[70px] border-black/15" /><p className="text-xs font-black uppercase tracking-[.2em] text-black/60">Built around your brand</p><h2 className="mt-5 max-w-lg text-4xl font-black uppercase leading-[.95] tracking-[-.04em] sm:text-5xl">Your customers see you. Not us.</h2><p className="mt-6 max-w-md text-lg leading-8 text-white/80">Every manufacturer controls its own logo, colors, landing page, product content, users, and training experience—inside one secure platform.</p><div className="absolute bottom-8 left-8 right-8 flex items-center justify-between border-t border-white/30 pt-5 sm:bottom-12 sm:left-12 sm:right-12"><b className="uppercase">White-label by design</b><span className="text-2xl">→</span></div></div><div><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-[#ff4f1f]">What better training changes</p><h2 className="mt-4 text-4xl font-black uppercase leading-tight tracking-[-0.04em] sm:text-5xl">Equip the person at the point of sale.</h2><p className="mt-6 text-lg leading-8 text-black/55">The best product rarely wins when the salesperson cannot explain it. Give every learner a clear reason to recommend your brand.</p><div className="mt-8 space-y-1">{outcomes.map((item) => <div key={item} className="flex gap-4 border-t border-black/10 py-5"><span className="font-black text-[#ff4f1f]">✓</span><b>{item}</b></div>)}</div></div></div></section>

    <section id="pilot" className="border-y border-black/10 bg-white px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-[#ff4f1f]">Live pilot experience</p><h2 className="mt-4 max-w-3xl text-4xl font-black uppercase leading-[.95] tracking-[-.04em] sm:text-5xl">See how a manufacturer academy comes to life.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-black/55">Explore the GEN-Y Hitch training portal to see how JobberTrain adapts to a manufacturer’s identity while preserving the same powerful training engine.</p></div><div className="border border-black/10 bg-[#f4f1eb] p-7 shadow-sm"><p className="text-xs font-black uppercase tracking-[.18em] text-black/40">Pilot academy</p><h3 className="mt-3 text-2xl font-black uppercase">GEN-Y Hitch Training</h3><p className="mt-3 leading-7 text-black/55">Branded landing page, product education, structured courses, quizzes, and team access.</p><Link href="/m/gen-y-hitch" className="mt-7 flex min-h-14 items-center justify-between bg-black px-6 font-extrabold uppercase text-white transition hover:bg-[#ff4f1f]">Explore the academy <span>↗</span></Link></div></div></section>

    <section className="bg-[#ff4f1f] px-5 py-20 text-white lg:px-8 lg:py-24"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-9 lg:flex-row lg:items-end"><div><p className="text-sm font-black uppercase tracking-[.2em] text-black/60">Ready for a smarter dealer network?</p><h2 className="mt-4 max-w-4xl text-4xl font-black uppercase leading-[.95] tracking-[-.04em] sm:text-6xl">Make product knowledge your competitive advantage.</h2></div><Link href="/login" className="inline-flex min-h-14 shrink-0 items-center justify-center bg-black px-8 font-extrabold uppercase tracking-wide text-white transition hover:bg-white hover:text-black">Platform sign in</Link></div></section>

    <footer className="bg-[#101010] px-5 py-10 text-white lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 sm:flex-row sm:items-center"><Link href="/" className="text-2xl font-black uppercase tracking-[-0.05em]">Jobber<span className="text-[#ff4f1f]">Train</span></Link><div className="flex flex-wrap gap-5 text-xs font-extrabold uppercase tracking-wide text-white/45"><span>Manufacturer training</span><span>Retailer enablement</span><span>Product knowledge</span></div><span className="text-xs text-white/35">© {new Date().getFullYear()} JobberTrain</span></div></footer>
  </main>;
}
