import Link from "next/link";
import { redirect } from "next/navigation";
import { ManufacturerHeader } from "@/components/manufacturer-shell";
import { getActiveBrand } from "@/lib/branding";
import { DealerProgram,effectiveProgramStatus,formatProgramDate,programStatusClass } from "@/lib/dealer-programs";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import {AcademyPageHeader,academyButton,academyInput} from "@/components/academy-ui";

type Program=DealerProgram&{dealer_program_products:{product_id:string}[]};
export default async function DealerProgramsPage({searchParams}:{searchParams:Promise<{q?:string}>}){
  const query=await searchParams,supabase=await createSupabaseServerClient();
  const[{data:auth},brand,{data}]=await Promise.all([supabase.auth.getUser(),getActiveBrand(),supabase.from("dealer_programs").select("*,dealer_program_products(product_id)").order("starts_at",{ascending:false,nullsFirst:false})]);
  if(!auth.user)redirect("/login");if(!brand)redirect("/academies");
  const search=(query.q??"").trim().toLowerCase(),all=(data??[])as Program[],programs=all.filter(p=>!search||`${p.title} ${p.summary} ${p.offer_details}`.toLowerCase().includes(search));
  return <div className="min-h-screen bg-[#f4f4f2]"><ManufacturerHeader brand={brand} email={auth.user.email}/><main className="mx-auto max-w-7xl px-5 py-10 lg:px-8 lg:py-14">
    <AcademyPageHeader eyebrow="Private dealer opportunities" title="Dealer Offers" description={`Exclusive stocking, display, bundle, and promotional offers available through ${brand.name}.`} accent={brand.primary_color} actions={brand.can_manage_training?<Link href={`/m/${brand.slug}/app/programs`} className={academyButton.secondary}>Manage Offers</Link>:undefined}/>
    {brand.can_manage_training&&<div className="mt-7 border-l-4 bg-amber-50 p-4 text-sm text-amber-950" style={{borderColor:brand.primary_color}}><b>Manufacturer preview:</b> You can see drafts, scheduled programs, and archived offers here. Retailer users see only active programs for which they are eligible.</div>}
    <form className="mt-8 flex gap-3 rounded-lg border border-black/10 bg-white p-4 shadow-sm"><label className="grid flex-1 gap-1 text-xs font-extrabold uppercase tracking-wide text-black/45">Search dealer offers<input name="q" defaultValue={query.q} placeholder="Offer, product, or promotion" className={`${academyInput} normal-case tracking-normal`}/></label><button className={`${academyButton.primary} self-end bg-black`}>Search</button></form>
    <section className="mt-5 grid gap-5 md:grid-cols-2">{programs.map(program=>{const status=effectiveProgramStatus(program);return <article key={program.id} className="flex flex-col rounded-lg border border-black/10 bg-white p-6 shadow-sm sm:p-7"><div className="flex items-start justify-between gap-4"><span className={`inline-flex px-2 py-1 text-[10px] font-extrabold uppercase ${programStatusClass(status)}`}>{status}</span><span className="text-xs font-bold uppercase text-black/35">{program.audience_mode==="all"?"All retailers":"Selected retailers"}</span></div><h2 className="mt-6 text-2xl font-extrabold uppercase leading-tight">{program.title}</h2><p className="mt-4 flex-1 leading-7 text-black/55">{program.summary}</p><div className="mt-6 grid grid-cols-2 gap-4 border-y border-black/10 py-4 text-sm"><div><span className="block text-[10px] font-extrabold uppercase text-black/35">Available</span><b>{program.starts_at?formatProgramDate(program.starts_at):"Now"}</b></div><div><span className="block text-[10px] font-extrabold uppercase text-black/35">Ends</span><b>{program.ends_at?formatProgramDate(program.ends_at):"No expiration"}</b></div></div><div className="mt-5 flex items-center justify-between gap-4"><span className="text-xs font-bold uppercase text-black/40">{program.dealer_program_products.length} related product{program.dealer_program_products.length===1?"":"s"}{program.flyer_path?" · PDF flyer":""}</span><Link href={`/m/${brand.slug}/app/dealer-programs/${program.id}`} className={academyButton.primary} style={{backgroundColor:brand.primary_color}}>View offer</Link></div></article>})}{!programs.length&&<div className="border border-dashed border-black/15 bg-white p-12 text-center md:col-span-2"><h2 className="text-2xl font-extrabold uppercase">No offers available</h2><p className="mt-3 text-black/50">There are no dealer offers matching this search or available to your retailer right now.</p></div>}</section>
  </main></div>;
}
