"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";

type MenuName = "learn" | "manage" | null;
type Props = { portal:string; primary:string; canManageTraining:boolean; canViewReports:boolean; canManageBrand:boolean };
type MenuLinkProps = { href:string; title:string; description:string; accent?:boolean };

export function AcademyDesktopMenu({portal,primary,canManageTraining,canViewReports,canManageBrand}:Props){
  const[open,setOpen]=useState<MenuName>(null);const root=useRef<HTMLDivElement>(null);
  useEffect(()=>{const outside=(event:MouseEvent)=>{if(root.current&&!root.current.contains(event.target as Node))setOpen(null)};const escape=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(null)};document.addEventListener("mousedown",outside);window.addEventListener("keydown",escape);return()=>{document.removeEventListener("mousedown",outside);window.removeEventListener("keydown",escape)}},[]);

  const MenuLink=({href,title,description,accent=false}:MenuLinkProps)=><Link href={href} onClick={()=>setOpen(null)} className="group/link block rounded-lg px-4 py-3 transition hover:bg-black/[.045] focus-visible:outline-2 focus-visible:outline-black"><span className="flex items-center justify-between gap-3 text-sm font-black uppercase tracking-[.04em]" style={accent?{color:primary}:undefined}>{title}<span aria-hidden="true" className="translate-x-0 text-black/20 transition group-hover/link:translate-x-1 group-hover/link:text-black/55">→</span></span><span className="mt-1 block text-xs leading-5 text-black/45">{description}</span></Link>;
  const button=(name:Exclude<MenuName,null>,label:string)=><button type="button" aria-expanded={open===name} aria-controls={`academy-${name}-menu`} onClick={()=>setOpen(current=>current===name?null:name)} className={`flex min-h-10 items-center gap-2 rounded-md px-4 text-xs font-black uppercase tracking-[.06em] transition focus-visible:outline-2 focus-visible:outline-black ${open===name?"bg-black/[.055] text-black":"text-black hover:bg-black/5"}`}>{label}<span aria-hidden="true" className={`text-[9px] transition-transform ${open===name?"rotate-180":""}`}>▼</span></button>;

  return <div ref={root} className="relative hidden items-center gap-1 lg:flex">{button("learn","Learn")}{(canManageTraining||canViewReports||canManageBrand)&&button("manage","Manage")}
    {open==="learn"&&<div id="academy-learn-menu" className="fixed inset-x-0 top-[76px] z-50 border-b border-black/10 bg-white shadow-[0_18px_40px_rgba(16,16,16,.11)]"><div className="mx-auto grid max-w-7xl grid-cols-3 gap-8 px-8 py-8">
      <section><p className="mb-3 px-4 text-[10px] font-black uppercase tracking-[.2em] text-black/35">Build Product Knowledge</p>{canManageTraining&&<MenuLink href={`${portal}/products`} title="Products" description="Create the trusted source for product details, variations, and selling points."/>}{canManageTraining&&<MenuLink href={portal} title="Quizzes" description="Build knowledge checks that reinforce the information that matters."/>}{canManageTraining&&<MenuLink href={`${portal}/courses`} title="Courses" description="Combine products, media, lessons, and quizzes into learning paths."/>}{canManageTraining&&<MenuLink href={`${portal}/templates`} title="Templates" description="Reuse proven structures and JobberTrain starter content."/>}</section>
      <section className="border-l border-black/10 pl-8"><p className="mb-3 px-4 text-[10px] font-black uppercase tracking-[.2em] text-black/35">Dealer Enablement</p>{canManageTraining&&<MenuLink href={`${portal}/getting-started`} title="Launch Guide" description="Follow the guided path from academy setup to the first measurable pilot."/>}<MenuLink href={`${portal}/dealer-programs`} title="Dealer Offers" description="Share private stocking, display, bundle, and promotional opportunities."/></section>
      <section className="border-l border-black/10 pl-8"><p className="mb-3 px-4 text-[10px] font-black uppercase tracking-[.2em] text-black/35">My Academy</p><MenuLink href={`${portal}/my-training`} title="My Training" description="Continue assigned courses and quizzes." accent/><MenuLink href="/academies" title="My Academies" description="Move between the manufacturer academies you can access." accent/><MenuLink href={`${portal}/certificates`} title="My Certificates" description="View and download earned credentials." accent/><MenuLink href={`${portal}/rewards`} title="My Rewards" description="Track points and redeem available rewards." accent/></section>
    </div></div>}
    {open==="manage"&&<div id="academy-manage-menu" className="fixed inset-x-0 top-[76px] z-50 border-b border-black/10 bg-white shadow-[0_18px_40px_rgba(16,16,16,.11)]"><div className="mx-auto grid max-w-7xl grid-cols-3 gap-8 px-8 py-8">
      <section><p className="mb-3 px-4 text-[10px] font-black uppercase tracking-[.2em] text-black/35">Dealer Network</p>{canManageTraining&&<MenuLink href={`${portal}/retailers`} title="Retailers" description="Manage dealer locations, contact information, and academy access."/>}{canManageTraining&&<MenuLink href={`${portal}/assignments`} title="Assignments" description="Deliver training to manufacturer teams or selected retailer audiences."/>}</section>
      <section className="border-l border-black/10 pl-8"><p className="mb-3 px-4 text-[10px] font-black uppercase tracking-[.2em] text-black/35">Programs & Communication</p>{canManageTraining&&<MenuLink href={`${portal}/certifications`} title="Certifications" description="Define requirements and track certified dealer status."/>}{canManageTraining&&<MenuLink href={`${portal}/programs`} title="Manage Offers" description="Create and target private dealer opportunities."/>}{canManageTraining&&<MenuLink href={`${portal}/rewards/manage`} title="Rewards" description="Configure points, catalog items, and fulfillment."/>}{canManageTraining&&<MenuLink href={`${portal}/notifications`} title="Notifications" description="Control learner reminders and manager updates."/>}</section>
      <section className="border-l border-black/10 pl-8"><p className="mb-3 px-4 text-[10px] font-black uppercase tracking-[.2em] text-black/35">Insights & Administration</p>{canManageTraining&&<MenuLink href={`${portal}/reviews`} title="Review Queue" description="Approve submitted products, quizzes, and courses before publishing."/>}{canViewReports&&<MenuLink href={`${portal}/reports`} title="Reports" description="Measure participation, progress, completion, and performance."/>}{canManageBrand&&<MenuLink href={`${portal}/users`} title="Users" description="Invite people and manage manufacturer or retailer access."/>}{canManageBrand&&<MenuLink href={`${portal}/settings/branding`} title="Brand Studio" description="Control the academy identity and landing-page experience." accent/>}</section>
    </div></div>}
  </div>;
}
