"use client";

import Link from "next/link";
import {useEffect,useRef,useState} from "react";

type Props={slug:string;primary:string;canManageTraining:boolean;canViewReports:boolean;canManageBrand:boolean};

export function AcademyMobileMenu({slug,primary,canManageTraining,canViewReports,canManageBrand}:Props){
  const[open,setOpen]=useState(false);const portal=`/m/${slug}/app`,navRef=useRef<HTMLElement>(null),triggerRef=useRef<HTMLButtonElement>(null);
  useEffect(()=>{if(!open)return;const prior=document.body.style.overflow;document.body.style.overflow="hidden";const focusable=()=>Array.from(navRef.current?.querySelectorAll<HTMLElement>('a[href],button:not([disabled]),input:not([disabled])')??[]);focusable()[0]?.focus();const keys=(event:KeyboardEvent)=>{if(event.key==="Escape"){setOpen(false);triggerRef.current?.focus();return}if(event.key!=="Tab")return;const items=focusable();if(!items.length)return;const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};window.addEventListener("keydown",keys);return()=>{document.body.style.overflow=prior;window.removeEventListener("keydown",keys)}},[open]);
  const item="block border-b border-black/10 px-5 py-3.5 text-sm font-black uppercase tracking-[.08em]";
  return <div className="relative z-50 lg:hidden">
    {open&&<button type="button" aria-label="Close academy menu" onClick={()=>setOpen(false)} className="fixed inset-0 z-40 cursor-default bg-black/25"/>}
    <button ref={triggerRef} type="button" aria-label={open?"Close academy menu":"Open academy menu"} aria-expanded={open} aria-controls="academy-mobile-navigation" onClick={()=>setOpen(value=>!value)} className={`relative z-[60] grid h-11 w-11 place-items-center rounded-md border transition ${open?"text-white":"border-black/15 bg-white text-black"}`} style={open?{backgroundColor:primary,borderColor:primary}:undefined}><span className="grid gap-1.5" aria-hidden="true"><span className={`h-0.5 w-5 transition ${open?"translate-y-2 rotate-45 bg-white":"bg-black"}`}/><span className={`h-0.5 w-5 transition ${open?"opacity-0":"bg-black"}`}/><span className={`h-0.5 w-5 transition ${open?"-translate-y-2 -rotate-45 bg-white":"bg-black"}`}/></span></button>
    {open&&<nav ref={navRef} id="academy-mobile-navigation" className="fixed inset-x-0 top-[76px] z-[60] max-h-[calc(100dvh-76px)] overflow-y-auto border-t-4 bg-white shadow-2xl" style={{borderTopColor:primary}} aria-label="Academy mobile navigation">
      <div className="grid gap-px bg-black/10">
        <div className="bg-white p-2"><p className="px-5 py-2 text-[10px] font-black uppercase tracking-[.18em] text-black/35">Learn</p>{canManageTraining&&<><Link onClick={()=>setOpen(false)} href={`${portal}/getting-started`} className={item}>Launch Guide</Link><Link onClick={()=>setOpen(false)} href={`${portal}/products`} className={item}>Products</Link><Link onClick={()=>setOpen(false)} href={portal} className={item}>Quizzes</Link><Link onClick={()=>setOpen(false)} href={`${portal}/courses`} className={item}>Courses</Link><Link onClick={()=>setOpen(false)} href={`${portal}/templates`} className={item}>Templates</Link></>}<Link onClick={()=>setOpen(false)} href={`${portal}/dealer-programs`} className={item}>Dealer Offers</Link><Link onClick={()=>setOpen(false)} href={`${portal}/my-training`} className={item} style={{color:primary}}>My Training</Link><Link onClick={()=>setOpen(false)} href="/academies" className={item} style={{color:primary}}>My Academies</Link><Link onClick={()=>setOpen(false)} href={`${portal}/certificates`} className={item} style={{color:primary}}>My Certificates</Link><Link onClick={()=>setOpen(false)} href={`${portal}/rewards`} className={item} style={{color:primary}}>My Rewards</Link></div>
        <div className="bg-white p-2"><p className="px-5 py-2 text-[10px] font-black uppercase tracking-[.18em] text-black/35">Manage</p>{canManageTraining&&<><Link onClick={()=>setOpen(false)} href={`${portal}/retailers`} className={item}>Retailers</Link><Link onClick={()=>setOpen(false)} href={`${portal}/assignments`} className={item}>Assignments</Link><Link onClick={()=>setOpen(false)} href={`${portal}/reviews`} className={item}>Review Queue</Link><Link onClick={()=>setOpen(false)} href={`${portal}/programs`} className={item}>Manage Offers</Link><Link onClick={()=>setOpen(false)} href={`${portal}/certifications`} className={item}>Certifications</Link><Link onClick={()=>setOpen(false)} href={`${portal}/notifications`} className={item}>Notifications</Link><Link onClick={()=>setOpen(false)} href={`${portal}/rewards/manage`} className={item}>Rewards</Link></>}{canViewReports&&<Link onClick={()=>setOpen(false)} href={`${portal}/reports`} className={item}>Reports</Link>}{canManageBrand&&<><Link onClick={()=>setOpen(false)} href={`${portal}/users`} className={item}>Users</Link><Link onClick={()=>setOpen(false)} href={`${portal}/settings/branding`} className={item} style={{color:primary}}>Brand Studio</Link></>}</div>
      </div>
      <form action={`/logout?brand=${encodeURIComponent(slug)}`} method="post" className="p-3"><button className="min-h-11 w-full rounded-md bg-black text-xs font-black uppercase tracking-[.1em] text-white">Sign out</button></form>
    </nav>}
  </div>
}
