import Image from "next/image";
import Link from "next/link";
import type { LandingSection, ManufacturerBrand, PublicLandingExperience } from "@/lib/branding";
import { AnnouncementBar, ProductCarousel } from "./landing-experience";

const validHex=(value:string)=>/^#[0-9a-f]{6}$/i.test(value);
const isDark=(hex:string)=>{if(!validHex(hex))return false;const[r,g,b]=[hex.slice(1,3),hex.slice(3,5),hex.slice(5,7)].map(value=>parseInt(value,16));return (r*299+g*587+b*114)/1000<145};
const academyLink=(value:unknown,brand:ManufacturerBrand)=>{const link=String(value??"").trim();if(!link)return `/login?brand=${encodeURIComponent(brand.slug)}`;if(link==="/app"||link.startsWith("/app/"))return `/m/${brand.slug}${link}`;if(link==="/login")return `/login?brand=${encodeURIComponent(brand.slug)}`;if(link.startsWith("/login?")){const params=new URLSearchParams(link.slice(7));if(!params.has("brand"))params.set("brand",brand.slug);return `/login?${params.toString()}`;}return link};
const paletteColor=(choice:unknown,brand:ManufacturerBrand,custom?:unknown)=>choice==="primary"?brand.primary_color:choice==="secondary"?brand.secondary_color:choice==="black"?"#141414":choice==="white"?"#FFFFFF":choice==="neutral"?"#EFEFEC":choice==="custom"&&validHex(String(custom??""))?String(custom):"#FFFFFF";
const sectionColors=(config:LandingSection["config"],brand:ManufacturerBrand,fallback:"white"|"neutral"|"black"|"primary"="white")=>{
  const legacy=config.style==="dark"?"black":config.style==="neutral"?"neutral":fallback;
  const background=paletteColor(config.background??legacy,brand,config.custom_bg);
  const text=config.text_tone==="light"?"#FFFFFF":config.text_tone==="dark"?"#141414":isDark(background)?"#FFFFFF":"#141414";
  const accent=paletteColor(config.accent_color??"primary",brand);
  const button=paletteColor(config.button_color??"primary",brand);
  return{background,text,accent,button,buttonText:isDark(button)?"#FFFFFF":"#141414"};
};

export default function LandingPageSections({ sections, brand, products }: { sections:LandingSection[]; brand:ManufacturerBrand; products:PublicLandingExperience["products"] }) {
  return <>{sections.filter((section)=>section.enabled).map((section) => {
    const config = section.config;
    if (section.type === "announcement") { const announcements=String(config.messages??"").split("\n").map((line)=>{const [text,...url]=line.split("|");return{text:text.trim(),url:url.join("|").trim()||undefined}}).filter((item)=>item.text); return <AnnouncementBar key={section.id} announcements={announcements} color={brand.primary_color}/>; }
    if (section.type === "hero") {
      const imageUrl=String(config.image_url??"");
      const alignment=config.alignment === "center" ? "center" : "left";
      const height=config.height === "compact" ? "min-h-[420px]" : config.height === "full" ? "min-h-[calc(100vh-80px)]" : "min-h-[620px]";
      const overlay=Math.min(90,Math.max(0,Number(config.overlay??60)))/100;
      const link=academyLink(config.link_url,brand);
      return <section key={section.id} className={`relative isolate flex ${height} items-center overflow-hidden px-5 py-20 text-white lg:px-8`} style={{backgroundColor:brand.secondary_color}}>{imageUrl&&<><Image src={imageUrl} alt="" fill className="-z-20 object-cover" unoptimized/><div className="absolute inset-0 -z-10 bg-black" style={{opacity:overlay}}/></>}<div className={`mx-auto w-full max-w-7xl ${alignment === "center" ? "text-center" : "text-left"}`}>{String(config.eyebrow??`${brand.name} learning center`) && <p className="text-sm font-extrabold uppercase italic tracking-[.2em]" style={{color:brand.primary_color}}>{String(config.eyebrow??`${brand.name} learning center`)}</p>}<h1 className={`mt-5 text-5xl font-extrabold uppercase leading-[.94] tracking-[-.04em] sm:text-6xl lg:text-7xl ${alignment === "center" ? "mx-auto max-w-5xl" : "max-w-5xl"}`}>{String(config.headline??"")}</h1><p className={`mt-7 max-w-2xl text-lg leading-8 text-white/80 ${alignment === "center" ? "mx-auto" : ""}`}>{String(config.description??"")}</p><Link href={link} className="mt-9 inline-flex min-h-14 items-center px-7 font-extrabold uppercase text-white" style={{backgroundColor:brand.primary_color}}>{String(config.button_text??"Start training")}</Link></div></section>;
    }
    if (section.type === "carousel") { const selected=String(config.mode??"category")==="manual" ? products.filter((product)=>Array.isArray(config.product_ids)&&config.product_ids.includes(product.id)) : products.filter((product)=>product.category_name===String(config.category??"")); return <ProductCarousel key={section.id} products={selected} manufacturerSlug={brand.slug} color={brand.primary_color} autoplay={Boolean(config.autoplay)} title={String(config.title??"Featured products")}/>; }
    if (section.type === "product_showcase") {
      const ids=Array.isArray(config.product_ids)?config.product_ids:[],selected=ids.map(id=>products.find(product=>product.id===id)).filter((product):product is PublicLandingExperience["products"][number]=>Boolean(product));
      const colors=sectionColors(config,brand,config.style==="dark"?"black":config.style==="neutral"?"neutral":"white");
      return <section key={section.id} className="px-5 py-20 lg:px-8 lg:py-24" style={{backgroundColor:colors.background,color:colors.text}}><div className="mx-auto max-w-7xl text-center">{config.eyebrow&&<p className="text-sm font-extrabold uppercase italic tracking-[.2em]" style={{color:colors.accent}}>{String(config.eyebrow)}</p>}<h2 className="mt-3 text-4xl font-extrabold uppercase sm:text-5xl">{String(config.title??"Products worth knowing")}</h2>{config.description&&<p className="mx-auto mt-4 max-w-2xl text-lg opacity-60">{String(config.description)}</p>}<div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{selected.map(product=><Link key={product.id} href={`/m/${brand.slug}/products/${product.slug}`} className="group overflow-hidden border text-left transition hover:-translate-y-1" style={{borderColor:`${colors.text}26`,color:colors.text,backgroundColor:`${colors.text}0A`}}><div className="aspect-square overflow-hidden bg-white">{product.image?<img src={product.image} alt="" className="h-full w-full object-contain p-4 transition duration-300 group-hover:scale-105"/>:<div className="grid h-full place-items-center text-xs font-bold uppercase text-black/30">No image</div>}</div><div className="p-5"><span className="text-[10px] font-extrabold uppercase tracking-wide opacity-45">{product.category_name||"Product knowledge"}</span><h3 className="mt-2 text-lg font-extrabold uppercase leading-tight">{product.name}</h3><p className="mt-3 text-sm leading-6 opacity-55">{product.tagline||"Explore features, applications, and selling points."}</p><span className="mt-5 inline-block text-xs font-extrabold uppercase" style={{color:colors.accent}}>Learn product →</span></div></Link>)}</div>{!selected.length&&<p className="mt-10 border border-dashed p-8 opacity-45" style={{borderColor:`${colors.text}26`}}>Select products in Brand Studio to populate this section.</p>}</div></section>;
    }
    if (section.type === "category_explorer") {
      const selectedCategories=Array.isArray(config.categories)?config.categories:[],categories=selectedCategories.map(name=>({name,product:products.find(product=>(product.category_name||"Uncategorized")===name)})).filter(item=>item.product);
      const colors=sectionColors(config,brand,config.style==="dark"?"black":config.style==="neutral"?"neutral":"white");
      return <section key={section.id} className="overflow-hidden px-5 py-20 lg:px-8 lg:py-24" style={{backgroundColor:colors.background,color:colors.text}}><div className="mx-auto max-w-7xl text-center">{config.eyebrow&&<p className="text-sm font-extrabold uppercase italic tracking-[.2em]" style={{color:colors.accent}}>{String(config.eyebrow)}</p>}<h2 className="mt-3 text-4xl font-extrabold uppercase sm:text-5xl">{String(config.title??"Explore by category")}</h2>{config.description&&<p className="mx-auto mt-4 max-w-3xl text-lg opacity-60">{String(config.description)}</p>}<div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.map(({name,product})=><Link key={name} href={`/m/${brand.slug}/products/${product!.slug}`} className="group relative isolate min-h-72 overflow-hidden bg-[#222] text-left text-white">{product!.image&&<img src={product!.image} alt="" className="absolute inset-0 -z-20 h-full w-full object-cover transition duration-500 group-hover:scale-105"/>}<div className="absolute inset-0 -z-10 bg-gradient-to-t from-black via-black/20 to-transparent"/><h3 className="absolute inset-x-0 bottom-0 border-l-4 p-6 text-2xl font-extrabold uppercase leading-tight" style={{borderColor:colors.accent}}>{name}</h3></Link>)}</div>{!categories.length&&<p className="mt-10 border border-dashed p-8 opacity-45" style={{borderColor:`${colors.text}26`}}>Choose product categories in Brand Studio to populate this section.</p>}</div></section>;
    }
    if (section.type === "split_feature") {
      const colors=sectionColors(config,brand,config.style==="dark"?"black":config.style==="neutral"?"neutral":"white");
      const panels=[{title:String(config.left_title??""),description:String(config.left_description??""),image:String(config.image_url??""),link:String(config.left_link??"")},{title:String(config.right_title??""),description:String(config.right_description??""),image:String(config.image_url_2??""),link:String(config.right_link??"")}];
      return <section key={section.id} className="grid gap-px lg:grid-cols-2" style={{backgroundColor:colors.background,color:colors.text}}>{panels.map((panel,index)=>{const content=<article className="group relative isolate flex min-h-[420px] items-end overflow-hidden p-8 text-white lg:p-12">{panel.image&&<img src={panel.image} alt="" className="absolute inset-0 -z-20 h-full w-full object-cover transition duration-500 group-hover:scale-[1.02]"/>}<div className="absolute inset-0 -z-10 bg-gradient-to-t from-black via-black/35 to-black/10"/><div><h2 className="max-w-xl text-3xl font-extrabold uppercase sm:text-4xl">{panel.title}</h2><p className="mt-4 max-w-xl text-lg leading-8 text-white/75">{panel.description}</p>{panel.link&&<span className="mt-6 inline-block text-xs font-extrabold uppercase" style={{color:colors.accent}}>Explore →</span>}</div></article>;return panel.link?<Link key={index} href={academyLink(panel.link,brand)}>{content}</Link>:<div key={index}>{content}</div>})}</section>;
    }
    if (section.type === "dealer_program" || section.type === "featured_training") {
      const colors=sectionColors(config,brand,config.style==="dark"?"black":config.style==="neutral"?"neutral":"white"),image=String(config.image_url??""),link=academyLink(config.link_url,brand);
      return <section key={section.id} className="px-5 py-20 lg:px-8 lg:py-24" style={{backgroundColor:colors.background,color:colors.text}}><div className="mx-auto grid max-w-7xl overflow-hidden border lg:grid-cols-2" style={{borderColor:`${colors.text}26`}}><div className="relative min-h-80" style={{backgroundColor:`${colors.text}0A`}}>{image?<img src={image} alt="" className="absolute inset-0 h-full w-full object-cover"/>:<div className="grid h-full min-h-80 place-items-center text-xs font-extrabold uppercase opacity-25">{section.type==="dealer_program"?"Dealer opportunity":"Featured training"}</div>}</div><div className="flex flex-col justify-center p-8 lg:p-12">{config.eyebrow&&<p className="text-sm font-extrabold uppercase italic tracking-[.2em]" style={{color:colors.accent}}>{String(config.eyebrow)}</p>}<h2 className="mt-4 text-4xl font-extrabold uppercase leading-tight sm:text-5xl">{String(config.title??"")}</h2><p className="mt-5 text-lg leading-8 opacity-65">{String(config.description??"")}</p><Link href={link} className="mt-8 inline-flex min-h-14 w-fit items-center px-7 font-extrabold uppercase" style={{backgroundColor:colors.button,color:colors.buttonText}}>{String(config.button_text??"Explore")}</Link></div></div></section>;
    }
    if (section.type === "benefits") { const colors=sectionColors(config,brand,"white"),cards=[[String(config.card_1_title??"Product Training"),String(config.card_1_description??`Understand ${brand.name} products, features, and customer benefits.`)],[String(config.card_2_title??"Knowledge Checks"),String(config.card_2_description??"Reinforce the information that matters at the point of sale.")],[String(config.card_3_title??"Progress Tracking"),String(config.card_3_description??"Give teams visibility into training and completion.")]]; return <section key={section.id} className="px-5 py-20 lg:px-8 lg:py-24" style={{backgroundColor:colors.background,color:colors.text}}><div className="mx-auto max-w-7xl">{String(config.eyebrow??"Built for product experts")&&<p className="text-sm font-extrabold uppercase italic tracking-[.2em]" style={{color:colors.accent}}>{String(config.eyebrow??"Built for product experts")}</p>}<h2 className="mt-4 max-w-3xl text-4xl font-extrabold uppercase sm:text-5xl">{String(config.title??"Build product confidence")}</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{cards.map(([title,copy],index)=><article key={index} className="border p-7" style={{borderColor:`${colors.text}26`,backgroundColor:`${colors.text}08`}}><span className="grid h-10 w-10 place-items-center text-xs font-black" style={{backgroundColor:colors.accent,color:isDark(colors.accent)?"#FFFFFF":"#141414"}}>0{index+1}</span><h3 className="mt-6 text-xl font-extrabold uppercase">{title}</h3><p className="mt-3 leading-7 opacity-60">{copy}</p></article>)}</div></div></section>; }
    if (section.type === "banner" && config.image_url) { const image=<img src={String(config.image_url)} alt={String(config.alt_text??`${brand.name} promotion`)} className="h-auto w-full object-cover"/>; return <section key={section.id} className="mx-auto max-w-7xl px-5 py-12 lg:px-8">{config.link_url?<a href={academyLink(config.link_url,brand)}>{image}</a>:image}</section>; }
    if (section.type === "cta") { const colors=sectionColors(config,brand,"primary"),centered=config.alignment === "center"; const link=academyLink(config.link_url,brand); return <section key={section.id} className="px-5 py-20 lg:px-8" style={{backgroundColor:colors.background,color:colors.text}}><div className={`mx-auto max-w-7xl ${centered?"text-center":"flex flex-col justify-between gap-8 lg:flex-row lg:items-end"}`}><div>{config.eyebrow&&<p className="mb-4 text-sm font-extrabold uppercase italic tracking-[.2em]" style={{color:colors.accent}}>{String(config.eyebrow)}</p>}<h2 className={`text-4xl font-extrabold uppercase sm:text-5xl ${centered?"mx-auto max-w-4xl":"max-w-4xl"}`}>{String(config.headline??"")}</h2><p className={`mt-4 max-w-2xl text-lg opacity-70 ${centered?"mx-auto":""}`}>{String(config.description??"")}</p></div><Link href={link} className={`${centered?"mt-8":""} inline-flex min-h-14 shrink-0 items-center px-7 font-extrabold uppercase`} style={{backgroundColor:colors.button,color:colors.buttonText}}>{String(config.button_text??"Start training")}</Link></div></section>; }
    return null;
  })}</>;
}
