import Image from "next/image";
import Link from "next/link";
import type { LandingSection, ManufacturerBrand, PublicLandingExperience } from "@/lib/branding";
import { AnnouncementBar, ProductCarousel } from "./landing-experience";

export default function LandingPageSections({ sections, brand, products }: { sections:LandingSection[]; brand:ManufacturerBrand; products:PublicLandingExperience["products"] }) {
  return <>{sections.filter((section)=>section.enabled).map((section) => {
    const config = section.config;
    if (section.type === "announcement") { const announcements=String(config.messages??"").split("\n").map((line)=>{const [text,...url]=line.split("|");return{text:text.trim(),url:url.join("|").trim()||undefined}}).filter((item)=>item.text); return <AnnouncementBar key={section.id} announcements={announcements} color={brand.primary_color}/>; }
    if (section.type === "hero") return <section key={section.id} className="relative isolate overflow-hidden px-5 py-24 text-white lg:px-8 lg:py-32" style={{backgroundColor:brand.secondary_color}}>{brand.hero_image_url&&<><Image src={brand.hero_image_url} alt="" fill className="-z-20 object-cover" unoptimized/><div className="absolute inset-0 -z-10 bg-black/60"/></>}<div className="mx-auto max-w-7xl"><p className="text-sm font-extrabold uppercase italic tracking-[.2em]" style={{color:brand.primary_color}}>{brand.name} learning center</p><h1 className="mt-5 max-w-5xl text-5xl font-extrabold uppercase leading-[.94] tracking-[-.04em] sm:text-6xl lg:text-7xl">{String(config.headline??"")}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/80">{String(config.description??"")}</p><Link href={`/login?brand=${encodeURIComponent(brand.slug)}`} className="mt-9 inline-flex min-h-14 items-center px-7 font-extrabold uppercase text-white" style={{backgroundColor:brand.primary_color}}>{String(config.button_text??"Start training")}</Link></div></section>;
    if (section.type === "carousel") { const selected=String(config.mode??"category")==="manual" ? products.filter((product)=>Array.isArray(config.product_ids)&&config.product_ids.includes(product.id)) : products.filter((product)=>product.category_name===String(config.category??"")); return <ProductCarousel key={section.id} products={selected} manufacturerSlug={brand.slug} color={brand.primary_color} autoplay={Boolean(config.autoplay)} title={String(config.title??"Featured products")}/>; }
    if (section.type === "benefits") return <section key={section.id} className="px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><p className="text-sm font-extrabold uppercase italic tracking-[.2em]" style={{color:brand.primary_color}}>Built for product experts</p><h2 className="mt-4 max-w-3xl text-4xl font-extrabold uppercase sm:text-5xl">{String(config.title??"Build product confidence")}</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{[["Product Training",`Understand ${brand.name} products, features, and customer benefits.`],["Knowledge Checks","Reinforce the information that matters at the point of sale."],["Progress Tracking","Give teams visibility into training and completion."]].map(([title,copy],index)=><article key={title} className="border border-black/10 p-7"><span className="grid h-10 w-10 place-items-center text-xs font-black text-white" style={{backgroundColor:index?brand.secondary_color:brand.primary_color}}>0{index+1}</span><h3 className="mt-6 text-xl font-extrabold uppercase">{title}</h3><p className="mt-3 leading-7 text-black/55">{copy}</p></article>)}</div></div></section>;
    if (section.type === "banner" && config.image_url) { const image=<img src={String(config.image_url)} alt={`${brand.name} promotion`} className="h-auto w-full object-cover"/>; return <section key={section.id} className="mx-auto max-w-7xl px-5 py-12 lg:px-8">{config.link_url?<a href={String(config.link_url)}>{image}</a>:image}</section>; }
    if (section.type === "cta") return <section key={section.id} className="px-5 py-20 text-white lg:px-8" style={{backgroundColor:brand.primary_color}}><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><h2 className="max-w-4xl text-4xl font-extrabold uppercase sm:text-5xl">{String(config.headline??"")}</h2><p className="mt-4 max-w-2xl text-lg text-white/80">{String(config.description??"")}</p></div><Link href={String(config.link_url??`/login?brand=${brand.slug}`)} className="inline-flex min-h-14 shrink-0 items-center bg-black px-7 font-extrabold uppercase text-white">{String(config.button_text??"Start training")}</Link></div></section>;
    return null;
  })}</>;
}
