import Image from "next/image";
import Link from "next/link";
import type { LandingSection, ManufacturerBrand, PublicLandingExperience } from "@/lib/branding";
import { AnnouncementBar, ProductCarousel } from "./landing-experience";

export default function LandingPageSections({ sections, brand, products }: { sections:LandingSection[]; brand:ManufacturerBrand; products:PublicLandingExperience["products"] }) {
  return <>{sections.filter((section)=>section.enabled).map((section) => {
    const config = section.config;
    if (section.type === "announcement") { const announcements=String(config.messages??"").split("\n").map((line)=>{const [text,...url]=line.split("|");return{text:text.trim(),url:url.join("|").trim()||undefined}}).filter((item)=>item.text); return <AnnouncementBar key={section.id} announcements={announcements} color={brand.primary_color}/>; }
    if (section.type === "hero") {
      const imageUrl=String(config.image_url??"");
      const alignment=config.alignment === "center" ? "center" : "left";
      const height=config.height === "compact" ? "min-h-[420px]" : config.height === "full" ? "min-h-[calc(100vh-80px)]" : "min-h-[620px]";
      const overlay=Math.min(90,Math.max(0,Number(config.overlay??60)))/100;
      const link=String(config.link_url??"") || `/login?brand=${encodeURIComponent(brand.slug)}`;
      return <section key={section.id} className={`relative isolate flex ${height} items-center overflow-hidden px-5 py-20 text-white lg:px-8`} style={{backgroundColor:brand.secondary_color}}>{imageUrl&&<><Image src={imageUrl} alt="" fill className="-z-20 object-cover" unoptimized/><div className="absolute inset-0 -z-10 bg-black" style={{opacity:overlay}}/></>}<div className={`mx-auto w-full max-w-7xl ${alignment === "center" ? "text-center" : "text-left"}`}>{String(config.eyebrow??`${brand.name} learning center`) && <p className="text-sm font-extrabold uppercase italic tracking-[.2em]" style={{color:brand.primary_color}}>{String(config.eyebrow??`${brand.name} learning center`)}</p>}<h1 className={`mt-5 text-5xl font-extrabold uppercase leading-[.94] tracking-[-.04em] sm:text-6xl lg:text-7xl ${alignment === "center" ? "mx-auto max-w-5xl" : "max-w-5xl"}`}>{String(config.headline??"")}</h1><p className={`mt-7 max-w-2xl text-lg leading-8 text-white/80 ${alignment === "center" ? "mx-auto" : ""}`}>{String(config.description??"")}</p><Link href={link} className="mt-9 inline-flex min-h-14 items-center px-7 font-extrabold uppercase text-white" style={{backgroundColor:brand.primary_color}}>{String(config.button_text??"Start training")}</Link></div></section>;
    }
    if (section.type === "carousel") { const selected=String(config.mode??"category")==="manual" ? products.filter((product)=>Array.isArray(config.product_ids)&&config.product_ids.includes(product.id)) : products.filter((product)=>product.category_name===String(config.category??"")); return <ProductCarousel key={section.id} products={selected} manufacturerSlug={brand.slug} color={brand.primary_color} autoplay={Boolean(config.autoplay)} title={String(config.title??"Featured products")}/>; }
    if (section.type === "benefits") { const cards=[[String(config.card_1_title??"Product Training"),String(config.card_1_description??`Understand ${brand.name} products, features, and customer benefits.`)],[String(config.card_2_title??"Knowledge Checks"),String(config.card_2_description??"Reinforce the information that matters at the point of sale.")],[String(config.card_3_title??"Progress Tracking"),String(config.card_3_description??"Give teams visibility into training and completion.")]]; return <section key={section.id} className="px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl">{String(config.eyebrow??"Built for product experts")&&<p className="text-sm font-extrabold uppercase italic tracking-[.2em]" style={{color:brand.primary_color}}>{String(config.eyebrow??"Built for product experts")}</p>}<h2 className="mt-4 max-w-3xl text-4xl font-extrabold uppercase sm:text-5xl">{String(config.title??"Build product confidence")}</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{cards.map(([title,copy],index)=><article key={index} className="border border-black/10 p-7"><span className="grid h-10 w-10 place-items-center text-xs font-black text-white" style={{backgroundColor:index?brand.secondary_color:brand.primary_color}}>0{index+1}</span><h3 className="mt-6 text-xl font-extrabold uppercase">{title}</h3><p className="mt-3 leading-7 text-black/55">{copy}</p></article>)}</div></div></section>; }
    if (section.type === "banner" && config.image_url) { const image=<img src={String(config.image_url)} alt={String(config.alt_text??`${brand.name} promotion`)} className="h-auto w-full object-cover"/>; return <section key={section.id} className="mx-auto max-w-7xl px-5 py-12 lg:px-8">{config.link_url?<a href={String(config.link_url)}>{image}</a>:image}</section>; }
    if (section.type === "cta") { const centered=config.alignment === "center"; const link=String(config.link_url??"")||`/login?brand=${brand.slug}`; return <section key={section.id} className="px-5 py-20 text-white lg:px-8" style={{backgroundColor:brand.primary_color}}><div className={`mx-auto max-w-7xl ${centered?"text-center":"flex flex-col justify-between gap-8 lg:flex-row lg:items-end"}`}><div>{config.eyebrow&&<p className="mb-4 text-sm font-extrabold uppercase italic tracking-[.2em] text-white/65">{String(config.eyebrow)}</p>}<h2 className={`text-4xl font-extrabold uppercase sm:text-5xl ${centered?"mx-auto max-w-4xl":"max-w-4xl"}`}>{String(config.headline??"")}</h2><p className={`mt-4 max-w-2xl text-lg text-white/80 ${centered?"mx-auto":""}`}>{String(config.description??"")}</p></div><Link href={link} className={`${centered?"mt-8":""} inline-flex min-h-14 shrink-0 items-center bg-black px-7 font-extrabold uppercase text-white`}>{String(config.button_text??"Start training")}</Link></div></section>; }
    return null;
  })}</>;
}
