import Link from "next/link";

export function MarketingHeader() {
  return <header className="sticky top-0 z-40 border-b border-black/10 bg-[#f4f1eb]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4 lg:px-8"><Link href="/" className="text-2xl font-black uppercase tracking-[-0.05em]">Jobber<span className="text-[#ff4f1f]">Train</span></Link><nav className="hidden items-center gap-7 md:flex" aria-label="Public navigation"><Link href="/#how-it-works" className="text-xs font-extrabold uppercase tracking-[.12em] hover:text-[#ff4f1f]">How it works</Link><Link href="/#features" className="text-xs font-extrabold uppercase tracking-[.12em] hover:text-[#ff4f1f]">Features</Link><Link href="/pricing" className="text-xs font-extrabold uppercase tracking-[.12em] hover:text-[#ff4f1f]">Pricing</Link><Link href="/contact" className="text-xs font-extrabold uppercase tracking-[.12em] hover:text-[#ff4f1f]">Contact</Link></nav><div className="flex items-center gap-2 sm:gap-3"><Link href="/login?next=/platform" className="hidden px-3 py-3 text-xs font-extrabold uppercase tracking-wide sm:block">Sign in</Link><Link href="/contact" className="bg-black px-4 py-3 text-xs font-extrabold uppercase tracking-wide text-white transition hover:bg-[#ff4f1f] sm:px-5">Discuss a pilot</Link></div></div></header>;
}

export function MarketingFooter() {
  return <footer className="bg-[#101010] px-5 py-10 text-white lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-7 lg:flex-row lg:items-center"><div><Link href="/" className="text-2xl font-black uppercase tracking-[-0.05em]">Jobber<span className="text-[#ff4f1f]">Train</span></Link><p className="mt-2 text-sm text-white/40">Manufacturer product knowledge for the last mile of the sale.</p></div><div className="flex flex-wrap gap-5 text-xs font-extrabold uppercase tracking-wide text-white/55"><Link href="/pricing" className="hover:text-white">Pricing</Link><Link href="/contact" className="hover:text-white">Contact</Link><Link href="/m/gen-y-hitch" className="hover:text-white">Live academy</Link><Link href="/login?next=/platform" className="hover:text-white">Sign in</Link></div><span className="text-xs text-white/35">© {new Date().getFullYear()} JobberTrain</span></div></footer>;
}
