"use client";

import { useState } from "react";
import type { LandingSection } from "@/lib/branding";

export type BuilderSection = LandingSection;
type ProductOption = { product_id:string; name:string; model_sku:string|null; category_name:string|null; is_family:boolean; variation_count:number };

const labels: Record<BuilderSection["type"], string> = { announcement:"Announcement bar", hero:"Hero", carousel:"Product carousel", benefits:"Benefits cards", banner:"Promotional banner", cta:"Call to action", product_showcase:"Product showcase", category_explorer:"Category explorer", split_feature:"Split image feature", dealer_program:"Featured dealer program", featured_training:"Featured training" };
const newSection = (type: BuilderSection["type"]): BuilderSection => ({ id: crypto.randomUUID(), type, enabled:true, config: type === "carousel" ? { title:"Featured products", mode:"manual", product_ids:[], autoplay:true } : type === "product_showcase" ? { eyebrow:"Popular with dealers", title:"Products worth knowing", description:"Explore the products customers ask for most.", product_ids:[], style:"dark" } : type === "category_explorer" ? { eyebrow:"Explore the line", title:"Shop by category", description:"Find the right product knowledge for every customer application.", categories:[], style:"dark" } : type === "split_feature" ? { left_title:"Built for the real world", left_description:"Tell the story behind the products your retailers sell.", left_link:"", right_title:"Made to perform", right_description:"Highlight technology, manufacturing, service, or warranty advantages.", right_link:"", image_url:"", image_url_2:"", style:"dark" } : type === "dealer_program" ? { eyebrow:"Dealer opportunity", title:"Programs built to help you sell", description:"Explore private stocking, display, and promotional programs available to eligible dealers.", button_text:"View dealer programs", link_url:"/app/dealer-programs", image_url:"", style:"dark" } : type === "featured_training" ? { eyebrow:"Featured training", title:"Know the product. Make the recommendation.", description:"Build confidence with focused product training designed for the sales counter.", button_text:"Start training", link_url:"/app/my-training", image_url:"", style:"light" } : type === "hero" ? { eyebrow:"Learning center", headline:"Product knowledge that drives sales.", description:"Learn the products and build confidence with every customer.", button_text:"Start training", link_url:"", image_url:"", overlay:"60", alignment:"left", height:"large" } : type === "announcement" ? { messages:"New training is now available" } : type === "benefits" ? { eyebrow:"Built for product experts", title:"Build product confidence", card_1_title:"Product Training", card_1_description:"Understand products, features, and customer benefits.", card_2_title:"Knowledge Checks", card_2_description:"Reinforce the information that matters at the point of sale.", card_3_title:"Progress Tracking", card_3_description:"Give teams visibility into training and completion." } : type === "banner" ? { image_url:"", link_url:"", alt_text:"Promotional banner" } : { eyebrow:"Continue learning", headline:"Ready to start training?", description:"Sign in to continue your learning.", button_text:"Start training", link_url:"/login", alignment:"left" } });

function CarouselProductPicker({ section, products, updateConfig }: { section:BuilderSection; products:ProductOption[]; updateConfig:(id:string,key:string,value:string|string[]|boolean)=>void }) {
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("all");
  const [type, setType] = useState("all");
  const ids = Array.isArray(section.config.product_ids) ? section.config.product_ids : [];
  const selected = ids.map((id) => products.find((product) => product.product_id === id)).filter((product): product is ProductOption => Boolean(product));
  const categories = Array.from(new Set(products.map((product) => product.category_name || "Uncategorized"))).sort();
  const query = search.trim().toLowerCase();
  const filtered = products.filter((product) => {
    const matchesSearch = !query || [product.name, product.model_sku, product.category_name].some((value) => value?.toLowerCase().includes(query));
    const matchesCategory = category === "all" || (product.category_name || "Uncategorized") === category;
    const matchesType = type === "all" || (type === "family" ? product.is_family : !product.is_family);
    return matchesSearch && matchesCategory && matchesType;
  });
  const toggle = (id:string) => updateConfig(section.id, "product_ids", ids.includes(id) ? ids.filter((item) => item !== id) : [...ids, id]);
  const moveSelected = (index:number, direction:number) => {
    const target = index + direction;
    if (target < 0 || target >= ids.length) return;
    const next = [...ids];
    [next[index], next[target]] = [next[target], next[index]];
    updateConfig(section.id, "product_ids", next);
  };

  return <div className="sm:col-span-2">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-bold">Choose products and families</p><p className="mt-1 text-sm text-black/45">Carousel order follows the selected list below.</p></div><span className="rounded-full bg-black/5 px-3 py-1 text-xs font-extrabold">{ids.length} selected</span></div>
    {selected.length > 0 && <div className="mt-4 border border-black/15 bg-[#f7f7f5] p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-extrabold uppercase tracking-wide text-black/45">Selected carousel order</p><button type="button" onClick={() => updateConfig(section.id, "product_ids", [])} className="text-xs font-bold uppercase text-red-700 hover:underline">Clear all</button></div><div className="mt-3 grid gap-2">{selected.map((product,index) => <div key={product.product_id} className="flex items-center gap-3 border border-black/10 bg-white p-3"><span className="grid h-7 w-7 shrink-0 place-items-center bg-black text-xs font-black text-white">{index+1}</span><div className="min-w-0 flex-1"><b className="block truncate text-sm">{product.name}</b><span className="block truncate text-xs text-black/45">{product.is_family ? `Family · ${product.variation_count} variations` : "Product"}{product.model_sku ? ` · ${product.model_sku}` : ""}</span></div><button type="button" disabled={index===0} onClick={() => moveSelected(index,-1)} aria-label={`Move ${product.name} earlier`} className="grid h-8 w-8 place-items-center font-black disabled:opacity-20">↑</button><button type="button" disabled={index===selected.length-1} onClick={() => moveSelected(index,1)} aria-label={`Move ${product.name} later`} className="grid h-8 w-8 place-items-center font-black disabled:opacity-20">↓</button><button type="button" onClick={() => toggle(product.product_id)} aria-label={`Remove ${product.name}`} className="grid h-8 w-8 place-items-center text-xl text-red-700">×</button></div>)}</div></div>}
    <div className="mt-4 grid gap-3 md:grid-cols-[minmax(0,1fr)_180px_160px]"><label className="grid gap-1 text-xs font-bold uppercase text-black/50">Search<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Name, SKU, or category" className="min-h-11 border border-black/20 px-3 text-sm font-normal normal-case text-black outline-none focus:border-black" /></label><label className="grid gap-1 text-xs font-bold uppercase text-black/50">Category<select value={category} onChange={(event) => setCategory(event.target.value)} className="min-h-11 border border-black/20 bg-white px-3 text-sm font-normal normal-case text-black"><option value="all">All categories</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label className="grid gap-1 text-xs font-bold uppercase text-black/50">Type<select value={type} onChange={(event) => setType(event.target.value)} className="min-h-11 border border-black/20 bg-white px-3 text-sm font-normal normal-case text-black"><option value="all">All types</option><option value="family">Families</option><option value="product">Products</option></select></label></div>
    {products.length ? <><p className="mt-4 text-xs font-bold uppercase text-black/40">{filtered.length} result{filtered.length === 1 ? "" : "s"}</p><div className="mt-2 grid max-h-96 gap-2 overflow-y-auto pr-1 sm:grid-cols-2">{filtered.map((product) => { const checked=ids.includes(product.product_id); return <label key={product.product_id} className={`flex cursor-pointer items-start gap-3 border p-4 transition ${checked?"border-black bg-black text-white":"border-black/10 hover:border-black/40"}`}><input type="checkbox" checked={checked} onChange={() => toggle(product.product_id)} className="mt-1"/><span className="min-w-0"><b className="block text-sm">{product.name}</b><span className={`mt-1 block text-xs ${checked?"text-white/60":"text-black/45"}`}>{product.category_name || "Uncategorized"}{product.is_family ? ` · Family · ${product.variation_count} variation${product.variation_count === 1 ? "" : "s"}` : " · Product"}{product.model_sku ? ` · ${product.model_sku}` : ""}</span></span></label>})}</div>{filtered.length === 0 && <div className="mt-2 border border-dashed p-5 text-sm text-black/45">No products match these filters.</div>}</> : <div className="mt-4 border-2 border-dashed border-black/10 p-5 text-sm text-black/45">Publish a parent product or family before adding it to a carousel.</div>}
  </div>;
}

type UpdateConfig=(id:string,key:string,value:string|string[]|boolean)=>void;

function SectionIntroFields({section,updateConfig,textInput}:{section:BuilderSection;updateConfig:UpdateConfig;textInput:string}){
  return <><label className="grid gap-2 text-sm font-bold sm:col-span-2">Eyebrow text<input value={String(section.config.eyebrow??"")} onChange={event=>updateConfig(section.id,"eyebrow",event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Section title<input value={String(section.config.title??"")} onChange={event=>updateConfig(section.id,"title",event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Description<textarea rows={3} value={String(section.config.description??"")} onChange={event=>updateConfig(section.id,"description",event.target.value)} className="border border-black/20 p-3 font-normal"/></label></>;
}

function ColorControls({section,updateConfig,textInput,showButton=false}:{section:BuilderSection;updateConfig:UpdateConfig;textInput:string;showButton?:boolean}){
  const legacyStyle=String(section.config.style??"light");
  const background=String(section.config.background??(legacyStyle==="dark"?"black":legacyStyle==="neutral"?"neutral":"white"));
  return <fieldset className="grid gap-4 border border-black/10 bg-[#f7f7f5] p-4 sm:col-span-2 sm:grid-cols-2"><legend className="px-2 text-xs font-extrabold uppercase tracking-wide text-black/45">Section colors</legend><label className="grid gap-2 text-sm font-bold">Background<select value={background} onChange={event=>updateConfig(section.id,"background",event.target.value)} className={textInput}><option value="white">White</option><option value="neutral">Neutral</option><option value="black">Black / industrial</option><option value="primary">Primary brand color</option><option value="secondary">Secondary brand color</option><option value="custom">Custom color</option></select></label><label className="grid gap-2 text-sm font-bold">Text color<select value={String(section.config.text_tone??"auto")} onChange={event=>updateConfig(section.id,"text_tone",event.target.value)} className={textInput}><option value="auto">Automatic contrast</option><option value="light">Light</option><option value="dark">Dark</option></select></label>{background==="custom"&&<label className="grid gap-2 text-sm font-bold">Custom background<input type="color" value={String(section.config.custom_bg??"#444444")} onChange={event=>updateConfig(section.id,"custom_bg",event.target.value)} className="h-11 w-full cursor-pointer border border-black/20 bg-white p-1"/></label>}<label className="grid gap-2 text-sm font-bold">Accent color<select value={String(section.config.accent_color??"primary")} onChange={event=>updateConfig(section.id,"accent_color",event.target.value)} className={textInput}><option value="primary">Primary brand color</option><option value="secondary">Secondary brand color</option><option value="black">Black</option><option value="white">White</option></select></label>{showButton&&<label className="grid gap-2 text-sm font-bold">Button color<select value={String(section.config.button_color??"primary")} onChange={event=>updateConfig(section.id,"button_color",event.target.value)} className={textInput}><option value="primary">Primary brand color</option><option value="secondary">Secondary brand color</option><option value="black">Black</option><option value="white">White</option></select></label>}<p className="self-end text-xs leading-5 text-black/45">Automatic contrast keeps section text readable when brand colors change.</p></fieldset>;
}

function SectionImageField({section,updateConfig}:{section:BuilderSection;updateConfig:UpdateConfig}){
  return <div className="sm:col-span-2"><p className="mb-2 text-sm font-bold">Feature image</p>{section.config.image_url?<div className="relative overflow-hidden border border-black/10 bg-black"><img src={String(section.config.image_url)} alt="Current section" className="h-48 w-full object-cover opacity-85"/><button type="button" onClick={()=>updateConfig(section.id,"image_url","")} className="absolute right-3 top-3 bg-white px-3 py-2 text-[11px] font-extrabold uppercase shadow">Remove image</button></div>:<div className="grid min-h-28 place-items-center border-2 border-dashed border-black/15 bg-black/[.02] text-sm text-black/40">No feature image yet</div>}<label className="mt-3 grid gap-2 text-sm font-bold">Upload image<input name={`sectionImage:${section.id}`} type="file" accept="image/png,image/jpeg,image/webp" className="min-h-12 border border-black/20 p-3 font-normal"/></label></div>;
}

function CategoryPicker({section,products,updateConfig}:{section:BuilderSection;products:ProductOption[];updateConfig:UpdateConfig}){
  const categories=Array.from(new Set(products.map(product=>product.category_name||"Uncategorized"))).sort();
  const selected=Array.isArray(section.config.categories)?section.config.categories:[];
  const toggle=(category:string)=>updateConfig(section.id,"categories",selected.includes(category)?selected.filter(item=>item!==category):[...selected,category]);
  return <div className="sm:col-span-2"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-bold">Choose categories</p><p className="mt-1 text-sm text-black/45">Cards use imagery from a published product in each category.</p></div><span className="rounded-full bg-black/5 px-3 py-1 text-xs font-extrabold">{selected.length} selected</span></div><div className="mt-4 grid max-h-72 gap-2 overflow-y-auto sm:grid-cols-2">{categories.map(category=><label key={category} className={`flex cursor-pointer items-center gap-3 border p-4 text-sm font-bold ${selected.includes(category)?"border-black bg-black text-white":"border-black/10"}`}><input type="checkbox" checked={selected.includes(category)} onChange={()=>toggle(category)}/>{category}</label>)}{!categories.length&&<p className="border border-dashed p-4 text-sm text-black/45 sm:col-span-2">Publish products with categories to use this section.</p>}</div></div>;
}

function SplitPanelFields({side,section,updateConfig,textInput}:{side:"left"|"right";section:BuilderSection;updateConfig:UpdateConfig;textInput:string}){
  const imageKey=side==="left"?"image_url":"image_url_2";
  const uploadName=side==="left"?`sectionImage:${section.id}`:`sectionImage:${section.id}:secondary`;
  return <fieldset className="grid gap-3 border border-black/10 p-4 sm:col-span-2"><legend className="px-2 text-xs font-extrabold uppercase tracking-wide text-black/45">{side} panel</legend>{section.config[imageKey]?<div className="relative overflow-hidden bg-black"><img src={String(section.config[imageKey])} alt="" className="h-40 w-full object-cover opacity-80"/><button type="button" onClick={()=>updateConfig(section.id,imageKey,"")} className="absolute right-3 top-3 bg-white px-3 py-2 text-[11px] font-extrabold uppercase">Remove</button></div>:<div className="grid min-h-24 place-items-center border-2 border-dashed text-sm text-black/40">No image yet</div>}<label className="grid gap-2 text-sm font-bold">Upload image<input name={uploadName} type="file" accept="image/png,image/jpeg,image/webp" className="min-h-12 border p-3 font-normal"/></label><label className="grid gap-2 text-sm font-bold">Headline<input value={String(section.config[`${side}_title`]??"")} onChange={event=>updateConfig(section.id,`${side}_title`,event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold">Description<textarea rows={2} value={String(section.config[`${side}_description`]??"")} onChange={event=>updateConfig(section.id,`${side}_description`,event.target.value)} className="border border-black/20 p-3 font-normal"/></label><label className="grid gap-2 text-sm font-bold">Optional destination<input value={String(section.config[`${side}_link`]??"")} onChange={event=>updateConfig(section.id,`${side}_link`,event.target.value)} placeholder="/app/my-training" className={textInput}/></label></fieldset>;
}

function BuilderPreview({sections,products,primary}:{sections:BuilderSection[];products:ProductOption[];primary:string}){
  const visible=sections.filter(section=>section.enabled);
  const productMap=new Map(products.map(product=>[product.product_id,product]));
  return <aside className="hidden h-fit overflow-hidden rounded-lg border border-black/10 bg-[#e8e8e5] shadow-sm 2xl:sticky 2xl:top-24 2xl:block">
    <div className="flex items-center justify-between border-b border-black/10 bg-white px-4 py-3"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-black/35">Live preview</p><p className="mt-1 text-xs font-bold">Desktop landing page</p></div><span className="h-2.5 w-2.5 rounded-full bg-green-500"/></div>
    <div className="max-h-[calc(100vh-190px)] overflow-y-auto p-3"><div className="overflow-hidden rounded-md bg-white shadow-sm">
      <div className="flex h-10 items-center justify-between border-b border-black/10 px-3"><span className="h-3 w-20 rounded-sm bg-black/80"/><span className="h-2 w-10 rounded-full" style={{backgroundColor:primary}}/></div>
      {visible.map(section=>{const config=section.config; if(section.type==="announcement")return <div key={section.id} className="px-3 py-2 text-center text-[8px] font-black uppercase text-white" style={{backgroundColor:primary}}>{String(config.messages??"Announcement").split("\n")[0].split("|")[0]}</div>;
        if(section.type==="hero")return <div key={section.id} className="relative isolate min-h-52 overflow-hidden bg-[#181818] p-5 text-white">{config.image_url&&<img src={String(config.image_url)} alt="" className="absolute inset-0 -z-20 h-full w-full object-cover"/>}<div className="absolute inset-0 -z-10 bg-black" style={{opacity:Number(config.overlay??60)/100}}/><p className="text-[8px] font-black uppercase tracking-[.15em]" style={{color:primary}}>{String(config.eyebrow??"Learning center")}</p><h3 className="mt-3 max-w-[250px] text-2xl font-black uppercase leading-[.9]">{String(config.headline??"Hero headline")}</h3><p className="mt-3 max-w-[250px] text-[9px] leading-4 text-white/65">{String(config.description??"")}</p><span className="mt-4 inline-flex rounded-sm px-3 py-2 text-[8px] font-black uppercase text-white" style={{backgroundColor:primary}}>{String(config.button_text??"Start training")}</span></div>;
        if(section.type==="carousel"||section.type==="product_showcase"){const ids=Array.isArray(config.product_ids)?config.product_ids:[];return <div key={section.id} className="p-4"><h3 className="text-sm font-black uppercase">{String(config.title??"Featured products")}</h3><div className="mt-3 grid grid-cols-3 gap-2">{ids.slice(0,3).map(id=><div key={id} className="min-h-20 rounded-sm border border-black/10 bg-[#f3f3f1] p-2"><div className="h-8 rounded-sm bg-black/5"/><p className="mt-2 line-clamp-2 text-[7px] font-bold uppercase">{productMap.get(id)?.name??"Product"}</p></div>)}{!ids.length&&[1,2,3].map(item=><div key={item} className="h-20 rounded-sm bg-black/5"/>)}</div></div>}
        if(section.type==="benefits")return <div key={section.id} className="bg-[#f3f3f1] p-4"><h3 className="text-center text-sm font-black uppercase">{String(config.title??"Benefits")}</h3><div className="mt-3 grid grid-cols-3 gap-2">{[1,2,3].map(card=><div key={card} className="rounded-sm bg-white p-2"><b className="text-[7px] uppercase">{String(config[`card_${card}_title`]??`Benefit ${card}`)}</b><div className="mt-2 h-1.5 rounded-full bg-black/10"/><div className="mt-1 h-1.5 w-2/3 rounded-full bg-black/10"/></div>)}</div></div>;
        if(section.type==="banner")return <div key={section.id} className="h-20 bg-black/10">{config.image_url&&<img src={String(config.image_url)} alt="" className="h-full w-full object-cover"/>}</div>;
        return <div key={section.id} className="border-t border-black/10 p-4"><p className="text-[8px] font-black uppercase tracking-[.12em]" style={{color:primary}}>{labels[section.type]}</p><h3 className="mt-2 text-base font-black uppercase leading-tight">{String(config.title??config.headline??config.left_title??labels[section.type])}</h3><p className="mt-2 line-clamp-2 text-[8px] leading-4 text-black/45">{String(config.description??config.left_description??"")}</p></div>})}
      {!visible.length&&<div className="grid min-h-64 place-items-center p-8 text-center text-xs text-black/40">Add or show a section to preview the landing page.</div>}
    </div></div>
  </aside>;
}

export default function PageBuilder({ initialSections, products, primary }: { initialSections:BuilderSection[]; products:ProductOption[]; primary:string }) {
  const [sections, setSections] = useState(() => initialSections.map((section) => {
    if (section.type !== "carousel" && section.type !== "product_showcase") return section;
    const savedIds=Array.isArray(section.config.product_ids)?section.config.product_ids:[];
    const migratedIds=savedIds.length ? savedIds : products.filter((product)=>product.category_name===String(section.config.category??"")).map((product)=>product.product_id);
    return { ...section, config:{ ...section.config, mode:"manual", product_ids:migratedIds } };
  }));
  const [expanded, setExpanded] = useState<Set<string>>(() => new Set(initialSections.map((section)=>section.id)));
  const [dragged, setDragged] = useState<string|null>(null);
  const update = (id:string, patch:Partial<BuilderSection>) => setSections((current) => current.map((section) => section.id === id ? { ...section, ...patch } : section));
  const updateConfig = (id:string, key:string, value:string|string[]|boolean) => setSections((current) => current.map((section) => section.id === id ? { ...section, config:{ ...section.config, [key]:value } } : section));
  const dropOn = (target:string) => { if (!dragged || dragged === target) return; setSections((current) => { const from=current.findIndex((s)=>s.id===dragged); const to=current.findIndex((s)=>s.id===target); const copy=[...current]; const [item]=copy.splice(from,1); copy.splice(to,0,item); return copy; }); setDragged(null); };
  const move = (id:string, direction:number) => setSections((current) => { const index=current.findIndex((section)=>section.id===id); const target=index+direction; if(index<0||target<0||target>=current.length)return current; const copy=[...current]; [copy[index],copy[target]]=[copy[target],copy[index]]; return copy; });
  const duplicate = (section:BuilderSection) => setSections((current) => [...current.slice(0,current.findIndex((item)=>item.id===section.id)+1), { ...section, id:crypto.randomUUID(), config:{...section.config} }, ...current.slice(current.findIndex((item)=>item.id===section.id)+1)]);
  const toggleExpanded = (id:string) => setExpanded((current) => { const next=new Set(current); if(next.has(id)) next.delete(id); else next.add(id); return next; });
  const addSection = (type:BuilderSection["type"]) => { const section=newSection(type); setSections((current)=>[...current,section]); setExpanded((current)=>new Set(current).add(section.id)); };
  const textInput = "min-h-11 w-full rounded-md border border-black/15 bg-white px-3 text-sm outline-none transition focus:border-black/45 focus:ring-2 focus:ring-black/5";

  return <section className="rounded-xl border border-black/10 bg-white p-5 shadow-[0_1px_2px_rgba(16,16,16,.05)] sm:p-7"><input type="hidden" name="pageSections" value={JSON.stringify(sections)}/><div className="flex flex-wrap items-start justify-between gap-4 border-b border-black/10 pb-5"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-black/40">03 · Landing page</p><h2 className="mt-2 text-2xl font-extrabold uppercase">Page builder</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-black/55">Build the page from reusable brand-safe sections, then drag them into the right order.</p></div><div className="flex flex-wrap items-center gap-2"><button type="button" onClick={()=>setExpanded(new Set(sections.map((section)=>section.id)))} className="rounded-md px-3 py-2 text-[11px] font-extrabold uppercase text-black/45 hover:bg-black/[.04] hover:text-black">Expand all</button><button type="button" onClick={()=>setExpanded(new Set())} className="rounded-md px-3 py-2 text-[11px] font-extrabold uppercase text-black/45 hover:bg-black/[.04] hover:text-black">Collapse all</button><span className="rounded-full bg-black/5 px-3 py-2 text-[11px] font-extrabold uppercase tracking-wide text-black/45">{sections.filter((section)=>section.enabled).length} visible</span></div></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[280px_minmax(0,1fr)] 2xl:grid-cols-[260px_minmax(520px,1fr)_360px]"><div className="grid gap-4 xl:col-start-2">{sections.map((section,index) => <article key={section.id} draggable onDragStart={()=>setDragged(section.id)} onDragOver={(event)=>event.preventDefault()} onDrop={()=>dropOn(section.id)} className={`overflow-hidden rounded-lg border bg-white transition duration-150 ${section.enabled ? "border-black/15 shadow-[0_1px_2px_rgba(16,16,16,.05)] hover:border-black/25" : "border-dashed border-black/15 opacity-60"}`}><div className={`flex flex-wrap items-center gap-2 bg-[#f7f7f5] px-3 py-3 sm:px-4 ${expanded.has(section.id)?"border-b border-black/10":""}`}><span className="cursor-grab text-xl leading-none text-black/30" title="Drag to reorder">⠿</span><span className="grid h-7 w-7 place-items-center rounded-md bg-black text-xs font-black text-white">{index+1}</span><b className="mr-auto text-sm uppercase sm:text-base">{labels[section.type]}</b><div className="flex items-center gap-1 border-l border-black/10 pl-2"><button type="button" onClick={()=>move(section.id,-1)} disabled={index===0} aria-label={`Move ${labels[section.type]} up`} className="grid h-8 w-8 place-items-center rounded-md text-sm font-black hover:bg-black/5 disabled:opacity-20">↑</button><button type="button" onClick={()=>move(section.id,1)} disabled={index===sections.length-1} aria-label={`Move ${labels[section.type]} down`} className="grid h-8 w-8 place-items-center rounded-md text-sm font-black hover:bg-black/5 disabled:opacity-20">↓</button></div><div className="flex flex-wrap gap-x-1 gap-y-1 pl-1"><button type="button" onClick={()=>toggleExpanded(section.id)} aria-expanded={expanded.has(section.id)} className="rounded-md px-2 py-1 text-[11px] font-extrabold uppercase tracking-wide hover:bg-black/[.05]">{expanded.has(section.id)?"Collapse":"Edit"} {expanded.has(section.id)?"−":"+"}</button><button type="button" onClick={()=>update(section.id,{enabled:!section.enabled})} className="rounded-md px-2 py-1 text-[11px] font-extrabold uppercase tracking-wide hover:bg-black/[.05]">{section.enabled?"Hide":"Show"}</button><button type="button" onClick={()=>duplicate(section)} className="rounded-md px-2 py-1 text-[11px] font-extrabold uppercase tracking-wide hover:bg-black/[.05]">Duplicate</button><button type="button" onClick={()=>setSections((current)=>current.filter((item)=>item.id!==section.id))} className="rounded-md px-2 py-1 text-[11px] font-extrabold uppercase tracking-wide text-red-700 hover:bg-red-50">Remove</button></div></div><div className={`${expanded.has(section.id)?"grid":"hidden"} gap-4 p-4 sm:grid-cols-2 sm:p-5`}>
          {section.type === "announcement" && <label className="grid gap-2 text-sm font-bold sm:col-span-2">Messages <span className="font-normal text-black/45">One per line. Add a link after |</span><textarea rows={4} value={String(section.config.messages??"")} onChange={(event)=>updateConfig(section.id,"messages",event.target.value)} className="border border-black/20 p-3 font-normal"/></label>}
          {section.type === "hero" && <>
            <div className="sm:col-span-2"><p className="mb-2 text-sm font-bold">Background image</p>{section.config.image_url ? <div className="relative overflow-hidden border border-black/10 bg-black"><img src={String(section.config.image_url)} alt="Current hero" className="h-48 w-full object-cover opacity-80"/><button type="button" onClick={()=>updateConfig(section.id,"image_url","")} className="absolute right-3 top-3 bg-white px-3 py-2 text-[11px] font-extrabold uppercase shadow">Remove image</button></div> : <div className="grid min-h-28 place-items-center border-2 border-dashed border-black/15 bg-black/[.02] px-4 text-center text-sm text-black/40">No hero image yet</div>}<label className="mt-3 grid gap-2 text-sm font-bold">Upload {section.config.image_url ? "a replacement" : "an image"}<input name={`sectionImage:${section.id}`} type="file" accept="image/png,image/jpeg,image/webp" className="min-h-12 border border-black/20 p-3 font-normal"/><span className="font-normal text-black/45">Wide landscape images work best. PNG, JPG, or WebP up to 8 MB.</span></label></div>
            <label className="grid gap-2 text-sm font-bold sm:col-span-2">Eyebrow text<input value={String(section.config.eyebrow??"")} onChange={(event)=>updateConfig(section.id,"eyebrow",event.target.value)} placeholder="Learning center" className={textInput}/></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Headline<input value={String(section.config.headline??"")} onChange={(event)=>updateConfig(section.id,"headline",event.target.value)} className={textInput}/></label>
            <label className="grid gap-2 text-sm font-bold sm:col-span-2">Description<textarea rows={3} value={String(section.config.description??"")} onChange={(event)=>updateConfig(section.id,"description",event.target.value)} className="border border-black/20 p-3 font-normal"/></label>
            <label className="grid gap-2 text-sm font-bold">Button text<input value={String(section.config.button_text??"")} onChange={(event)=>updateConfig(section.id,"button_text",event.target.value)} className={textInput}/></label>
            <label className="grid gap-2 text-sm font-bold">Button destination<input value={String(section.config.link_url??"")} onChange={(event)=>updateConfig(section.id,"link_url",event.target.value)} placeholder="/login" className={textInput}/></label>
            <label className="grid gap-2 text-sm font-bold">Text alignment<select value={String(section.config.alignment??"left")} onChange={(event)=>updateConfig(section.id,"alignment",event.target.value)} className={textInput}><option value="left">Left</option><option value="center">Centered</option></select></label>
            <label className="grid gap-2 text-sm font-bold">Hero height<select value={String(section.config.height??"large")} onChange={(event)=>updateConfig(section.id,"height",event.target.value)} className={textInput}><option value="compact">Compact</option><option value="large">Large</option><option value="full">Full screen</option></select></label>
            <label className="grid gap-2 text-sm font-bold sm:col-span-2">Image overlay · {String(section.config.overlay??"60")}%<input type="range" min="0" max="90" value={String(section.config.overlay??"60")} onChange={(event)=>updateConfig(section.id,"overlay",event.target.value)} className="min-h-11 accent-black"/></label>
          </>}
          {section.type === "carousel" && <><label className="grid gap-2 text-sm font-bold sm:col-span-2">Section title<input value={String(section.config.title??"")} onChange={(event)=>updateConfig(section.id,"title",event.target.value)} className={textInput}/></label><CarouselProductPicker section={section} products={products} updateConfig={updateConfig}/><label className="flex items-center gap-3 text-sm font-bold sm:col-span-2"><input type="checkbox" checked={Boolean(section.config.autoplay)} onChange={(event)=>updateConfig(section.id,"autoplay",event.target.checked)}/> Rotate automatically</label></>}
          {section.type === "product_showcase" && <><SectionIntroFields section={section} updateConfig={updateConfig} textInput={textInput}/><CarouselProductPicker section={section} products={products} updateConfig={updateConfig}/><ColorControls section={section} updateConfig={updateConfig} textInput={textInput}/></>}
          {section.type === "category_explorer" && <><SectionIntroFields section={section} updateConfig={updateConfig} textInput={textInput}/><CategoryPicker section={section} products={products} updateConfig={updateConfig}/><ColorControls section={section} updateConfig={updateConfig} textInput={textInput}/></>}
          {section.type === "split_feature" && <><SplitPanelFields side="left" section={section} updateConfig={updateConfig} textInput={textInput}/><SplitPanelFields side="right" section={section} updateConfig={updateConfig} textInput={textInput}/><ColorControls section={section} updateConfig={updateConfig} textInput={textInput}/></>}
          {(section.type === "dealer_program" || section.type === "featured_training") && <><SectionImageField section={section} updateConfig={updateConfig}/><SectionIntroFields section={section} updateConfig={updateConfig} textInput={textInput}/><label className="grid gap-2 text-sm font-bold">Button text<input value={String(section.config.button_text??"")} onChange={(event)=>updateConfig(section.id,"button_text",event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold">Button destination<input value={String(section.config.link_url??"")} onChange={(event)=>updateConfig(section.id,"link_url",event.target.value)} className={textInput}/></label><ColorControls section={section} updateConfig={updateConfig} textInput={textInput} showButton/></>}
          {section.type === "benefits" && <><label className="grid gap-2 text-sm font-bold sm:col-span-2">Eyebrow text<input value={String(section.config.eyebrow??"Built for product experts")} onChange={(event)=>updateConfig(section.id,"eyebrow",event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Section title<input value={String(section.config.title??"")} onChange={(event)=>updateConfig(section.id,"title",event.target.value)} className={textInput}/></label>{[["Product Training","Understand products, features, and customer benefits."],["Knowledge Checks","Reinforce the information that matters at the point of sale."],["Progress Tracking","Give teams visibility into training and completion."]].map(([fallbackTitle,fallbackDescription],index)=>{const card=index+1;return <fieldset key={card} className="grid gap-3 border border-black/10 p-4 sm:col-span-2"><legend className="px-2 text-xs font-extrabold uppercase tracking-wide text-black/45">Card {card}</legend><label className="grid gap-2 text-sm font-bold">Title<input value={String(section.config[`card_${card}_title`]??fallbackTitle)} onChange={(event)=>updateConfig(section.id,`card_${card}_title`,event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold">Description<textarea rows={2} value={String(section.config[`card_${card}_description`]??fallbackDescription)} onChange={(event)=>updateConfig(section.id,`card_${card}_description`,event.target.value)} className="border border-black/20 p-3 font-normal"/></label></fieldset>})}<ColorControls section={section} updateConfig={updateConfig} textInput={textInput}/></>}
          {section.type === "banner" && <><div className="sm:col-span-2">{section.config.image_url ? <div className="relative overflow-hidden border border-black/10"><img src={String(section.config.image_url)} alt="Current banner" className="max-h-56 w-full object-cover"/><button type="button" onClick={()=>updateConfig(section.id,"image_url","")} className="absolute right-3 top-3 bg-white px-3 py-2 text-[11px] font-extrabold uppercase shadow">Remove image</button></div> : <div className="grid min-h-24 place-items-center border-2 border-dashed border-black/15 text-sm text-black/40">No banner image yet</div>}<label className="mt-3 grid gap-2 text-sm font-bold">Upload banner image<input name={`sectionImage:${section.id}`} type="file" accept="image/png,image/jpeg,image/webp" className="min-h-12 border border-black/20 p-3 font-normal"/></label></div><label className="grid gap-2 text-sm font-bold">Image description<input value={String(section.config.alt_text??"")} onChange={(event)=>updateConfig(section.id,"alt_text",event.target.value)} placeholder="Describe the banner for accessibility" className={textInput}/></label><label className="grid gap-2 text-sm font-bold">Destination URL<input value={String(section.config.link_url??"")} onChange={(event)=>updateConfig(section.id,"link_url",event.target.value)} className={textInput}/></label></>}
          {section.type === "cta" && <><label className="grid gap-2 text-sm font-bold sm:col-span-2">Eyebrow text<input value={String(section.config.eyebrow??"")} onChange={(event)=>updateConfig(section.id,"eyebrow",event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Headline<input value={String(section.config.headline??"")} onChange={(event)=>updateConfig(section.id,"headline",event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Description<textarea rows={2} value={String(section.config.description??"")} onChange={(event)=>updateConfig(section.id,"description",event.target.value)} className="border border-black/20 p-3 font-normal"/></label><label className="grid gap-2 text-sm font-bold">Button text<input value={String(section.config.button_text??"")} onChange={(event)=>updateConfig(section.id,"button_text",event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold">Button link<input value={String(section.config.link_url??"")} onChange={(event)=>updateConfig(section.id,"link_url",event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold">Text alignment<select value={String(section.config.alignment??"left")} onChange={(event)=>updateConfig(section.id,"alignment",event.target.value)} className={textInput}><option value="left">Left</option><option value="center">Centered</option></select></label><ColorControls section={section} updateConfig={updateConfig} textInput={textInput} showButton/></>}
        </div></article>)}</div><aside className="order-first h-fit rounded-lg border border-black/10 bg-[#f4f4f2] p-4 xl:col-start-1 xl:row-start-1 xl:sticky xl:top-24"><div className="flex items-center justify-between gap-3"><p className="text-xs font-extrabold uppercase tracking-[.14em] text-black/45">Section library</p><span className="text-[11px] text-black/35 xl:hidden">Add a block</span></div><p className="mt-2 hidden text-xs leading-5 text-black/45 xl:block">Choose a structured block. Every section inherits the academy brand system.</p><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-1">{(Object.keys(labels) as BuilderSection["type"][]).map((type)=><button key={type} type="button" onClick={()=>addSection(type)} className="flex min-h-10 items-center gap-2 rounded-md border border-black/10 bg-white px-3 text-left text-[11px] font-extrabold uppercase tracking-wide transition hover:-translate-y-px hover:border-black/30 hover:shadow-sm"><span className="text-base leading-none" style={{color:primary}}>+</span><span>{labels[type]}</span></button>)}</div></aside><BuilderPreview sections={sections} products={products} primary={primary}/></div>
  </section>;
}
