"use client";

import { useState } from "react";
import type { LandingSection } from "@/lib/branding";

export type BuilderSection = LandingSection;
type ProductOption = { product_id:string; name:string; category_name:string|null };

const labels: Record<BuilderSection["type"], string> = { announcement:"Announcement bar", hero:"Hero", carousel:"Product carousel", benefits:"Benefits cards", banner:"Promotional banner", cta:"Call to action" };
const newSection = (type: BuilderSection["type"]): BuilderSection => ({ id: crypto.randomUUID(), type, enabled:true, config: type === "carousel" ? { title:"Featured products", mode:"category", category:"", product_ids:[], autoplay:true } : type === "hero" ? { headline:"Product knowledge that drives sales.", description:"Learn the products and build confidence with every customer.", button_text:"Start training", link_url:"", image_url:"", overlay:"60", alignment:"left", height:"large" } : type === "announcement" ? { messages:"New training is now available" } : type === "benefits" ? { title:"Build product confidence" } : type === "banner" ? { image_url:"", link_url:"" } : { headline:"Ready to start training?", description:"Sign in to continue your learning.", button_text:"Start training", link_url:"/login" } });

export default function PageBuilder({ initialSections, products, primary }: { initialSections:BuilderSection[]; products:ProductOption[]; primary:string }) {
  const [sections, setSections] = useState(initialSections);
  const [dragged, setDragged] = useState<string|null>(null);
  const categories = Array.from(new Set(products.map((product) => product.category_name).filter(Boolean))) as string[];
  const update = (id:string, patch:Partial<BuilderSection>) => setSections((current) => current.map((section) => section.id === id ? { ...section, ...patch } : section));
  const updateConfig = (id:string, key:string, value:string|string[]|boolean) => setSections((current) => current.map((section) => section.id === id ? { ...section, config:{ ...section.config, [key]:value } } : section));
  const dropOn = (target:string) => { if (!dragged || dragged === target) return; setSections((current) => { const from=current.findIndex((s)=>s.id===dragged); const to=current.findIndex((s)=>s.id===target); const copy=[...current]; const [item]=copy.splice(from,1); copy.splice(to,0,item); return copy; }); setDragged(null); };
  const move = (id:string, direction:number) => setSections((current) => { const index=current.findIndex((section)=>section.id===id); const target=index+direction; if(index<0||target<0||target>=current.length)return current; const copy=[...current]; [copy[index],copy[target]]=[copy[target],copy[index]]; return copy; });
  const duplicate = (section:BuilderSection) => setSections((current) => [...current.slice(0,current.findIndex((item)=>item.id===section.id)+1), { ...section, id:crypto.randomUUID(), config:{...section.config} }, ...current.slice(current.findIndex((item)=>item.id===section.id)+1)]);
  const textInput = "min-h-11 w-full border border-black/20 px-3 text-sm outline-none focus:border-black";

  return <section className="border border-black/10 bg-white p-5 sm:p-7"><input type="hidden" name="pageSections" value={JSON.stringify(sections)}/><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-black/40">03 · Landing page</p><h2 className="mt-2 text-2xl font-extrabold uppercase">Page builder</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-black/55">Drag sections into order. Add multiple product carousels for different categories.</p></div><span className="rounded-full bg-black/5 px-3 py-2 text-[11px] font-extrabold uppercase tracking-wide text-black/45">{sections.filter((section)=>section.enabled).length} visible</span></div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1fr)_260px]"><div className="grid gap-4">{sections.map((section,index) => <article key={section.id} draggable onDragStart={()=>setDragged(section.id)} onDragOver={(event)=>event.preventDefault()} onDrop={()=>dropOn(section.id)} className={`overflow-hidden border bg-white shadow-sm transition ${section.enabled ? "border-black/15" : "border-dashed border-black/15 opacity-60"}`}><div className="flex flex-wrap items-center gap-2 border-b border-black/10 bg-[#f7f7f5] px-3 py-3 sm:px-4"><span className="cursor-grab text-xl leading-none text-black/30" title="Drag to reorder">⠿</span><span className="grid h-7 w-7 place-items-center bg-black text-xs font-black text-white">{index+1}</span><b className="mr-auto text-sm uppercase sm:text-base">{labels[section.type]}</b><div className="flex items-center gap-1 border-l border-black/10 pl-2"><button type="button" onClick={()=>move(section.id,-1)} disabled={index===0} aria-label={`Move ${labels[section.type]} up`} className="grid h-8 w-8 place-items-center text-sm font-black hover:bg-black/5 disabled:opacity-20">↑</button><button type="button" onClick={()=>move(section.id,1)} disabled={index===sections.length-1} aria-label={`Move ${labels[section.type]} down`} className="grid h-8 w-8 place-items-center text-sm font-black hover:bg-black/5 disabled:opacity-20">↓</button></div><div className="flex flex-wrap gap-x-3 gap-y-1 pl-1"><button type="button" onClick={()=>update(section.id,{enabled:!section.enabled})} className="text-[11px] font-extrabold uppercase tracking-wide hover:underline">{section.enabled?"Hide":"Show"}</button><button type="button" onClick={()=>duplicate(section)} className="text-[11px] font-extrabold uppercase tracking-wide hover:underline">Duplicate</button><button type="button" onClick={()=>setSections((current)=>current.filter((item)=>item.id!==section.id))} className="text-[11px] font-extrabold uppercase tracking-wide text-red-700 hover:underline">Remove</button></div></div><div className="grid gap-4 p-4 sm:grid-cols-2 sm:p-5">
          {section.type === "announcement" && <label className="grid gap-2 text-sm font-bold sm:col-span-2">Messages <span className="font-normal text-black/45">One per line. Add a link after |</span><textarea rows={4} value={String(section.config.messages??"")} onChange={(event)=>updateConfig(section.id,"messages",event.target.value)} className="border border-black/20 p-3 font-normal"/></label>}
          {section.type === "hero" && <>
            <div className="sm:col-span-2"><p className="mb-2 text-sm font-bold">Background image</p>{section.config.image_url ? <div className="relative overflow-hidden border border-black/10 bg-black"><img src={String(section.config.image_url)} alt="Current hero" className="h-48 w-full object-cover opacity-80"/><button type="button" onClick={()=>updateConfig(section.id,"image_url","")} className="absolute right-3 top-3 bg-white px-3 py-2 text-[11px] font-extrabold uppercase shadow">Remove image</button></div> : <div className="grid min-h-28 place-items-center border-2 border-dashed border-black/15 bg-black/[.02] px-4 text-center text-sm text-black/40">No hero image yet</div>}<label className="mt-3 grid gap-2 text-sm font-bold">Upload {section.config.image_url ? "a replacement" : "an image"}<input name={`sectionImage:${section.id}`} type="file" accept="image/png,image/jpeg,image/webp" className="min-h-12 border border-black/20 p-3 font-normal"/><span className="font-normal text-black/45">Wide landscape images work best. PNG, JPG, or WebP up to 8 MB.</span></label></div>
            <label className="grid gap-2 text-sm font-bold sm:col-span-2">Headline<input value={String(section.config.headline??"")} onChange={(event)=>updateConfig(section.id,"headline",event.target.value)} className={textInput}/></label>
            <label className="grid gap-2 text-sm font-bold sm:col-span-2">Description<textarea rows={3} value={String(section.config.description??"")} onChange={(event)=>updateConfig(section.id,"description",event.target.value)} className="border border-black/20 p-3 font-normal"/></label>
            <label className="grid gap-2 text-sm font-bold">Button text<input value={String(section.config.button_text??"")} onChange={(event)=>updateConfig(section.id,"button_text",event.target.value)} className={textInput}/></label>
            <label className="grid gap-2 text-sm font-bold">Button destination<input value={String(section.config.link_url??"")} onChange={(event)=>updateConfig(section.id,"link_url",event.target.value)} placeholder="/login" className={textInput}/></label>
            <label className="grid gap-2 text-sm font-bold">Text alignment<select value={String(section.config.alignment??"left")} onChange={(event)=>updateConfig(section.id,"alignment",event.target.value)} className={textInput}><option value="left">Left</option><option value="center">Centered</option></select></label>
            <label className="grid gap-2 text-sm font-bold">Hero height<select value={String(section.config.height??"large")} onChange={(event)=>updateConfig(section.id,"height",event.target.value)} className={textInput}><option value="compact">Compact</option><option value="large">Large</option><option value="full">Full screen</option></select></label>
            <label className="grid gap-2 text-sm font-bold sm:col-span-2">Image overlay · {String(section.config.overlay??"60")}%<input type="range" min="0" max="90" value={String(section.config.overlay??"60")} onChange={(event)=>updateConfig(section.id,"overlay",event.target.value)} className="min-h-11 accent-black"/></label>
          </>}
          {section.type === "carousel" && <><label className="grid gap-2 text-sm font-bold sm:col-span-2">Section title<input value={String(section.config.title??"")} onChange={(event)=>updateConfig(section.id,"title",event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold">Product source<select value={String(section.config.mode??"category")} onChange={(event)=>updateConfig(section.id,"mode",event.target.value)} className={textInput}><option value="category">Automatic category</option><option value="manual">Hand-picked products</option></select></label>{section.config.mode !== "manual" ? <label className="grid gap-2 text-sm font-bold">Category<select value={String(section.config.category??"")} onChange={(event)=>updateConfig(section.id,"category",event.target.value)} className={textInput}><option value="">Choose category…</option>{categories.map((category)=><option key={category}>{category}</option>)}</select></label> : <label className="grid gap-2 text-sm font-bold sm:col-span-2">Products<select multiple value={Array.isArray(section.config.product_ids)?section.config.product_ids:[]} onChange={(event)=>updateConfig(section.id,"product_ids",Array.from(event.target.selectedOptions).map((option)=>option.value))} className="min-h-32 border border-black/20 p-2 font-normal">{products.map((product)=><option key={product.product_id} value={product.product_id}>{product.name}{product.category_name?` · ${product.category_name}`:""}</option>)}</select><span className="font-normal text-black/45">Hold Command/Ctrl to choose several.</span></label>}<label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={Boolean(section.config.autoplay)} onChange={(event)=>updateConfig(section.id,"autoplay",event.target.checked)}/> Rotate automatically</label></>}
          {section.type === "benefits" && <label className="grid gap-2 text-sm font-bold sm:col-span-2">Section title<input value={String(section.config.title??"")} onChange={(event)=>updateConfig(section.id,"title",event.target.value)} className={textInput}/></label>}
          {section.type === "banner" && <><div className="sm:col-span-2">{section.config.image_url ? <div className="relative overflow-hidden border border-black/10"><img src={String(section.config.image_url)} alt="Current banner" className="max-h-56 w-full object-cover"/><button type="button" onClick={()=>updateConfig(section.id,"image_url","")} className="absolute right-3 top-3 bg-white px-3 py-2 text-[11px] font-extrabold uppercase shadow">Remove image</button></div> : <div className="grid min-h-24 place-items-center border-2 border-dashed border-black/15 text-sm text-black/40">No banner image yet</div>}<label className="mt-3 grid gap-2 text-sm font-bold">Upload banner image<input name={`sectionImage:${section.id}`} type="file" accept="image/png,image/jpeg,image/webp" className="min-h-12 border border-black/20 p-3 font-normal"/></label></div><label className="grid gap-2 text-sm font-bold sm:col-span-2">Destination URL<input value={String(section.config.link_url??"")} onChange={(event)=>updateConfig(section.id,"link_url",event.target.value)} className={textInput}/></label></>}
          {section.type === "cta" && <><label className="grid gap-2 text-sm font-bold sm:col-span-2">Headline<input value={String(section.config.headline??"")} onChange={(event)=>updateConfig(section.id,"headline",event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Description<input value={String(section.config.description??"")} onChange={(event)=>updateConfig(section.id,"description",event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold">Button text<input value={String(section.config.button_text??"")} onChange={(event)=>updateConfig(section.id,"button_text",event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold">Button link<input value={String(section.config.link_url??"")} onChange={(event)=>updateConfig(section.id,"link_url",event.target.value)} className={textInput}/></label></>}
        </div></article>)}</div><aside className="order-first h-fit border border-black/10 bg-[#f4f4f2] p-4 xl:order-none xl:sticky xl:top-5"><div className="flex items-center justify-between gap-3"><p className="text-xs font-extrabold uppercase tracking-[.14em] text-black/45">Add a section</p><span className="text-[11px] text-black/35 xl:hidden">Choose a block below</span></div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-1">{(Object.keys(labels) as BuilderSection["type"][]).map((type)=><button key={type} type="button" onClick={()=>setSections((current)=>[...current,newSection(type)])} className="flex min-h-10 items-center gap-2 border border-black/10 bg-white px-3 text-left text-[11px] font-extrabold uppercase tracking-wide transition hover:border-black hover:bg-black hover:text-white"><span className="text-base leading-none" style={{color:primary}}>+</span><span>{labels[type]}</span></button>)}</div></aside></div>
  </section>;
}
