"use client";

import { useState } from "react";
import type { LandingSection } from "@/lib/branding";

export type BuilderSection = LandingSection;
type ProductOption = { product_id:string; name:string; category_name:string|null };

const labels: Record<BuilderSection["type"], string> = { announcement:"Announcement bar", hero:"Hero", carousel:"Product carousel", benefits:"Benefits cards", banner:"Promotional banner", cta:"Call to action" };
const newSection = (type: BuilderSection["type"]): BuilderSection => ({ id: crypto.randomUUID(), type, enabled:true, config: type === "carousel" ? { title:"Featured products", mode:"category", category:"", product_ids:[], autoplay:true } : type === "hero" ? { headline:"Product knowledge that drives sales.", description:"Learn the products and build confidence with every customer.", button_text:"Start training" } : type === "announcement" ? { messages:"New training is now available" } : type === "benefits" ? { title:"Build product confidence" } : type === "banner" ? { image_url:"", link_url:"" } : { headline:"Ready to start training?", description:"Sign in to continue your learning.", button_text:"Start training", link_url:"/login" } });

export default function PageBuilder({ initialSections, products, primary }: { initialSections:BuilderSection[]; products:ProductOption[]; primary:string }) {
  const [sections, setSections] = useState(initialSections);
  const [dragged, setDragged] = useState<string|null>(null);
  const categories = Array.from(new Set(products.map((product) => product.category_name).filter(Boolean))) as string[];
  const update = (id:string, patch:Partial<BuilderSection>) => setSections((current) => current.map((section) => section.id === id ? { ...section, ...patch } : section));
  const updateConfig = (id:string, key:string, value:string|string[]|boolean) => setSections((current) => current.map((section) => section.id === id ? { ...section, config:{ ...section.config, [key]:value } } : section));
  const dropOn = (target:string) => { if (!dragged || dragged === target) return; setSections((current) => { const from=current.findIndex((s)=>s.id===dragged); const to=current.findIndex((s)=>s.id===target); const copy=[...current]; const [item]=copy.splice(from,1); copy.splice(to,0,item); return copy; }); setDragged(null); };
  const move = (id:string, direction:number) => setSections((current) => { const index=current.findIndex((section)=>section.id===id); const target=index+direction; if(index<0||target<0||target>=current.length)return current; const copy=[...current]; [copy[index],copy[target]]=[copy[target],copy[index]]; return copy; });
  const duplicate = (section:BuilderSection) => setSections((current) => [...current.slice(0,current.findIndex((item)=>item.id===section.id)+1), { ...section, id:crypto.randomUUID(), config:{...section.config} }, ...current.slice(current.findIndex((item)=>item.id===section.id)+1)]);
  const textInput = "min-h-11 w-full border border-black/20 px-3 text-sm outline-none focus:border-black";

  return <section className="border border-black/10 bg-white p-6 sm:p-8"><input type="hidden" name="pageSections" value={JSON.stringify(sections)}/><p className="text-xs font-extrabold uppercase tracking-[.16em] text-black/40">03 · Landing page</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-extrabold uppercase">Page builder</h2><p className="mt-2 text-sm text-black/55">Drag sections into order. Add multiple product carousels for different categories.</p></div><span className="text-xs font-bold uppercase text-black/40">{sections.filter((section)=>section.enabled).length} visible sections</span></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_220px]"><div className="grid gap-3">{sections.map((section,index) => <article key={section.id} draggable onDragStart={()=>setDragged(section.id)} onDragOver={(event)=>event.preventDefault()} onDrop={()=>dropOn(section.id)} className={`border-2 bg-white ${section.enabled ? "border-black/15" : "border-dashed border-black/10 opacity-60"}`}><div className="flex flex-wrap items-center gap-3 border-b border-black/10 bg-[#f4f4f2] px-4 py-3"><span className="cursor-grab text-xl text-black/35" title="Drag to reorder">⠿</span><span className="grid h-7 w-7 place-items-center bg-black text-xs font-black text-white">{index+1}</span><b className="mr-auto uppercase">{labels[section.type]}</b><button type="button" onClick={()=>move(section.id,-1)} disabled={index===0} aria-label={`Move ${labels[section.type]} up`} className="text-sm font-black disabled:opacity-20">↑</button><button type="button" onClick={()=>move(section.id,1)} disabled={index===sections.length-1} aria-label={`Move ${labels[section.type]} down`} className="text-sm font-black disabled:opacity-20">↓</button><button type="button" onClick={()=>update(section.id,{enabled:!section.enabled})} className="text-xs font-extrabold uppercase">{section.enabled?"Hide":"Show"}</button><button type="button" onClick={()=>duplicate(section)} className="text-xs font-extrabold uppercase">Duplicate</button><button type="button" onClick={()=>setSections((current)=>current.filter((item)=>item.id!==section.id))} className="text-xs font-extrabold uppercase text-red-700">Remove</button></div><div className="grid gap-4 p-4 sm:grid-cols-2">
          {section.type === "announcement" && <label className="grid gap-2 text-sm font-bold sm:col-span-2">Messages <span className="font-normal text-black/45">One per line. Add a link after |</span><textarea rows={4} value={String(section.config.messages??"")} onChange={(event)=>updateConfig(section.id,"messages",event.target.value)} className="border border-black/20 p-3 font-normal"/></label>}
          {section.type === "hero" && <><label className="grid gap-2 text-sm font-bold sm:col-span-2">Headline<input value={String(section.config.headline??"")} onChange={(event)=>updateConfig(section.id,"headline",event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Description<textarea rows={3} value={String(section.config.description??"")} onChange={(event)=>updateConfig(section.id,"description",event.target.value)} className="border border-black/20 p-3 font-normal"/></label><label className="grid gap-2 text-sm font-bold">Button text<input value={String(section.config.button_text??"")} onChange={(event)=>updateConfig(section.id,"button_text",event.target.value)} className={textInput}/></label></>}
          {section.type === "carousel" && <><label className="grid gap-2 text-sm font-bold sm:col-span-2">Section title<input value={String(section.config.title??"")} onChange={(event)=>updateConfig(section.id,"title",event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold">Product source<select value={String(section.config.mode??"category")} onChange={(event)=>updateConfig(section.id,"mode",event.target.value)} className={textInput}><option value="category">Automatic category</option><option value="manual">Hand-picked products</option></select></label>{section.config.mode !== "manual" ? <label className="grid gap-2 text-sm font-bold">Category<select value={String(section.config.category??"")} onChange={(event)=>updateConfig(section.id,"category",event.target.value)} className={textInput}><option value="">Choose category…</option>{categories.map((category)=><option key={category}>{category}</option>)}</select></label> : <label className="grid gap-2 text-sm font-bold sm:col-span-2">Products<select multiple value={Array.isArray(section.config.product_ids)?section.config.product_ids:[]} onChange={(event)=>updateConfig(section.id,"product_ids",Array.from(event.target.selectedOptions).map((option)=>option.value))} className="min-h-32 border border-black/20 p-2 font-normal">{products.map((product)=><option key={product.product_id} value={product.product_id}>{product.name}{product.category_name?` · ${product.category_name}`:""}</option>)}</select><span className="font-normal text-black/45">Hold Command/Ctrl to choose several.</span></label>}<label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={Boolean(section.config.autoplay)} onChange={(event)=>updateConfig(section.id,"autoplay",event.target.checked)}/> Rotate automatically</label></>}
          {section.type === "benefits" && <label className="grid gap-2 text-sm font-bold sm:col-span-2">Section title<input value={String(section.config.title??"")} onChange={(event)=>updateConfig(section.id,"title",event.target.value)} className={textInput}/></label>}
          {section.type === "banner" && <><label className="grid gap-2 text-sm font-bold">Image URL<input type="url" value={String(section.config.image_url??"")} onChange={(event)=>updateConfig(section.id,"image_url",event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold">Destination URL<input value={String(section.config.link_url??"")} onChange={(event)=>updateConfig(section.id,"link_url",event.target.value)} className={textInput}/></label></>}
          {section.type === "cta" && <><label className="grid gap-2 text-sm font-bold sm:col-span-2">Headline<input value={String(section.config.headline??"")} onChange={(event)=>updateConfig(section.id,"headline",event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Description<input value={String(section.config.description??"")} onChange={(event)=>updateConfig(section.id,"description",event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold">Button text<input value={String(section.config.button_text??"")} onChange={(event)=>updateConfig(section.id,"button_text",event.target.value)} className={textInput}/></label><label className="grid gap-2 text-sm font-bold">Button link<input value={String(section.config.link_url??"")} onChange={(event)=>updateConfig(section.id,"link_url",event.target.value)} className={textInput}/></label></>}
        </div></article>)}</div><aside className="h-fit border border-black/10 bg-[#f4f4f2] p-4 lg:sticky lg:top-5"><p className="text-xs font-extrabold uppercase tracking-[.14em] text-black/45">Add section</p><div className="mt-3 grid gap-2">{(Object.keys(labels) as BuilderSection["type"][]).map((type)=><button key={type} type="button" onClick={()=>setSections((current)=>[...current,newSection(type)])} className="min-h-10 border border-black/15 bg-white px-3 text-left text-xs font-extrabold uppercase transition hover:border-black" style={{borderLeftColor:primary,borderLeftWidth:4}}>+ {labels[type]}</button>)}</div></aside></div>
  </section>;
}
