import { redirect } from "next/navigation";
import { ManufacturerHeader } from "@/components/manufacturer-shell";
import { getActiveBrand } from "@/lib/branding";
import { createSupabaseServerClient } from "@/lib/supabase/server";

type Summary = { retailers: number; learners: number; assigned: number; completed: number; completion_rate: number; pass_rate: number };
type QuizStat = { quiz_id: string; title: string; assigned_retailers: number; assigned_learners: number; completed: number; average_score: number; passed: number };
type RetailerStat = { company_id: string; company_name: string; learners: number; assigned_quizzes: number; completed: number; average_score: number; passed: number };
type Recent = { learner_email: string; company_name: string; quiz_title: string; score: number; passed: boolean; submitted_at: string };
type Report = { summary: Summary; quizzes: QuizStat[]; retailers: RetailerStat[]; recent: Recent[] };

function RateBar({ value, color }: { value: number; color: string }) {
  return <div className="mt-2 h-2 overflow-hidden bg-black/10"><div className="h-full" style={{ width: `${Math.min(100, value)}%`, backgroundColor: color }} /></div>;
}

export default async function ReportsPage() {
  const supabase = await createSupabaseServerClient();
  const [{ data: auth }, brand] = await Promise.all([supabase.auth.getUser(), getActiveBrand()]);
  if (!auth.user) redirect("/login");
  if (!brand?.can_view_reports) redirect("/app");
  const { data, error } = await supabase.rpc("manufacturer_training_report");
  const report = data as Report | null;
  const summary = report?.summary ?? { retailers: 0, learners: 0, assigned: 0, completed: 0, completion_rate: 0, pass_rate: 0 };
  const primary = brand.primary_color;

  return <div className="min-h-screen bg-[#f4f4f2] text-black"><ManufacturerHeader brand={brand} email={auth.user.email} /><main className="mx-auto max-w-7xl px-5 py-10 lg:px-8 lg:py-14">
    <p className="text-sm font-extrabold uppercase italic tracking-[0.2em]" style={{ color: primary }}>Network performance</p><h1 className="mt-2 text-4xl font-extrabold uppercase tracking-tight sm:text-5xl">Training reports</h1><p className="mt-3 max-w-2xl text-black/60">Measure retailer participation, product knowledge, and the training that needs attention.</p>
    {error && <div className="mt-7 border-l-4 bg-red-50 p-4 font-semibold text-red-900" style={{ borderColor: primary }}>Reports are temporarily unavailable.</div>}

    <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <article className="border border-black/10 bg-white p-5 shadow-sm"><span className="text-xs font-extrabold uppercase tracking-wide text-black/45">Retailers</span><b className="mt-2 block text-4xl">{summary.retailers}</b><p className="mt-1 text-sm text-black/50">{summary.learners} active learners</p></article>
      <article className="border border-black/10 bg-white p-5 shadow-sm"><span className="text-xs font-extrabold uppercase tracking-wide text-black/45">Completion rate</span><b className="mt-2 block text-4xl">{summary.completion_rate}%</b><RateBar value={summary.completion_rate} color={primary} /><p className="mt-2 text-sm text-black/50">{summary.completed} of {summary.assigned} learner assignments</p></article>
      <article className="border border-black/10 bg-white p-5 shadow-sm"><span className="text-xs font-extrabold uppercase tracking-wide text-black/45">Pass rate</span><b className="mt-2 block text-4xl">{summary.pass_rate}%</b><RateBar value={summary.pass_rate} color="#15803d" /><p className="mt-2 text-sm text-black/50">Latest completed attempts</p></article>
      <article className="p-5 text-white shadow-sm" style={{ backgroundColor: brand.secondary_color }}><span className="text-xs font-extrabold uppercase tracking-wide text-white/55">Outstanding</span><b className="mt-2 block text-4xl">{Math.max(0, summary.assigned - summary.completed)}</b><p className="mt-1 text-sm text-white/60">Assignments still to complete</p></article>
    </section>

    <section className="mt-10"><h2 className="text-2xl font-extrabold uppercase">By quiz</h2><div className="mt-4 overflow-hidden border border-black/10 bg-white shadow-sm"><div className="hidden grid-cols-[minmax(0,1.5fr)_150px_180px_120px_100px] items-center gap-5 border-b border-black/10 bg-black/[.03] px-5 py-4 text-xs font-extrabold uppercase tracking-wide text-black/45 lg:grid"><span>Quiz</span><span>Audience</span><span>Completion</span><span>Avg. score</span><span>Passed</span></div>{(report?.quizzes.length ?? 0) === 0 ? <p className="p-8 text-center text-black/50">No assigned quizzes yet.</p> : report!.quizzes.map(item => { const completion = item.assigned_learners ? Math.round(item.completed / item.assigned_learners * 100) : 0; return <article key={item.quiz_id} className="grid min-h-20 gap-4 border-b border-black/10 px-5 py-5 last:border-0 lg:grid-cols-[minmax(0,1.5fr)_150px_180px_120px_100px] lg:items-center lg:gap-5"><div className="min-w-0"><b className="uppercase">{item.title}</b><p className="mt-1 text-sm text-black/45">Quiz performance</p></div><div><span className="mr-2 text-[10px] font-extrabold uppercase text-black/35 lg:hidden">Audience</span><b>{item.assigned_retailers}</b><span className="ml-1 text-xs text-black/45">retailers</span><p className="mt-1 text-xs text-black/45">{item.assigned_learners} learners</p></div><div><div className="flex justify-between text-xs font-bold uppercase"><span>{completion}%</span><span className="text-black/35">{item.completed}/{item.assigned_learners}</span></div><RateBar value={completion} color={primary} /></div><div><span className="mr-2 text-[10px] font-extrabold uppercase text-black/35 lg:hidden">Avg. score</span><b className="text-lg">{item.average_score}%</b></div><div><span className="mr-2 text-[10px] font-extrabold uppercase text-black/35 lg:hidden">Passed</span><b className="text-lg">{item.passed}</b></div></article>})}</div></section>

    <section className="mt-10"><h2 className="text-2xl font-extrabold uppercase">By retailer</h2><div className="mt-4 overflow-hidden border border-black/10 bg-white shadow-sm"><div className="hidden grid-cols-[minmax(0,1.5fr)_120px_120px_180px_120px_100px] items-center gap-5 border-b border-black/10 bg-black/[.03] px-5 py-4 text-xs font-extrabold uppercase tracking-wide text-black/45 lg:grid"><span>Retailer</span><span>Learners</span><span>Assigned</span><span>Completion</span><span>Avg. score</span><span>Passed</span></div>{(report?.retailers.length ?? 0) === 0 ? <p className="p-8 text-center text-black/50">No connected retailers yet.</p> : report!.retailers.map(item => { const expected = item.learners * item.assigned_quizzes; const completion = expected ? Math.round(item.completed / expected * 100) : 0; return <article key={item.company_id} className="grid min-h-20 gap-4 border-b border-black/10 px-5 py-5 last:border-0 lg:grid-cols-[minmax(0,1.5fr)_120px_120px_180px_120px_100px] lg:items-center lg:gap-5"><div className="min-w-0"><b className="uppercase">{item.company_name}</b><p className="mt-1 text-sm text-black/45">Retailer performance</p></div><div><span className="mr-2 text-[10px] font-extrabold uppercase text-black/35 lg:hidden">Learners</span><b>{item.learners}</b></div><div><span className="mr-2 text-[10px] font-extrabold uppercase text-black/35 lg:hidden">Assigned</span><b>{item.assigned_quizzes}</b><span className="ml-1 text-xs text-black/45">quizzes</span></div><div><div className="flex justify-between text-xs font-bold uppercase"><span>{completion}%</span><span className="text-black/35">{item.completed}/{expected}</span></div><RateBar value={completion} color={primary} /></div><div><span className="mr-2 text-[10px] font-extrabold uppercase text-black/35 lg:hidden">Avg. score</span><b className="text-lg">{item.average_score}%</b></div><div><span className="mr-2 text-[10px] font-extrabold uppercase text-black/35 lg:hidden">Passed</span><b className="text-lg">{item.passed}</b></div></article>})}</div></section>

    <section className="mt-10"><h2 className="text-2xl font-extrabold uppercase">Recent results</h2><div className="mt-4 overflow-hidden border border-black/10 bg-white shadow-sm"><div className="hidden grid-cols-[minmax(180px,1.2fr)_minmax(150px,1fr)_minmax(180px,1.3fr)_90px_120px_130px] items-center gap-5 border-b border-black/10 bg-black/[.03] px-5 py-4 text-xs font-extrabold uppercase tracking-wide text-black/45 lg:grid"><span>Learner</span><span>Retailer</span><span>Quiz</span><span>Score</span><span>Result</span><span>Completed</span></div>{(report?.recent.length ?? 0) === 0 ? <p className="p-8 text-center text-black/50">No completed training yet.</p> : report!.recent.map((item, index) => <article key={`${item.learner_email}-${item.quiz_title}-${index}`} className="grid min-h-20 gap-4 border-b border-black/10 px-5 py-5 last:border-0 lg:grid-cols-[minmax(180px,1.2fr)_minmax(150px,1fr)_minmax(180px,1.3fr)_90px_120px_130px] lg:items-center lg:gap-5"><div className="min-w-0 break-words font-semibold">{item.learner_email}</div><div><span className="mr-2 text-[10px] font-extrabold uppercase text-black/35 lg:hidden">Retailer</span>{item.company_name}</div><div><span className="mr-2 text-[10px] font-extrabold uppercase text-black/35 lg:hidden">Quiz</span>{item.quiz_title}</div><div><span className="mr-2 text-[10px] font-extrabold uppercase text-black/35 lg:hidden">Score</span><b>{item.score}%</b></div><div><span className={item.passed ? "inline-flex bg-green-100 px-2 py-1 text-xs font-bold uppercase text-green-800" : "inline-flex bg-red-100 px-2 py-1 text-xs font-bold uppercase text-red-800"}>{item.passed ? "Passed" : "Needs retry"}</span></div><div className="text-black/50"><span className="mr-2 text-[10px] font-extrabold uppercase text-black/35 lg:hidden">Completed</span>{new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(new Date(item.submitted_at))}</div></article>)}</div></section>
  </main></div>;
}
