import Image from "next/image";
import Link from "next/link";
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import InviteForm from "./invite-form";
import CopyInviteLink from "./copy-invite-link";
import { managePlatformInvitation, openManufacturerDashboard } from "./actions";
import ManufacturerForm from "./manufacturer-form";
import PlatformUserControls, { type ManagedPlatformUser } from "./platform-user-controls";

type Manufacturer = { id: string; name: string; slug: string; status: string; logo_url: string | null; team_count: number; retailer_count: number; quiz_count: number };
type UserRecord = ManagedPlatformUser & { created_at: string; last_sign_in_at: string | null };
type Invitation = { id: string; email: string; invitation_type: string; role: string; status: string; manufacturer_name: string | null; company_name: string | null; expires_at: string; created_at: string };
type Dashboard = { counts: { users: number; manufacturers: number; retailers: number; pending_invitations: number }; users: UserRecord[]; manufacturers: Manufacturer[]; invitations: Invitation[] };
type ReferenceData = { manufacturers: { id: string; name: string }[]; companies: { id: string; name: string }[] };
type ContactInquiry = { id:string;created_at:string;name:string;email:string;company:string;job_title:string|null;website:string|null;retailer_count:string|null;current_process:string|null;primary_goal:string;launch_timeline:string|null;service_tier:string|null;status:string };

export default async function PlatformPage({ searchParams }: { searchParams: Promise<{ error?: string; manufacturerError?: string; invited?: string; created?: string; updated?:string }> }) {
  const params = await searchParams;
  const supabase = await createSupabaseServerClient();
  const { data: auth } = await supabase.auth.getUser();
  if (!auth.user) redirect("/login?next=/platform");
  const [{ data, error }, { data: references }, {data: inquiryRows}] = await Promise.all([supabase.rpc("platform_dashboard"), supabase.rpc("platform_reference_data"),supabase.rpc("platform_contact_inquiries")]);
  if (error || !data) redirect("/app");
  const dashboard = data as Dashboard;
  const options = references as ReferenceData;
  const inquiries=(inquiryRows??[]) as ContactInquiry[];

  return <div className="min-h-screen bg-[#f3f3f1] text-black">
    <header className="border-b border-black/10 bg-black text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/platform" className="flex items-center gap-4"><span className="text-2xl font-black uppercase tracking-[-0.05em]">Jobber<span className="text-[#ff4f1f]">Train</span></span><span className="border-l border-white/20 pl-4 text-xs font-extrabold uppercase tracking-[0.2em] text-white/60">Platform Control</span></Link><form action="/logout" method="post"><button type="submit" className="text-sm font-bold uppercase tracking-wide text-white/60 hover:text-white">Sign out</button></form></div></header>
    <main className="mx-auto max-w-7xl px-5 py-10 lg:px-8 lg:py-14">
      <p className="text-sm font-extrabold uppercase italic tracking-[0.2em] text-[#d93a10]">SaaS operations</p><h1 className="mt-2 text-4xl font-extrabold uppercase tracking-tight sm:text-5xl">Platform overview</h1><p className="mt-3 max-w-2xl text-black/60">Manage manufacturer customers, retailer access, users, and invitations across the entire training platform.</p>
      <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Users",dashboard.counts.users],["Manufacturers",dashboard.counts.manufacturers],["Retailers",dashboard.counts.retailers],["Pending invites",dashboard.counts.pending_invitations]].map(([label,value]) => <article key={label} className="border border-black/10 bg-white p-6 shadow-sm"><p className="text-sm font-extrabold uppercase tracking-wide text-black/45">{label}</p><p className="mt-2 text-4xl font-extrabold">{value}</p></article>)}</section>

      <section className="mt-10"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><p className="text-sm font-extrabold uppercase tracking-[0.16em] text-[#d93a10]">Sales pipeline</p><h2 className="mt-2 text-2xl font-extrabold uppercase">Contact inquiries</h2></div><p className="max-w-md text-sm text-black/50">Direct manufacturer requests submitted through the JobberTrain contact page.</p></div><div className="mt-5 grid gap-4">{inquiries.map(inquiry=><article key={inquiry.id} className="border border-black/10 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-extrabold uppercase">{inquiry.company}</h3><span className="bg-[#ff4f1f]/10 px-2 py-1 text-[10px] font-extrabold uppercase text-[#b92e08]">{inquiry.service_tier||"Plan undecided"}</span></div><p className="mt-2 text-sm"><b>{inquiry.name}</b>{inquiry.job_title?` · ${inquiry.job_title}`:""}</p><a href={`mailto:${inquiry.email}`} className="mt-1 block text-sm font-bold text-[#d93a10] hover:underline">{inquiry.email}</a></div><div className="text-sm text-black/45"><p>{new Date(inquiry.created_at).toLocaleDateString()}</p><p className="mt-1">{inquiry.retailer_count||"Retailer count not provided"}</p><p>{inquiry.launch_timeline||"Timeline not provided"}</p></div></div><div className="mt-5 border-t border-black/10 pt-4"><p className="text-xs font-extrabold uppercase tracking-wide text-black/40">Primary goal</p><p className="mt-2 leading-7 text-black/65">{inquiry.primary_goal}</p>{inquiry.current_process&&<><p className="mt-4 text-xs font-extrabold uppercase tracking-wide text-black/40">Current training process</p><p className="mt-2 text-sm leading-6 text-black/55">{inquiry.current_process}</p></>}</div></article>)}{!inquiries.length&&<p className="border-2 border-dashed border-black/10 bg-white p-8 text-center text-black/45">No contact inquiries yet.</p>}</div></section>

      <section id="invite" className="mt-10 border border-black/10 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><p className="text-sm font-extrabold uppercase tracking-[0.16em] text-[#d93a10]">Controlled onboarding</p><h2 className="mt-2 text-2xl font-extrabold uppercase">Invite a user</h2></div><p className="max-w-md text-sm text-black/50">Creates a seven-day invitation record. Email delivery will be connected after production mail is configured.</p></div>{params.error && <div className="mt-5 border-l-4 border-red-700 bg-red-50 p-4 font-semibold text-red-900">{params.error}</div>}{params.invited && <div className="mt-5 border-l-4 border-green-600 bg-green-50 p-4 font-semibold text-green-900">Invitation created.</div>}<div className="mt-6"><InviteForm manufacturers={options?.manufacturers ?? []} companies={options?.companies ?? []} /></div></section>

      <section id="manufacturers" className="mt-10 border border-black/10 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><p className="text-sm font-extrabold uppercase tracking-[0.16em] text-[#d93a10]">Customer setup</p><h2 className="mt-2 text-2xl font-extrabold uppercase">Add manufacturer</h2></div><p className="max-w-md text-sm text-black/50">Creates a private tenant, gives your platform account admin access, and can generate the owner invitation immediately.</p></div>{params.manufacturerError && <div className="mt-5 border-l-4 border-red-700 bg-red-50 p-4 font-semibold text-red-900">{params.manufacturerError}</div>}{params.created && <div className="mt-5 border-l-4 border-green-600 bg-green-50 p-4 font-semibold text-green-900">Manufacturer created successfully.</div>}<div className="mt-6"><ManufacturerForm /></div></section>

      <section className="mt-10"><div className="flex items-end justify-between"><div><p className="text-sm font-extrabold uppercase tracking-[0.16em] text-[#d93a10]">Customers</p><h2 className="mt-2 text-2xl font-extrabold uppercase">Manufacturers</h2><p className="mt-2 text-sm text-black/50">Choose a manufacturer to enter its branded administration dashboard.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{dashboard.manufacturers.map((item) => <article key={item.id} className="border border-black/10 bg-white p-6 shadow-sm"><div className="flex min-h-11 items-center justify-between gap-4">{item.logo_url ? <Image src={item.logo_url} alt={`${item.name} logo`} width={150} height={42} className="max-h-10 w-auto object-contain" unoptimized /> : <h3 className="text-xl font-extrabold uppercase">{item.name}</h3>}<span className="bg-green-100 px-2 py-1 text-xs font-extrabold uppercase text-green-800">{item.status}</span></div><div className="mt-6 grid grid-cols-3 gap-3 border-t border-black/10 pt-5 text-center"><div><b className="block text-xl">{item.team_count}</b><span className="text-xs text-black/45">Team</span></div><div><b className="block text-xl">{item.retailer_count}</b><span className="text-xs text-black/45">Retailers</span></div><div><b className="block text-xl">{item.quiz_count}</b><span className="text-xs text-black/45">Quizzes</span></div></div><form action={openManufacturerDashboard} className="mt-5"><input type="hidden" name="manufacturerId" value={item.id} /><button className="min-h-11 w-full bg-black px-4 text-sm font-extrabold uppercase text-white transition hover:bg-[#ff4f1f]">Open dashboard</button></form><Link href={`/m/${item.slug}`} target="_blank" className="mt-4 block text-center text-sm font-extrabold uppercase text-[#d93a10] hover:underline">View public page ↗</Link></article>)}</div></section>

      <section id="users" className="mt-10"><p className="text-sm font-extrabold uppercase tracking-[0.16em] text-[#d93a10]">Directory</p><h2 className="mt-2 text-2xl font-extrabold uppercase">Users</h2><p className="mt-2 max-w-2xl text-sm text-black/50">Manage each membership independently. Removing brand access never deletes the user or their other access.</p>{params.updated&&<div className="mt-5 border-l-4 border-green-600 bg-green-50 p-4 font-semibold text-green-900">Access updated.</div>}<div className="mt-5 grid gap-4">{dashboard.users.map((user)=><article key={user.id} className="border border-black/10 bg-white shadow-sm"><div className="grid gap-3 p-5 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div><b>{user.email}</b><div className="mt-2 flex flex-wrap gap-2">{user.platform_owner&&<span className="bg-[#ff4f1f]/10 px-2 py-1 text-[10px] font-extrabold uppercase text-[#b92e08]">JobberTrain team</span>}<span className="bg-black/5 px-2 py-1 text-[10px] font-extrabold uppercase text-black/50">{user.manufacturers.length} brand memberships</span><span className="bg-black/5 px-2 py-1 text-[10px] font-extrabold uppercase text-black/50">{user.companies.length} retailer memberships</span></div></div><p className="text-sm text-black/45">Last sign-in {user.last_sign_in_at?new Date(user.last_sign_in_at).toLocaleDateString():"Never"}</p></div><PlatformUserControls user={user} currentUserId={auth.user.id}/></article>)}</div></section>

      <section id="invitations" className="mt-10"><p className="text-sm font-extrabold uppercase tracking-[0.16em] text-[#d93a10]">Onboarding queue</p><h2 className="mt-2 text-2xl font-extrabold uppercase">Invitations</h2><div className="mt-5 overflow-x-auto border border-black/10 bg-white shadow-sm"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-black/10 bg-white text-xs uppercase tracking-wide text-black/45"><tr><th className="px-5 py-4">Email</th><th className="px-5 py-4">Role</th><th className="px-5 py-4">Organization</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Expires</th><th className="px-5 py-4">Actions</th></tr></thead><tbody>{dashboard.invitations.length?dashboard.invitations.map(invite=><tr key={invite.id} className="border-t border-black/5"><td className="px-5 py-4 font-semibold">{invite.email}</td><td className="px-5 py-4 capitalize">{invite.invitation_type==="platform_owner"?"JobberTrain team":invite.role.replaceAll("_"," ")}</td><td className="px-5 py-4">{invite.invitation_type==="platform_owner"?"JobberTrain":invite.manufacturer_name||invite.company_name||" - "}</td><td className="px-5 py-4 capitalize">{invite.status}</td><td className="px-5 py-4 text-black/50">{new Date(invite.expires_at).toLocaleDateString()}</td><td className="px-5 py-4"><div className="flex gap-4">{invite.status==="pending"&&<CopyInviteLink token={invite.id}/>} {invite.status!=="accepted"&&<form action={managePlatformInvitation}><input type="hidden" name="invitationId" value={invite.id}/><button name="action" value="renew" className="font-bold">Renew</button></form>}{["pending","sent"].includes(invite.status)&&<form action={managePlatformInvitation}><input type="hidden" name="invitationId" value={invite.id}/><button name="action" value="revoke" className="font-bold text-red-700">Revoke</button></form>}</div></td></tr>):<tr><td colSpan={6} className="px-5 py-10 text-center text-black/45">No invitations yet.</td></tr>}</tbody></table></div></section>
    </main>
  </div>;
}
