import Link from "next/link";
import { notFound,redirect } from "next/navigation";
import { ManufacturerHeader } from "@/components/manufacturer-shell";
import { getActiveBrand } from "@/lib/branding";
import { DealerProgram,effectiveProgramStatus,formatProgramDate,programStatusClass } from "@/lib/dealer-programs";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { expressProgramInterest } from "../actions";
import { ProgramViewTracker } from "../program-view-tracker";

type Related={position:number;products:{id:string;name:string;slug:string;tagline:string|null;model_sku:string|null}|null};
export default async function DealerProgramPage({params,searchParams}:{params:Promise<{programId:string}>;searchParams:Promise<{interested?:string;error?:string}>}){
  const{programId}=await params,query=await searchParams,supabase=await createSupabaseServerClient();
  const[{data:auth},brand,{data:programData},{data:relatedData},{data:eventData}]=await Promise.all([supabase.auth.getUser(),getActiveBrand(),supabase.from("dealer_programs").select("*").eq("id",programId).single(),supabase.from("dealer_program_products").select("position,products(id,name,slug,tagline,model_sku)").eq("program_id",programId).order("position"),supabase.from("dealer_program_events").select("event_type").eq("program_id",programId).eq("event_type","interest").limit(1)]);
  if(!auth.user)redirect("/login");if(!brand)redirect("/academies");if(!programData)notFound();
  const program=programData as DealerProgram,status=effectiveProgramStatus(program),related=(relatedData??[])as unknown as Related[],alreadyInterested=Boolean(eventData?.length);
  return <div className="min-h-screen bg-[#f4f4f2]"><ManufacturerHeader brand={brand} email={auth.user.email}/><ProgramViewTracker programId={programId}/><main className="mx-auto max-w-5xl px-5 py-10 lg:px-8 lg:py-14"><div className="flex flex-wrap items-center justify-between gap-4"><Link href={`/m/${brand.slug}/app/dealer-programs`} className="text-sm font-extrabold uppercase text-black/50">← Dealer Programs</Link>{brand.can_manage_training&&<Link href={`/m/${brand.slug}/app/programs?edit=${program.id}#program-form`} className="text-sm font-extrabold uppercase" style={{color:brand.primary_color}}>Edit program</Link>}</div>
    <article className="mt-7 overflow-hidden border border-black/10 bg-white shadow-sm"><header className="p-7 text-white sm:p-10" style={{backgroundColor:brand.secondary_color}}><div className="flex flex-wrap items-center justify-between gap-4"><span className={`inline-flex px-2 py-1 text-[10px] font-extrabold uppercase ${programStatusClass(status)}`}>{status}</span><span className="text-xs font-extrabold uppercase tracking-[.14em] text-white/50">Private dealer program</span></div><h1 className="mt-7 max-w-4xl text-4xl font-extrabold uppercase leading-[.95] tracking-tight sm:text-5xl">{program.title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/65">{program.summary}</p></header>
      <div className="grid gap-0 lg:grid-cols-[1fr_320px]"><div className="p-7 sm:p-10"><section><p className="text-xs font-extrabold uppercase tracking-[.18em]" style={{color:brand.primary_color}}>Program offer</p><div className="mt-4 whitespace-pre-wrap text-lg leading-8 text-black/70">{program.offer_details}</div></section>{program.eligibility&&<section className="mt-9 border-l-4 bg-black/[.035] p-5" style={{borderColor:brand.primary_color}}><h2 className="font-extrabold uppercase">Eligibility</h2><p className="mt-3 whitespace-pre-wrap leading-7 text-black/60">{program.eligibility}</p></section>}{related.length>0&&<section className="mt-10"><h2 className="text-2xl font-extrabold uppercase">Related products</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{related.map(item=>item.products&&<Link key={item.products.id} href={`/m/${brand.slug}/products/${item.products.slug}`} className="border border-black/10 p-5 transition hover:border-black"><span className="text-[10px] font-extrabold uppercase text-black/35">{item.products.model_sku||"Product"}</span><b className="mt-2 block uppercase">{item.products.name}</b><p className="mt-2 text-sm text-black/45">{item.products.tagline||"View product details and selling points."}</p></Link>)}</div></section>}{program.terms&&<section className="mt-10 border-t border-black/10 pt-6"><h2 className="text-sm font-extrabold uppercase text-black/45">Terms and limitations</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-black/50">{program.terms}</p></section>}</div>
        <aside className="border-t border-black/10 bg-[#f4f4f2] p-7 lg:border-l lg:border-t-0"><h2 className="font-extrabold uppercase">Program availability</h2><dl className="mt-5 divide-y divide-black/10 border-y border-black/10 text-sm"><div className="py-4"><dt className="text-xs font-extrabold uppercase text-black/35">Starts</dt><dd className="mt-1 font-bold">{program.starts_at?formatProgramDate(program.starts_at):"Available now"}</dd></div><div className="py-4"><dt className="text-xs font-extrabold uppercase text-black/35">Ends</dt><dd className="mt-1 font-bold">{program.ends_at?formatProgramDate(program.ends_at):"No published expiration"}</dd></div></dl>{program.flyer_path&&<Link href={`/m/${brand.slug}/app/dealer-programs/${program.id}/flyer`} target="_blank" className="mt-5 flex min-h-12 items-center justify-center border-2 border-black px-5 text-sm font-extrabold uppercase">Download PDF flyer</Link>}
          {query.error&&<p className="mt-5 bg-red-50 p-4 text-sm font-semibold text-red-900">{query.error}</p>}{(query.interested||alreadyInterested)&&!brand.can_manage_training?<div className="mt-5 border-l-4 border-green-700 bg-green-50 p-4 text-sm text-green-900"><b>Interest recorded.</b><p className="mt-1">The manufacturer can now follow up with your retailer.</p></div>:!brand.can_manage_training&&status==="active"?<form action={expressProgramInterest} className="mt-5"><input type="hidden" name="programId" value={program.id}/><button className="min-h-12 w-full px-5 font-extrabold uppercase text-white" style={{backgroundColor:brand.primary_color}}>{program.cta_label}</button></form>:null}
          {(program.contact_name||program.contact_email||program.contact_phone)&&<div className="mt-7 border-t border-black/10 pt-5"><h2 className="text-xs font-extrabold uppercase text-black/35">Program contact</h2>{program.contact_name&&<b className="mt-2 block">{program.contact_name}</b>}{program.contact_email&&<a href={`mailto:${program.contact_email}`} className="mt-1 block break-all text-sm font-bold hover:underline">{program.contact_email}</a>}{program.contact_phone&&<a href={`tel:${program.contact_phone}`} className="mt-1 block text-sm font-bold hover:underline">{program.contact_phone}</a>}</div>}
        </aside></div></article>
  </main></div>;
}
