create table public.manufacturer_notification_settings(manufacturer_id uuid primary key references public.manufacturers(id) on delete cascade,assignment_enabled boolean not null default true,due_soon_enabled boolean not null default true,due_soon_days int not null default 3,overdue_enabled boolean not null default true,overdue_repeat_days int not null default 7,certificate_enabled boolean not null default true,certified_dealer_enabled boolean not null default true,weekly_summary_enabled boolean not null default false,summary_email text,updated_at timestamptz not null default now());
create table public.notification_deliveries(id bigint generated always as identity primary key,manufacturer_id uuid not null references public.manufacturers(id) on delete cascade,notification_type text not null,recipient text not null,subject text not null,status text not null check(status in('sent','failed','skipped')),provider_id text,error text,dedupe_key text unique,created_at timestamptz not null default now());
alter table public.manufacturer_notification_settings enable row level security;alter table public.notification_deliveries enable row level security;revoke all on public.manufacturer_notification_settings,public.notification_deliveries from anon,authenticated;
create or replace function public.notification_center_dashboard()returns jsonb language plpgsql stable security definer set search_path='' as $f$declare mid uuid;result jsonb;begin select active_manufacturer_id into mid from public.profiles where id=auth.uid();if mid is null or not private.has_manufacturer_role(mid,array['owner','admin','content_manager']::public.manufacturer_role[])then raise exception'Permission denied';end if;insert into public.manufacturer_notification_settings(manufacturer_id)values(mid)on conflict do nothing;select jsonb_build_object('settings',(select to_jsonb(s)from public.manufacturer_notification_settings s where s.manufacturer_id=mid),'deliveries',coalesce((select jsonb_agg(to_jsonb(d)order by d.created_at desc)from(select * from public.notification_deliveries where manufacturer_id=mid order by created_at desc limit 25)d),'[]'))into result;return result;end$f$;
create or replace function public.save_notification_settings(assignment_enabled boolean,due_soon_enabled boolean,due_soon_days int,overdue_enabled boolean,overdue_repeat_days int,certificate_enabled boolean,certified_dealer_enabled boolean,weekly_summary_enabled boolean,summary_email text)returns void language plpgsql security definer set search_path='' as $f$declare mid uuid;begin select active_manufacturer_id into mid from public.profiles where id=auth.uid();if mid is null or not private.has_manufacturer_role(mid,array['owner','admin','content_manager']::public.manufacturer_role[])then raise exception'Permission denied';end if;insert into public.manufacturer_notification_settings values(mid,assignment_enabled,due_soon_enabled,greatest(due_soon_days,1),overdue_enabled,greatest(overdue_repeat_days,1),certificate_enabled,certified_dealer_enabled,weekly_summary_enabled,nullif(trim(summary_email),''),now())on conflict(manufacturer_id)do update set assignment_enabled=excluded.assignment_enabled,due_soon_enabled=excluded.due_soon_enabled,due_soon_days=excluded.due_soon_days,overdue_enabled=excluded.overdue_enabled,overdue_repeat_days=excluded.overdue_repeat_days,certificate_enabled=excluded.certificate_enabled,certified_dealer_enabled=excluded.certified_dealer_enabled,weekly_summary_enabled=excluded.weekly_summary_enabled,summary_email=excluded.summary_email,updated_at=now();end$f$;
revoke all on function public.notification_center_dashboard(),public.save_notification_settings(boolean,boolean,int,boolean,int,boolean,boolean,boolean,text)from public,anon;grant execute on function public.notification_center_dashboard(),public.save_notification_settings(boolean,boolean,int,boolean,int,boolean,boolean,boolean,text)to authenticated;
alter function public.notification_center_dashboard() volatile;
create or replace function public.record_notification_delivery(notification_type text,recipient text,subject text,delivery_status text,provider_id text,delivery_error text,dedupe_key text default null)returns void language plpgsql security definer set search_path='' as $f$declare mid uuid;begin select active_manufacturer_id into mid from public.profiles where id=auth.uid();if mid is null or not private.has_manufacturer_role(mid,array['owner','admin','content_manager']::public.manufacturer_role[])then raise exception'Permission denied';end if;insert into public.notification_deliveries(manufacturer_id,notification_type,recipient,subject,status,provider_id,error,dedupe_key)values(mid,notification_type,recipient,subject,delivery_status,provider_id,left(delivery_error,500),dedupe_key)on conflict(dedupe_key)do nothing;end$f$;
revoke all on function public.record_notification_delivery(text,text,text,text,text,text,text)from public,anon;grant execute on function public.record_notification_delivery(text,text,text,text,text,text,text)to authenticated;
create or replace function public.scheduled_notification_queue(run_date date default current_date)returns table(manufacturer_id uuid,manufacturer_name text,manufacturer_slug text,logo_url text,primary_color text,recipient text,notification_type text,content_title text,due_at timestamptz,dedupe_key text)language sql security definer set search_path='' as $f$
with quiz_rows as(select m.id,m.name,m.slug,m.logo_url,m.primary_color,u.email,q.title,a.due_at,s.due_soon_days,s.overdue_repeat_days,s.due_soon_enabled,s.overdue_enabled from public.manufacturers m join public.manufacturer_notification_settings s on s.manufacturer_id=m.id join public.manufacturer_companies mc on mc.manufacturer_id=m.id and mc.status='active' join public.company_quiz_assignments a on a.company_id=mc.company_id join public.quizzes q on q.id=a.quiz_id and q.manufacturer_id=m.id join public.company_members cm on cm.company_id=a.company_id and cm.status='active' join auth.users u on u.id=cm.user_id where a.due_at is not null and not exists(select 1 from public.quiz_attempts qa where qa.company_id=a.company_id and qa.quiz_id=a.quiz_id and qa.user_id=cm.user_id and qa.status='completed' and qa.score>=q.passing_score)),queue as(select *,case when due_at::date-run_date=due_soon_days and due_soon_enabled then 'due_soon' when run_date>due_at::date and overdue_enabled and mod(run_date-due_at::date,overdue_repeat_days)=0 then 'overdue' end kind from quiz_rows)
select id,name,slug,logo_url,primary_color,email,kind,title,due_at,format('%s:%s:%s:%s',id,email,kind,run_date)from queue where kind is not null and not exists(select 1 from public.notification_deliveries d where d.dedupe_key=format('%s:%s:%s:%s',queue.id,queue.email,queue.kind,run_date));$f$;
revoke all on function public.scheduled_notification_queue(date)from public,anon,authenticated;grant execute on function public.scheduled_notification_queue(date)to service_role;
