create table public.certification_programs(id uuid primary key default gen_random_uuid(),manufacturer_id uuid not null references public.manufacturers(id) on delete cascade,name text not null,description text,minimum_certified_learners int not null default 1 check(minimum_certified_learners>0),validity_months int check(validity_months is null or validity_months>0),status text not null default 'active' check(status in('draft','active','archived')),created_at timestamptz not null default now());
create table public.certification_requirements(id uuid primary key default gen_random_uuid(),program_id uuid not null references public.certification_programs(id) on delete cascade,content_type text not null check(content_type in('quiz','course')),content_id uuid not null,position int not null,unique(program_id,content_type,content_id));
create table public.company_certification_assignments(program_id uuid not null references public.certification_programs(id) on delete cascade,company_id uuid not null references public.companies(id) on delete cascade,assigned_at timestamptz not null default now(),primary key(program_id,company_id));
alter table public.certification_programs enable row level security;alter table public.certification_requirements enable row level security;alter table public.company_certification_assignments enable row level security;
revoke all on public.certification_programs,public.certification_requirements,public.company_certification_assignments from anon,authenticated;

create or replace function public.create_certification_program(program_name text,program_description text,minimum_learners int,valid_months int,requirements jsonb) returns uuid language plpgsql security definer set search_path='' as $f$ declare mid uuid;pid uuid;item jsonb;begin select active_manufacturer_id into mid from public.profiles where id=auth.uid();if mid is null or not private.has_manufacturer_role(mid,array['owner','admin','content_manager']::public.manufacturer_role[]) then raise exception 'Permission denied';end if;if nullif(trim(program_name),'') is null or jsonb_array_length(requirements)=0 then raise exception 'Name and requirements are required';end if;insert into public.certification_programs(manufacturer_id,name,description,minimum_certified_learners,validity_months,status)values(mid,trim(program_name),nullif(trim(program_description),''),greatest(minimum_learners,1),valid_months,'active')returning id into pid;for item in select * from jsonb_array_elements(requirements) loop insert into public.certification_requirements(program_id,content_type,content_id,position)values(pid,item->>'type',(item->>'id')::uuid,coalesce((item->>'position')::int,0));end loop;return pid;end $f$;

create or replace function public.assign_certification_program(target_program_id uuid,target_company_ids uuid[]) returns int language plpgsql security definer set search_path='' as $f$ declare mid uuid;cid uuid;req record;total int:=0;begin select active_manufacturer_id into mid from public.profiles where id=auth.uid();if mid is null or not private.has_manufacturer_role(mid,array['owner','admin','content_manager']::public.manufacturer_role[]) or not exists(select 1 from public.certification_programs where id=target_program_id and manufacturer_id=mid) then raise exception 'Permission denied';end if;foreach cid in array target_company_ids loop if exists(select 1 from public.manufacturer_companies where manufacturer_id=mid and company_id=cid and status='active') then insert into public.company_certification_assignments values(target_program_id,cid,now())on conflict do nothing;for req in select * from public.certification_requirements where program_id=target_program_id loop if req.content_type='quiz' then insert into public.company_quiz_assignments(company_id,quiz_id,is_required)values(cid,req.content_id,true)on conflict(company_id,quiz_id)do update set is_required=true;else insert into public.company_course_assignments(company_id,course_id,is_required)values(cid,req.content_id,true)on conflict(company_id,course_id)do update set is_required=true;end if;end loop;total:=total+1;end if;end loop;return total;end $f$;

create or replace function public.manufacturer_certification_dashboard() returns jsonb language plpgsql stable security definer set search_path='' as $f$ declare mid uuid;result jsonb;begin select active_manufacturer_id into mid from public.profiles where id=auth.uid();if mid is null or not private.has_manufacturer_role(mid,array['owner','admin','content_manager']::public.manufacturer_role[]) then raise exception 'Permission denied';end if;with programs as(select p.*,coalesce(jsonb_agg(jsonb_build_object('type',r.content_type,'id',r.content_id,'title',case when r.content_type='quiz' then q.title else c.title end,'position',r.position)order by r.position)filter(where r.id is not null),'[]') requirements from public.certification_programs p left join public.certification_requirements r on r.program_id=p.id left join public.quizzes q on r.content_type='quiz' and q.id=r.content_id left join public.courses c on r.content_type='course' and c.id=r.content_id where p.manufacturer_id=mid group by p.id),assignments as(select a.program_id,a.company_id,co.name company_name,count(distinct cm.user_id)::int learner_count from public.company_certification_assignments a join programs p on p.id=a.program_id join public.companies co on co.id=a.company_id left join public.company_members cm on cm.company_id=a.company_id and cm.status='active' group by a.program_id,a.company_id,co.name)select jsonb_build_object('programs',coalesce((select jsonb_agg(to_jsonb(p)order by p.created_at desc)from programs p),'[]'),'assignments',coalesce((select jsonb_agg(to_jsonb(a))from assignments a),'[]'))into result;return result;end $f$;
revoke all on function public.create_certification_program(text,text,int,int,jsonb),public.assign_certification_program(uuid,uuid[]),public.manufacturer_certification_dashboard() from public,anon;grant execute on function public.create_certification_program(text,text,int,int,jsonb),public.assign_certification_program(uuid,uuid[]),public.manufacturer_certification_dashboard() to authenticated;
