create table public.certificates(id uuid primary key default gen_random_uuid(),manufacturer_id uuid not null references public.manufacturers(id),user_id uuid not null references auth.users(id),content_type text not null check(content_type in('quiz','course')),content_id uuid not null,title text not null,audience_key text not null,issued_at timestamptz not null default now(),unique(manufacturer_id,user_id,content_type,content_id,audience_key));
alter table public.certificates enable row level security;
create policy "learners read own certificates" on public.certificates for select to authenticated using((select auth.uid())=user_id);
revoke all on public.certificates from anon,authenticated;grant select on public.certificates to authenticated;
create or replace function public.sync_my_certificates() returns setof public.certificates language plpgsql security definer set search_path='' as $f$ declare mid uuid; begin if auth.uid() is null then raise exception 'Authentication required';end if;select active_manufacturer_id into mid from public.profiles where id=auth.uid();
insert into public.certificates(manufacturer_id,user_id,content_type,content_id,title,audience_key,issued_at)
select mid,auth.uid(),'quiz',q.id,q.title,coalesce(a.company_id::text,'team'),a.submitted_at from public.quiz_attempts a join public.quizzes q on q.id=a.quiz_id where a.user_id=auth.uid() and q.manufacturer_id=mid and a.status='completed' and a.score>=q.passing_score on conflict do nothing;
with block_counts as(select m.course_id,count(b.id) total from public.course_modules m join public.course_blocks b on b.module_id=m.id group by m.course_id),done as(select p.course_id,p.company_id::text audience_key,count(*) completed,max(p.completed_at) finished from public.course_block_progress p where p.user_id=auth.uid() group by p.course_id,p.company_id having count(*)>0 union all select p.course_id,'team',count(*),max(p.completed_at) from public.manufacturer_course_progress p where p.user_id=auth.uid() and p.manufacturer_id=mid group by p.course_id having count(*)>0)
insert into public.certificates(manufacturer_id,user_id,content_type,content_id,title,audience_key,issued_at) select mid,auth.uid(),'course',c.id,c.title,d.audience_key,d.finished from done d join block_counts bc on bc.course_id=d.course_id and d.completed>=bc.total join public.courses c on c.id=d.course_id and c.manufacturer_id=mid on conflict do nothing;
return query select * from public.certificates c where c.user_id=auth.uid() and c.manufacturer_id=mid order by c.issued_at desc;end $f$;
revoke all on function public.sync_my_certificates() from public,anon;grant execute on function public.sync_my_certificates() to authenticated;
