import Link from "next/link";
import {redirect} from "next/navigation";
import CsvImporter from "@/components/csv-importer";
import {ManufacturerHeader} from "@/components/manufacturer-shell";
import {getActiveBrand} from "@/lib/branding";
import {createSupabaseServerClient} from "@/lib/supabase/server";
import {importRetailers} from "./actions";

export default async function RetailerImportPage({searchParams}:{searchParams:Promise<{error?:string}>}) {
  const query=await searchParams;const supabase=await createSupabaseServerClient();const [{data:auth},brand]=await Promise.all([supabase.auth.getUser(),getActiveBrand()]);
  if(!auth.user)redirect("/login");if(!brand?.can_manage_training)redirect("/app");
  return <div className="min-h-screen bg-[#f4f4f2]"><ManufacturerHeader brand={brand} email={auth.user.email}/><main className="mx-auto max-w-4xl px-5 py-10 lg:px-8 lg:py-14"><Link href={`/m/${brand.slug}/app/retailers`} className="font-bold text-black/50">← Retailers</Link><p className="mt-7 text-sm font-extrabold uppercase italic tracking-[.2em]" style={{color:brand.primary_color}}>Bulk directory</p><h1 className="mt-2 text-4xl font-extrabold uppercase tracking-tight sm:text-5xl">Import retailers</h1><p className="mt-3 max-w-2xl text-black/60">Add retailer locations and contacts in bulk. Existing retailers in this academy are updated when their names match.</p>{query.error&&<div className="mt-5 bg-red-50 p-4 text-red-900">{query.error}</div>}<details open className="group mt-8 border border-black/10 bg-white"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 p-6 marker:content-none sm:p-8 [&::-webkit-details-marker]:hidden"><div><p className="text-xs font-extrabold uppercase tracking-[.16em]" style={{color:brand.primary_color}}>Before uploading</p><h2 className="mt-2 text-xl font-extrabold uppercase">Prepare the retailer CSV</h2></div><span className="text-xl transition group-open:rotate-45">+</span></summary><div className="border-t border-black/10 px-6 pb-7 pt-6 sm:px-8"><div className="grid gap-7 md:grid-cols-2"><div><h3 className="font-extrabold uppercase">Required</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6 text-black/65"><li>Keep the template headers unchanged</li><li>Enter one retailer location per row</li><li><b>name</b> is the only required field</li></ul></div><div><h3 className="font-extrabold uppercase">Duplicate handling</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6 text-black/65"><li>Name matching ignores capitalization</li><li>A matching retailer in this academy is updated</li><li>A new name creates and links a retailer</li></ul></div></div><div className="mt-6 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><b>Tip:</b> Use a location identifier in the name when a company has multiple stores, such as “Retailer Name - Indianapolis.”</div></div></details><CsvImporter mode="retailer" action={importRetailers} primary={brand.primary_color}/></main></div>;
}
